### ISSUE TITLE
Ticket Transactions not Synching Automatically

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1035]
I'm not sure what's going on.
Yesterday (Sat. May 27) I went to http://burlesque-expo.com/ticketing/transactions and saw that ticket transactions had not been synched since Feb. 13, 2017.  I tried synching things manually and got a 500 Server Error.

Today, I went to http://burlesque-expo.com/ticketing/ticket_items and synched manually and everything was fine.  So, I went back to http://burlesque-expo.com/ticketing/transactions and synched manually and everything seemed to work.  I'll check in in a few hours and see if automatic synching has resumed.  If it has, I'll close or re-cast this bug.

**Comment by bethlakshmi** [comment]
The cron script is/was definitely broken.  I found at least two settings errors coming from my move of the system between folders as part of the upgrade.  And I think it's still not right. I can replicate the error (at least on live) so I'll keep tracking.

**Comment by bethlakshmi** [comment]
Found it!  Fixed it live.  Checking in code soon.
