### ISSUE TITLE
BUG: Performers unable to submit act bids

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1041]
I got a message from Osceanna Rose (profile: Osceanna1966; http://burlesque-expo.com/profile/landing_page/1280) saying she couldn't submit her act.  I went and edited her payment email to match her BurlExpo email.  The application fee now shows up as a paid ticket when I view her profile, but she still can't submit the act.  I hijacked her account and verified that, yes, if you try and submit the act, you get the "You haven't Paid Yet" message -- but she obviously has. 

UPDATE: Same issue with Mr. & Mrs. Fucksmart, http://burlesque-expo.com/profile/landing_page/1651

**Comment by bethlakshmi** [comment]
I have the pull request pending, but I hot fixed it on the site.

Tested live with the two users mentioned above, so now both of their bids are submitted.
