### ISSUE TITLE
We deserve a sexy grid (for regular performers in shows)

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#1047]
We use essentially the same grid for vendors and shows, and it could be a lot sexier.

Problems:
- the 3 column is fixed in size and width - it doesn't scale well to mobile sites.
- the hover is not mobile friendly, also it shows up in strange places at times, and not near the person/business that is the target

I found a few examples I like, I want commentary:

http://preview.graygrids.com/item/impression-bootstrap-html5-event-and-conference-template/

The top half I like the most - since there's contact info available on hover and the layout scales well.  The bottom half, with rising & sinking images --- is dorky and a bit creepy.  Also it takes more photo editing than I know how how to do or want to learn.

http://demo.dhtheme.com/?theme=Eventus

Also nice, a bit less dynamic, which might be easier.

This might be a research in progress... need to talk ideas.

**Comment by burlexpo** [comment]
My impression is that the template is demonstrating several different grid styles and that we could use different styles for different parts of the site (like they do).  

1) http://preview.graygrids.com/item/impression-bootstrap-html5-event-and-conference-template/ 
I like "Gallery" for our Shows, if there's a way to display the performer's name over or near the image.  I like the going dark to indicate which image the user is focused on and I like the link to more information.  I think it would require us to have a separate "Performer Bio" page, but that's not a bad thing.  If there's not a way to add a label, I'd go with Blog for shows.

For Vendors, I like Blog, if it does what I think it does -- displays a little bit of info and then allows you to click a link to got to the full article.  

2) http://demo.dhtheme.com/?theme=Eventus

While there are features here it might be nice to use, I didn't like it nearly as much as the other one.  I did like their Pricing Tables display (under Features -- can't seem to link to it)

**Comment by bethlakshmi** [comment]
**On working on this I noticed this:**

http://www.burlesque-expo.com/scheduler/details/546/

It seems to me the grey box with the time/location in it, just seems really weird - long and skinny and lonely.  

Is that really how we want it, or do we have other layout concerns while I work on this grid?

**Other Question:  I**f we'd rather have popup pages inside the show page, with performer details, I could do that.  Usually that's a different icon.  There's nothing perfect, but this is common:

http://fontawesome.io/icon/external-link/

Changing the icon is trivial.  Doing the popup is some work, but not any more than doing a separate page.  Same difference.




FYI - CURRENT STATE:
- I've got the gallery displaying, statically, on our events page. 
- I merged the CSS of our site, and the template we chose to eliminate conflicts (I hope... I'll want a second eye)
- I used a clever django trick to make sure that I only include gallery CSS with this particular type of page, so I can limit CSS regressions on other pages.  I feel smart.

To do:
- dynamically show the performers - that's the big work
- get links working 
- design performer bio pages - also big work.

**Comment by bethlakshmi** [comment]
Hrmm... and another one - how is this?

![screen shot 2017-06-17 at 9 54 03 pm](https://user-images.githubusercontent.com/4542707/27257510-87e25d40-53a7-11e7-9c39-c8a8f34b43ff.png)

What I've hit is that different performers give us different size images.  The way this template works doesn't easily account for how we intend to feed it a dynamic set of images (I could explain more, but you'll regret it...). 

This was my best attempt - there's gaps where an image is short compared to the others in the row... but at least they all line up, are alphabetized left to right, and don't have huge weird gaps.

Thoughts?  

If you want the perfectly spaced alignment of the template... I will take a long time on it if no one has better ideas than I have...

**Comment by burlexpo** [comment]
That's fine. I'm pretty sure we could set up some text telling performers to upload portrait oriented pictures and even have a little script that rejected stuff that is wider than talk. 

--
Team BurlExpo
www.Burlesque-Expo.com
#BurlExpo

**Comment by bethlakshmi** [comment]
Sweet, I made a follow on ticket - I could use a priority on it, but if you need to wait to see this on test before you decide how important image management is, I understand.  In the meantime, I fell in love with the modal idea, and it's even easier than I thought, so I'm leaning this way, unless you 
![screen shot 2017-06-18 at 10 40 19 am](https://user-images.githubusercontent.com/4542707/27261525-90f97754-5412-11e7-9fe9-21630865344c.png)

I will do some coloring and tuning next (art deco font on name, creamy background, nice buttons, etc.)

**Comment by bethlakshmi** [comment]
@burlexpo - OK, I have a choice for you...

# OPTION 1 = 6 columns

Problem - I have some cases where names get cropped.  Alternatives involve a crappy layout where long names have their photos bumped out of alignment.  Or I spend a lot of time making the name text properly responsive (not a 20 minute answer... tried that).

6 columns on a regular screen:
![screen shot 2017-06-19 at 11 39 50 am](https://user-images.githubusercontent.com/4542707/27293817-8075f7e4-54e5-11e7-8d83-6a2f17ff6f50.png)

6 columns on a much narrower screen - see that Vanessa's name is cropped, so is Francine's probably. Also - the icons would need to be resized
![screen shot 2017-06-19 at 11 40 24 am](https://user-images.githubusercontent.com/4542707/27293812-7d43611a-54e5-11e7-8bcd-4f14c9354e39.png)

# OPTION 2 = 4 columns

Fewer performers per row, but not awful.  Easier to align things:

![screen shot 2017-06-19 at 11 46 14 am](https://user-images.githubusercontent.com/4542707/27293810-7ca60a46-54e5-11e7-8680-51991fbef534.png)
![screen shot 2017-06-19 at 11 45 31 am](https://user-images.githubusercontent.com/4542707/27293811-7cefd068-54e5-11e7-9f13-8aa533f02d80.png)

Option 3 - hybrid

I do 6 on a big screen, 4 on a smaller screen.  More work, but not impossible.  Blends these examples.
