### ISSUE TITLE
Connect rehearsal slots to shows

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1051]
There are two 1-hour rehearsal slots for each show.  Please connect them to the appropriate show.

**Comment by bethlakshmi** [comment]
done!

I can't easily test until you assign acts and make announcements.
Reminder - Act state changes now send email - so when you accept the first one, the template gets created.  Notes on how to add dynamic values are in the current templates, if you want to have act names, etc. in the mail.
