### ISSUE TITLE
Site is waaaaay too slow

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1054]
Most of the time (like 4 out of 5 times) loading any page on www.Burlesque-Expo.com takes forever.  Doesn't matter if the page is published, public, or in the admin section.  The site is so slow as an admin that it's almost impossible to use.

**Comment by bethlakshmi** [comment]
Hrm... I just did a restart of the apache servers and that temporarily seems to have speeded things up.  But that sure isn't a real fix.  I could do a nightly reboot via cron, but that can just be a bandaid on a head wound.

We already have caching, for regular people, but I'm seeing that it doesn't matter for admins  - we don't get the cache.   

Sites like this:  

https://www.django-cms.org/en/blog/2016/07/04/as-fast-as-possible-with-django-cms/

Suggest that the version of django-cms we're using (3.3.3) *should* be faster - but clearly not, and I'm wondering if adding bootstrap actually made it worse.

I'll continue to dig.  This won't be easy.

**Comment by bethlakshmi** [comment]
Current focus - 
- reduce the scope of ticket syncs
- review speeds on scheduling -  
   - the list of events when there's lots of events
   - the individual event data entry

**Comment by bethlakshmi** [comment]
If we want me to hit act review/act management - give me another ticket.

**Comment by burlexpo** [comment]
I know you want a ticket for everything that's slow, but the reality is that it's a moving target.  The problem is both broad (that is, lots of different things are slow) and inconsistent (but they're not always slow).  

This morning, it's taking 20+ seconds to just load the regular front page (www.Burlesque-Expo.com), it took 20+ seconds to load the general admin page (burlesque-expo.com/admin), and once I was on the Admin screen, it took 20+ seconds each to: load the Users; do a search of the users to find a particular user; and -- once the user was found -- to load her personal pane once I hijacked her profile.
