### ISSUE TITLE
Vendor grid needs mobile update

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#1055]
Follow on from #1047 

http://preview.graygrids.com/item/impression-bootstrap-html5-event-and-conference-template/

is a template I bought.

We like the "blog" for the vendor grid.  Need to update the vendor grid to the blog summary format, and then decommission the non-mobile mobile grid.

**Comment by burlexpo** [comment]
@bethlakshmi I played with this and it mostly looks fine.  Links work as intended, layout looks good.  Editing the header text seems to work fine.

Is there a way to force the images/logos so they fit in the entry? I'm particularly talking about "Glorious Pasties" or "Vixens Ahoy".
