### ISSUE TITLE
deduplicate shows on landing page

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#1063]
It's a rarity.  But when a performer is performing twice in 1 show, it looks goofy to show the same show twice on "Shows performer is appearing in" on the Right hand side of the landing page:

http://localhost:8282/gbe

![screen shot 2017-06-26 at 8 10 19 am](https://user-images.githubusercontent.com/4542707/27538635-efdb2df0-5a46-11e7-9ffc-aeed80c7db7c.png)

point of reference - account for "betty" last year (2017 Feb. gbe 11)

**Comment by burlexpo** [comment]
Alternative fix -- leave the duplicate shows, but add the name of the act afterwards.  i.e.,

The Mini Event - Opening Act
The Mini Event - 1812 Overdrive
