### ISSUE TITLE
Act bid review got hideous

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#1065]
![screen shot 2017-06-27 at 4 28 42 pm](https://user-images.githubusercontent.com/4542707/27608493-c3546ac0-5b55-11e7-9c21-0805773e1eb1.png)

This is likely a weakness in the original design that's been exacerbated by the recent work in styling for responsive design w. Bootstrap.  The answer is... more bootstrap.

My approach would just be to wrap the review form and the change-state form in two bootstrap grid columns, make them 50/50 on the screen in medium/large screens and 100% on phones & small tablets.  I'd make the coordinator box show up below the reviewer box.

**Comment by burlexpo** [comment]
Yes, sounds fine.  (Low impact on me; I almost never use my phone to view the site).
