### ISSUE TITLE
Making Ticketing Page Sexy

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1068]
Apply http://demo.graygrids.com/themes/impression/pricing.html
to http://burlesque-expo.com/ticketing/

![screen shot 2017-07-05 at 6 45 50 pm](https://user-images.githubusercontent.com/4542707/27888097-3f17f8cc-61b2-11e7-9f05-18e561708d7e.png)

**Comment by bethlakshmi** [comment]
OK... some questions... (the parens are as assessment on what's easy, moderate, hard)

- Can I change button color to something in our pallette?  Bright maroon maybe? (easy)
- OK to leave it as white background?  I think it will pop nicely. (easy)
- It's super subtle but one of these is highlighted (standard) by default, the other two get highlighted when you hover on them... it subtly draws the eye.  Do you wan that? (moderate)
- Do you want the ability to edit the icons?  These templates use:
    - http://simplelineicons.com/
    - or - http://fontawesome.io/icons/
- the bulleted list is showing a standard list of items and what's in or out.  Do you want me to build a configuration for that?  (between moderate and hard depending what we design)
- where does the current BPT text go?  There's no space for free form text here. (easy)

**Comment by bethlakshmi** [comment]
Notes from today's conversation:
 - yes, offer selectable icons.
 - make the header 3 lines long, center/center aligned
 - make a way to add multiple lines of short text, w. a neutral icon (not checkbox and minus sign)
 - make algorithm to keep lines of text center aligned
 - make pricing be a range - lowest and highest, to cover ticket variance.
 - separate tickets by conference
