### ISSUE TITLE
Ticketing bug affects ability to show multi-tier tickets

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#1071]
Example - on the site right now, we have VIP tickets and regular tickets for the shows.

Only VIP is shown.

@burlexpo  - we need to discuss business logic, this gets complex to write up.  There's no good answer, and I need you to understand the impact on promo.

For notes, here's the sample data I get from BPT

```
<document>
<result>success</result>
<resultcode>000000</resultcode>
<note/>
<totalprices>12</totalprices>
<price>
<price_id>4513068</price_id>
<live>n</live>
<name>Whole Shebang</name>
<value>125.00</value>
<service_fee>5.37</service_fee>
<venue_fee>0.00</venue_fee>
<price_available>50</price_available></price>

```

**Comment by burlexpo** [comment]
We've always had multi-tier tickets.  The way we've dealt with it is to show the most expensive price point on the site.  When people click, they can discover there are (potentially) less expensive tickets.  

The other thing I think I'd be super happy with is just removing the prices from tickets on our site at all.

**Comment by bethlakshmi** [comment]
OK... could do that.  And it's OK that the ticket says "VIP"?
