### ISSUE TITLE
Can't Edit

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1089]
Something is amiss with the editing tool.

I can get to "Pages" but when I try to edit any page, I get a Server 500 error.  This is both when I click the "Edit Page" button in the upper right corner and also when I use the "Pages" function and try to view a page in editing mode.

**Comment by bethlakshmi** [comment]
Argh - for some reason, you have access to a "multi-column" plugin that my account DOESN'T.

I put the plugin for multi-column back into our system manually, so you are no longer blocked.  I'll take the action to try to scrub our data even better and really, really remove any data for it.

In the meantime, avoid adding multi-columns to anything - use the bootstrap grid, instead, it's mobile friendly and more fully featured.

**Comment by bethlakshmi** [comment]
I think gone with the passage of time ??
