### ISSUE TITLE
Wall-o-text on ticketing/index

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#109]
I know we're all children of the '90s, but would it be acceptable to maybe get some collapse on the descriptions so people can see all of their options on the screen?

**Comment by jonkiparsky** [comment]
Layout is no longer a dev team problem, since we have CMS. Closing.

**Comment by burlexpo** [comment]
That would be true if the CMS could b used for every page.  Unfortunately, it can only be used for about 40% of the pages; most are generated dynamically (like the 'Wall o' Text Ticketing page'), others (like bid forms) have the text hard-coded into them.

**Comment by jonkiparsky** [comment]
@burlexpo - I can no longer access /ticketing/index, and /ticketing/ is pretty inoffensive. Closing.

**Comment by burlexpo** [comment]
Currently we have one type of ticket on sale so there's not a lot of text on this page.  Come January we'll have 10+ types -- which is when I think that this will offend your sense of aesthetics again.  But up to you.
