### ISSUE TITLE
Change Vote menus on http://gbeadmin.webfactional.com/act/review/7

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#110]
*This does NOT have to be done before August 22*

I'd like the reviewers to be able express a first choice and a second choice; often we get things where a n act is a 'Strong Yes' for one show (i.e., Newcomer's Showcase) but a 'Weak Yes' for a different show.  To that end, please change the "Vote" menu as follows:

First Vote: [existing dropdown]
First Show: [Dropdown: Rhinestone Review; Friday Late; Main Event; Sunday Showcase]

Second Vote: [existing dropdown]
Second Show: [Dropdown: Rhinestone Review; Friday Late; Main Event; Sunday Showcase]

That way, someone can express two opinions.

**Comment by jonkiparsky** [comment]
Also: modify vote choices as follows:
eliminated "Undecided", change "Author" to "Abstain"

**Comment by jonkiparsky** [comment]
Data should be shown in reviews column. (second and third line of each review)

Show to Scratch for approval

**Comment by BenignCremator** [comment]
Code reviewed and tested, functionality looks good.  Approved and merged, so closing ticket.
