### ISSUE TITLE
"Special" menu not showing up

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1111]
I used /admin to add user mspanu to a bunch of privileged groups (schedule mavens, volunteer reviewer and coordinator, etc.) and I also made her "staff".  The Special Menu doesn't show up... we created a stage persona in case that somehow was an issue but no luck.

**Comment by bethlakshmi** [comment]
Um... I don't know if this is a timing thing, but when I hijack the mspanu account, I see the special menu.
Stage persona should have absolutely no effect here.

**Comment by burlexpo** [comment]
Yup.  I do too.  It just took more than an hour for the privileges to show up.
