### ISSUE TITLE
Act Review Display is messed up

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1121]
On Chrome on a laptop, the "Detailed Reviews" section covers the rightmost column (the 5 score) of the Review Information section
![screenshot 2017-09-05 16 16 03](https://user-images.githubusercontent.com/5369404/30081563-acc2c400-9255-11e7-9cad-c5f633a2c96e.png)

**Comment by bethlakshmi** [comment]
fixing w/in #1113 since I haven't pulled it yet.

**Comment by bethlakshmi** [comment]
updated it on the test site - see what you think.  

At it's smooshiest, it's ugly but useable (ie, it's better than it was, at a normal desktop size it's actually attractive).
