### ISSUE TITLE
Rejigger User Privs for Manage Users page

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#1143]
The current page

http://www.burlesque-expo.com/profile/manage

Has the following permissions:

- 'Registrar' - can Update and Delete
- 'Registrar', 'Volunteer Coordinator', Act Coordinator', 'Conference Coordinator', 'Vendor Coordinator', 'Ticketing - Admin' - can get to the page and view profiles

So, essentially, Registrar has Read/Write, and the other roles listed above have Read Only

If you want a change here, give me the new rules and reassign to me.

**Comment by burlexpo** [comment]
@bethlakshmi pretty much any staff lead should have "read" privileges.  We want to make it easy for people who have to chase people (volunteers, performers, etc.) to be able to get the info to chase them.

**Comment by bethlakshmi** [comment]
So... do you want me to make it something like:
- if you are staff lead on anything in a current or upcoming conference.
- if you are any of our privileged roles

Typically we haven't done privileges based on who is a "staff lead" for an event, but I've run up against that useful sounding piece of logic often enough that I don't mind writing it up.

**Comment by bethlakshmi** [comment]
This seems like a good, fast thing to pickup pre-expo, so I'm running at it.
Also, having a "is this guy a staff lead check" makes a good stepping stone to letting staff leads do other things like contact users.
