### ISSUE TITLE
Build better Event scheduling workflows

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#1147]
OK, this is a big ticket, and I may carve out subtickets to work on.  This is meant to cover the complete design.

# Step 1:  Pick an Event Type

1. User selects Special -> Schedule -> Make an Event
2. User gets to a Pick Event Type screen, here's the choices (click picture to see it the right way up):

![step 1 - pick event type](https://user-images.githubusercontent.com/4542707/31498622-79d7d3da-af30-11e7-910d-12c0905ee6ef.JPG)

By default, they get the nearest, upcoming conference.  But they can pick other conferences in case we have two open conferences (like a Mini Event).

They click "Next" and the screen moves to the next step, which varies by Event Type.  
They can always return to here by clicking Back from previous screens.

# Start setting up Event
This varies per event type, so each section is a different type (or collection of types, there are common patterns).

## Step 2 - Create Volunteer Opportunity - Pick a Purpose

This may be the hardest one... 

![2ead4fd4-e94d-4f6a-96b0-f8d589f10a1a](https://user-images.githubusercontent.com/4542707/31499242-3d6deafe-af32-11e7-8bf8-e77ca7ae0a67.JPG)

The user gets a bunch of likely candidates for WHY they want to make a volunteer opportunity.  The options are culled from the configuration of events within the selected conference in step 1.  The options are a radio button of:

- Staff Areas - shows Title (? and staff lead???)
    - example: Registration
- Shows - shows Title and Date, Time
    - example:  The Bordello, Feb 2, 10:00 PM
- Special Events - same as Shows 
    - example:  Mina's Tea Party, Feb 4, 3:00 PM

The radio button spans all options.
There is a "Make New" button near the header for EACH AREA (picture is not acccurate) - clicking this button opens a modal on top of this working area that lets the user specify a new Staff Area, Show or Special Event.  That process is the same as if they had gotten here from step 1.

The user picks one and clicks "Next", clicking "Back" returns to step 1.

### Step 2.1 - Create Volunteer Opportunity - Set up opportunity

The user can add a volunteer opportunity to the purpose they have selected.  @burlexpo  - here is where I'm stuck.  I believe this looks like this:

http://www.burlesque-expo.com/scheduling/edit/Show/811/3712

With the difference that I would NOT have editable areas at the top of the page, the only editable stuff would be the Volunteer Management Section. When there are volunteer opportunities already created, those opportunities show up as a list in the Volunteer Management section.

The only think I could think to do here to make it better is to also show (w. static text), how many volunteers are currently assigned.

### Step 2.2 - Create Volunteer Opportunity - Set up staffing

When the user clicks on the "Staff" button on Step 2.1, they get a list of the volunteers currently assigned.  That would look like the bottom half of this page:

http://www.burlesque-expo.com/scheduling/edit/GenericEvent/816/3728

I'd assume we want to eliminate all the event editing stuff at the top, because you could do most of it in Step 2.1.

@burlexpo - on this one, too, I need guidance on how to make the staff selection better.

**Comment by burlexpo** [comment]
I am happy to guide you, but I don't think we can do this in writing.  I've read through everything and looked at the links and I just don't understand what you're asking me.

**Comment by bethlakshmi** [comment]
@burlexpo - I was able to move forward on Class creation so I did.  Check out:

http://gbeadmin.webfactional.com/scheduler/manage

See the new button - Create Class

Press it.

The only feature that works right now is " Conference Class" - the rest are placeholders that I'll remove before finalizing the code.  Also, I will change "Create Class" into "Create" when it does more than create classes.

I look forward to feedback...

To get you going, I fake accepted some classes on test, so there would be something to play with.

**Comment by bethlakshmi** [comment]
I'm letting the show interest stuff #1095 percolate for a few days before testing.  And I'll pull in the various fixes later this weekend.  Taking a break from interests, I'm returning to this to develop another workflow.

**Comment by bethlakshmi** [comment]
All classes now work on production = conference, drop in, master.

**Comment by bethlakshmi** [comment]
Still not done!  Until I get a new priority from @burlexpo, I'm going back in to work on Special Events and Shows, as a natural outgrowth of the Master Class & Drop In class - since all of these get tickets. 

The extra effort will be folding in volunteer position creation as a follow on step for Shows and Special events.

**Comment by bethlakshmi** [comment]
There is only one left!  (ah ha ha ha ha ha ha !!!)

Rehearsal slots.
