### ISSUE TITLE
Clicking "Act Tech Info" in automatic email doesn't work

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1152]
I wanted to test the auto emails, so I created an act (http://www.burlesque-expo.com/act/review/1041), used /admin to mark it as _submitted_ , and fired it off.  Good news, I got the email.  Bad news, when I clicked the "act tech info" link, I got re-directed to an error page.  Is this because the act wasn't created through the normal means? Or something else?

**Comment by bethlakshmi** [comment]
Found the problem.  The code I used to generate that link is faulty.  Interesting, as I'm not sure how old this function really is.... I can't remember messing w. this part for a long time.  :(

Found the fix and tested locally.  Dotting i's and crossing t's.

Do you need this as a hot patch or can it wait for a batch update... say next weekend?

**Comment by burlexpo** [comment]
It can wait until the weekend.
