### ISSUE TITLE
awkward URL in Volunteer Submission notices

### ISSUE THREAD

**Issue by eclecticmagpie** [bethlakshmi/GBE2#1166]
The email contains the URL: "www.burlesque-expo.com/volunteer/review", which is not automatically displayed on some browsers. (I am using Chrome Version 61.0.3163.100 (Official Build) (64-bit) on MacOSX 10.10.5).  Instead, the browser invokes google search for that phrase.

Using  "http://www.burlesque-expo.com/volunteer/review" would probably eliminate the issue.

**Comment by eclecticmagpie** [comment]
Today, I had no problem -- it still appeared to be kicking me into Google Search, but it found the site and redirected.  I don't know if that's because there was web congestion the other day, or something else that affected the operation.  I still think it would be a good idea to change the URL, but it's even lower priority than before!

**Comment by bethlakshmi** [comment]
We ended up totally changing volunteer applications - so hopefully this weird email is deprecated.
