### ISSUE TITLE
Volunteer events should default to "max volunteers" = 1

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#1188]
Big usability enhancement.  We never have a volunteer opportunity that doesn't want at least one volunteer. :)

@burlexpo  - I did some research here - it turns out that I think we default to the value of # volunteers that is set on the Staff Area.  For example, registration (the staff area) has max volunteers of 2.  And the blank volunteer form has a value of 2.  There's a Build/Strike area, and the value is 12, and the volunteer opportunities there default to 12.

Do you want me to fix it always to 1?

And, I can't reproduce the bug you were telling about.

**Comment by burlexpo** [comment]
Awesome. Thanks. 

--
Team BurlExpo
www.Burlesque-Expo.com
#BurlExpo

**Comment by bethlakshmi** [comment]
OK to close this?
