### ISSUE TITLE
Course Evaluations

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1205]
To rate a class you need to be logged in.
You need to have a Whole Shebang or Scholar Pass
You need to not have already submitted a review for that class.  (Q: Do we allow people to edit their reviews?)
----------------
Review page consists of
Name of class, teacher, and class description
Ratings as follows:
![image](https://user-images.githubusercontent.com/5369404/34428993-76672818-ec20-11e7-8946-441bf29379f6.png)

**Comment by bethlakshmi** [comment]
This made it up on the live site in prototype form.  I just finished the automated tests and thankfully very minor bug fixes that make this a stable peice of code.

In a few days, I'll review and pull it to master.  

Until then, the fact that this is on live, but from a branch blocks other code updates to live.
