### ISSUE TITLE
Investigate Divio Hosting

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#1261]
This may want to be a separate issue, but I may have found a better host --
https://www.divio.com/plans/

Roughly $4/month includes 

- Test server included
- Postgres database
- Daily backups (7 scheduled and 3 manual with 7 days retention) 
- Content Delivery Network (CDN) for your media files
- 2 domains (excludes registration)
- Divio developer tools including Divio Desktop and Divio CLI
- 10 GB object storage and 1 TB transfer per month
- SSL certificate

This might be _much_ faster than you trying to do the upgrades manually...

_Originally posted by @burlexpo in https://github.com/bethlakshmi/GBE2/issues/1245#issuecomment-522323753_

**Comment by bethlakshmi** [comment]
So, fun fact, after a not small amount of digging on this:
- I tried playing with Divio Cloud in 2016 - they are the people that make Django CMS, so my assumption was that using them for hosting may simplify our lives.
- back then (found the email w them) they were both stupid expensive (~$100/mo) and didn't have shell access - which made this a big no go.

Now... I'm investigating again.  So far:
- got a test server set up w. only Django CMS (current version, Python 3).
- I'm trying to get a parallelish feature set going.

https://burlesque-expocom-stage.us.aldryn.io/en/login/?next=%2F

@burlexpo - you have a login - mailed under separate cover.

So far, I know I got the bootstrap plugin working... and that means I know how to use their supported plugins - hot diggety!

**Comment by bethlakshmi** [comment]
Early things I should focus on to avoid wasting time:
- there's an SSH access thing -- but they say I need keys.  OK, how do I get keys?
- there seems to be a way to link in our git hub to this thing... cool beans,... um... how?  And once done, how do I publish updates? 
- can the - erm - unusual - way I wired our GBE code to the Django CMS system be fixed to do the same thing but better with this system?
- can email of information work?  do I need to change any thing there?  (they do integrate w. Mail Chimp...)
- How do I port our GBE data?  Probably clearer when I set up a DB.
- What is the bottom line on cost.. they charge upwards of $4 based on:

 -- storage -- would we need to scrub our music files?  How much do we consume???
 -- bandwidth - we run real slow for a long time... but we get real hot for a week.  But I have no idea how hot... can I get graphs out of this thing?  What happens when we hit our peak?  Do we start DOSing.  And... am I paying at the CDN level of traffic or the origin?  So much of our content is static, we should be able to leverage the CDN for that... but how does CDN caching factor into cost... I really want a Divio person to talk to on this...
 -- RAM - that's where Web Factional really smacks us around - we keep hosing our RAM allocation.  I really want to know 1 of 2 things (2 of 2 would be better) - (A) I can get a graph over time of our RAM allocation so I can investigate fixing our problems (B) that the leak is actually Django CMS and they actually fixed it (or they own it and it's not my problem).  Another requirement - what do they do when our RAM use exceeds their boundaries?

**Comment by bethlakshmi** [comment]
for later - need tech detox now:  http://support.divio.com/en/articles/17880-set-up-your-ssh-keys

But SSH keys go from my computer to the Divio cloud.  There appears to be no shell access.

Having consulted with 100% of the web dev team, I decided we don't care that much.  But... this is then only feasible if I can integrate the developer environment with our code.  AND if I have direct access to the SQL database.

**Comment by bethlakshmi** [comment]
I got a bit farther - 

https://github.com/bethlakshmi/gbe-divio-cloud

and 

https://custom-burl-expo-stage.us.aldryn.io/

are now connected.  It lets me edit the templates, and push code back and forth from my desktop to the server, through git.  That's some of the basics.

Things that don't work (but I'm trying):
- SSH access to the servers (conversation is ongoing with support)
- the menus - I heavily customized the drop down menus and my customizations for pull down behavior and the pretty fonts are both working in my local, but not in the deployed system.  Also talking to ticket folks, but they are not too helpful yet.
- regular user login - I stubbed it out as a first step, so if it works, it's ugly.
- Link buttons - actually linking them to internal pages is broken, it needs a django component that I can't figure out how to integrate. THIS COULD BE A BLOCKER - we have all kinds of custom libraries, if this can't work, I can't use this system.  It claims it can work... ticket filed.

I'm starting to get visual elements in the Django CMS system working:
- the images work
- Bootstrap is installed, but only quasi working (link button issue)
- Styles are installed, not necessarily configured.
- Can't tell why I can't embed links in text, but I can't.
- haven't tried/found column settings, or cascades (rotating images)
- googlemaps installed, may need to be configured.

For our custom code - I really haven't begun trying, this is django 1.11 - and we're still behind the times.  I am bracing myself for trying to integrate and upgrade our code directly into this system... what the hell...

**Comment by bethlakshmi** [comment]
Fun Fact:  Staging server requires user to be logged in.  Live Server doesn't - it can be no-login-viewable.  Makes some sense, but it means that "not logged in" user experience testing is either on my local or live.  That's a tad icky, because there are some JS loading issues on the Divio cloud servers that don't exist on my local.

**Comment by bethlakshmi** [comment]
So that @burlexpo doesn't feel hopeless and alone.  Although progress is SLOW, I'm getting there by baby steps (pun intended).

- https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7 - is another repo that I'm working in.  Scratch - I just invited you.  
   - the reason is - I'm still pretty crude in figuring out how to integrate and use github with Divio Cloud.  While I mess around, I really don't want to make a giant mess in THIS repo, particularly when setting up new repos is free and takes me maybe 8 minutes.  This is repository number 3 - which proves my point.
  - also - I suspect the structure of how we integrate is different *enough* that maybe a new source for our code is warranted.  Can always port the code over here if we feel otherwise later.

- The https://burlesque-expo-stage.us.aldryn.io/about-us/main/ is subtly but importantly better:
     - notice that our custom coloration and branding largely works.  I still have a problem with 20th Century Poster, but otherwise, most of it appears to be a matter of me spending a day and screwing with it.
      - ALSO - the javascript works - both in our menus (it makes pull down menus appear) but also in our use of Bootstrap 4.  **DON'T USE Bootstrap 3.  It doesn't work.** 

Now... I'm ready to start separating the known from the unknown and work towards resolution of the unknown:

RESEARCH PROJECTS:
The time estimate on these is "I have no earthly idea".  Some may be a conjecture of "small" or "large" but only w. respect to each other:

- **Nail down icon problem and font loading problem** - I have 1 recommendation that may work for "why can't I use icons that Django CMS gave me?", but the 20th century poster font problem remains a mystery.  
- **First database migration** - we ain't done nothing with out this.  It looks very clearly documented.
- **First data port** - much more problematic.  My understanding of how I can get to the database is limited.  BIG to-do, needs "first database migration".  The "migration" is to make our data structures show up in Divio's servers.  The "port" is moving our data from WebFactional to Divio.
- **Upgrade and integrate packages:**  gbe, scheduling, ticketing.
- **Figure out how to email people with email package** - linking to an email server is just never pretty
- **Figure out if/how we can use our extended login system** - years ago, I overwrote the defaults to let users login with either a username OR email.  We may want to re-investigate Django CMS's capabilities to see if we actually want to keep this.
- **Figure out Audio uploads** - always a big space consumer.  Chances are I can't use the compression stuff we wrote on Web Factional.  
- **Figure out cron stuff** - we have timed syncs with WebFactional - I haven't seen if timed jobs are available.  There's a hacky answer - do them somewhere else and trigger them via API call (yuck).
- **Integrate w Brown Paper Tickets** - really probably not that hard, so long as I can make outgoing calls.
- **Make recommendation on cost** - I suspect we are NOT the $4 a month package.  We are probably NOT > the $20/month package, and the speed is a hell of a lot better so far.  So mostly it's figuring out what we need and paying for it.  I'll know more based on the above tasks.






DEVELOPMENT PROJECTS:
This is work that seems quite doable, and estimate-able - it just needs to get done before transition....  Thus, there's an estimate on all this:

- **Finish making CSS nice - 1-2 days** - @burlexpo  - if you want a different look/feel right off the bat, give me some specs.  In almost any format will work - mock it up in anything you like and I will spend time making it so, instead of slavishly porting our CSS.  Same cost either way.   We can talk about when I need it from you.  Not in the next 2 weeks, for sure.
- **Port our static info 1-2 days** - our pictures, our non-dynamic pages - chances are good that anything Scratch made, I will manually re-make. 
- **Figure out if we are doing a total port to Bootstrap 4 - 2-5 days** - The thing that works right now is Bootstrap 4.  So far, I've been upgrading our Bootstrap 3 code to Bootstrap 4.  It's onerous, but not making my head explode.  It's probably nice to do that, as the world moves forward.  @burlexpo  - you can influence this if you care.  If you care, google bootstrap 4 vs. bootstrap 3.  This is mostly about the functionality in the UI.  Usually by moving with the times, we can stay closer to what people think a nice website looks like.


ISSUES TO BE FIXED:
There's no research here, we just need to figure out how to handle as a business:

- **password migration won't happen** - I can guarantee - me figuring out how to migrate user passwords is a no-go.  It's risky at the best of times, in this system, they've taken my hands out of their server enough that I know I can't get to the stuff that would let me migrate user passwords.  Given that it's been years, we may want to figure out a migration plan, and have me address it w. a bit of code.  I have ideas.  It needs a meeting.

Looking at all this, I'm debating making tickets for this stuff.  I'll talk to @burlexpo  and maybe move this very long format into tickets in the other repository.

**Comment by burlexpo** [comment]
https://codeburst.io/intro-to-google-fonts-for-web-developers-5559b63807d3
--
Team BurlExpo
www.Burlesque-Expo.com
#BurlExpo


-=Scratch
www.BostonBabydolls.net
(617)869-2000

**Comment by bethlakshmi** [comment]
So... these (it turns out) are NOT google fonts.  They are from other
sources:

https://fonts.google.com/?query=twentieth

If these were Google fonts, the website you pointed me to would be great
(so if you want any of those other fonts.... probably not too hard..)

Looks like, if I'm trying to include it, I need to pay ~$20 for it:

https://www.fonts.com/font/pelavin-fonts/twentieth-century?QueryFontType=Web&src=GoogleWebFonts

This site explictly says "web font".

At this point, I've spent enough time chasing it, that if we go with Divio,
I suggest I buy it for $20 and you buy me dinner for $20 sometime. :)

**Comment by bethlakshmi** [comment]
Close - moved that to another repo
