### ISSUE TITLE
Run on Text Description on Vendor Display

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#140]
I created a vendor with a very long 'description of goods and services'.  If you take a look at http://gbeadmin.webfactional.com/deploy_stack/vendors/fashion_faire/ you can see the results.

Solution: put a hard limit on the number of characters that can be entered into the text box when the vendor bid is submitted.  I suggest 250 characters.

**Comment by burlexpo** [comment]
I think we have a functional solution in place and this can be closed.  Can it?

**Comment by jonkiparsky** [comment]
No, solution is not in place. Adding it now.
