### ISSUE TITLE
Stop the same person from creating two act bids with the same name.

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#150]
Howdy,

In order to figure out which performers had created acts but not submitted them, I went to 

http://gbeadmin.webfactional.com/admin/gbe/act/

and sorted the page by the "Submitted" column, which enabled me to easily see all the unsubmitted acts.  I took a quick look at which unsubmitted acts looked completed and wrote them all down.  Then I compared the list of completed but unsubmitted acts with the list of ticketing transactions (http://gbeadmin.webfactional.com/admin/ticketing/transaction/) and came up with a list of people who had paid application fees AND had completed acts which were listed as "unsubmitted".

I sent email to all of these people (about 9), saying that they had yet to 'pull the trigger' and submit their act, which was fine if they were still editing it, but that they had paid their application fee and should remember to submit the act before Halloween. 

I got email back from one (Vivi Noir) of them almost immediately, saying that she *had* submitted her act -- and, in fact that the act appeared as submitted on her personal pane.  

I went back to http://gbeadmin.webfactional.com/admin/gbe/act/ and this time sorted by Performer and -- sure enough -- Vivi has two identical acts, one submitted (and therefore paid) and one not.  A quick check of some of the others shows at least one other performer (Sara Dipity) in the same situation.

Any thoughts?

**Comment by jonkiparsky** [comment]
I would like to close this issue. To do this, we need two decisions. 
First, a decision on cleanup of the double-submitted acts.  If we want that, I can do this in a few seconds. If not, no bother for me. @burlexpo, @bethlakshmi - do we want these extra bids deleted? 

Second, do we want to try to block double-submission? If so, we should write up that case as an enhancement. I think we can do this, and it's a good idea for next year. Other opinions?

**Comment by burlexpo** [comment]
First, *language*.  We don't have any "double-submitted" acts.  "Submitted" means "created, paid, and submitted for approval".  The problem described here might be "double-*created* acts" or something similar.

My only fear with cleaning up data this close to the event is that we're inadvertently going to screw something up.  Besides that paranoia, there's no reason to keep other acts from people who have successfully submitted acts.  I **would** like to keep data from people who created act bids but did not submit them for whatever reason.  That's useful information.

Next, yes, it'd be great next year to block the same person from creating two act bids with the same name.

**Comment by burlexpo** [comment]
The assignment here is "stop the same person from creating two act bids with the same name".
I believe this issue is still open, but can wait until March+

**Comment by jonkiparsky** [comment]
Definition of done: A user is prevented from creating a new act bid (draft or submission) which has a name that they have already used in this conference. Display a warning (bootstrap, class = alert or whatever class makes it red) including a link to the conflicting act. 
* User remains on the bid edit page (with the data they entered, ie, treat it like a form error)
* Names used in previous conferences are okay, no error should be displayed.

**Comment by bethlakshmi** [comment]
Notes on scope:
- affects and needs testing for both edit and submit - these are two different views and two separate tests
- scope does not require an alert window - it's in base.tmpl
- tests/functions/gbe_functions.py has a nice alert test
