### ISSUE TITLE
CSS: Mouseover flyouts go off the edge of the page if the screen gets narrow

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#172]
Performer bios require a 1250px frame to display correctly - otherwise, the images on the right go off the edge.

**Comment by bethlakshmi** [comment]
Idea for post expo - how about something like this?

http://getbootstrap.com/javascript/#popovers-examples

Idea:
- we design a little icon for a button (like [these](https://www.google.com/search?q=more+details+icon&ie=utf-8&oe=utf-8))
- we put all the act/vendor data into the popover 
- the popovers let you pick "right", "top", "left", "bottom" to anchor.  We use them as follows:
   - Right most column - pop-over comes up on left
   - middle column - right or below
   - left most column - comes up on right

Then it's always near the image of the performer, and not weird anymore.

OR - we could make the performer image the 'button' too, and do the same thing.

**Comment by bethlakshmi** [comment]
will be deprecated when I finish the boostrap ticket for vendors #1055
