### ISSUE TITLE
Check overbook on  scheduling

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#180]
Jon, I bet this is on your list, but here's a gratifying ticket to close when you are done. :)

Any time a person is attached to a schedule item that is:
- scheduled
- rescheduled

Then we need business logic to do an overbooking check.  If the person is overbooked (start + duration of current event overlaps with start + duration of any time the person is a Worker Item or part of an Act Item) then there is a warning to the scheduler.

Just a warning - not an an actual halt.

**Comment by bethlakshmi** [comment]
Reference, this is specifically for the page:

http://gbe2016test.gbeadmin.webfactional.com/scheduler/edit/GenericEvent/<id>

Where when you select a given volunteer and give them the job, there is no warning at all that they are overbooked.

**Comment by burlexpo** [comment]
Is this still an open ticket? Or was this tackled?

**Comment by jonkiparsky** [comment]
I don't see a PR for it.

**Comment by burlexpo** [comment]
I may not understand what problem this is addressing.  I believe the 
currently when we try to schedule someone for a time they are already 
scheduled we get a warning.  Isn't that the functionality described here?

**Comment by jonkiparsky** [comment]
I have no idea if that is happening or not. All I know is, this is an open ticket and there's no pull request addressing the issue. If this work does not need to be done, I'm happy to not do it.

**Comment by burlexpo** [comment]
Since @bethlakshmi created the ticket, I was asking her opinion if she thought it could be closed.  I *believe* the problem is solved, but since I didn't write the ticket, I want to make sure that my interpretation is correct.

**Comment by bethlakshmi** [comment]
Clarifying the logic needed to recreate the gap.

If you go to Schedule Events -> any type of event -> pick an event with volunteer opportunities

Manage the opportunities
Add a volunteer to the opportunity

if there is a conflict, you won't get any sort of a warning about that.

Similarly, if you have volunteers booked for the opportunity.  Or teachers booked for a class.  Or any individual booked for anything - if you move the start time of the thing, you don't get a warning that the person is overbooked if there is a conflict.  

The assign volunteers thread for Review volunteers -> Assign has the conflict checking.  The function exists and can be reused it's just never been linked in.

**Comment by BenignCremator** [comment]
Functional testing does work.  However, you need to either wait for the cache to time out and clear, or switch users to drop the cache on the floor.  Also, the pop-up warning could be larger (it is small enough to easily miss) and last longer (you can read it if you catch it immediately when it pops up).  Neither are blockers, and the functionality is there.  Code review looked good, nice that codebase is decreasing.  Pytests mostly worked, once I set the foreignkey constraints to not be checked.  Only 14 errors in non-relevant code, mostly dir not existing at /media/uploads (as in, not part of this issue).  Approving.
