### ISSUE TITLE
Still getting stack dumps on production?

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#187]
I just fixed an issue Mina found in password reset:

https://github.com/bethlakshmi/GBE2/commit/a97f377b2a5a0314562d5ab37fa1ac6e4bcd4eb8#diff-df18ec3f3f3e392cf167813732f56b04

What I saw was that while password reset was broken, we got a stack dump and code trace when it was broken...

Is that normal for a site in default mode?

Not sure how to retest, since obviously I wanted to fix the problem...  probably need to retest on a different stack.

**Comment by burlexpo** [comment]
I believe this can be closed.  @jonkiparsky ?
