### ISSUE TITLE
Didn't alphabetize events by title/name on volunteer bid

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#191]
Jon says it's super fast.

Code is in gbe.views, in the EventCheckBox

CHANGE = Scratch and I just reviewed, he's asking for 
1 - first sort by date/time - I can and will do that with the object query.
2 - secondary sort - name of event.

So I still need list sort help, but for a 2 order sort.

So the results should be:

2/20 - 8AM - Event A
2/20 - 8AM - Event B
2/20 - 9AM - Event A
2/20 - 10AM - Event B

**Comment by burlexpo** [comment]
I think this is rendered moot by the ability to sort stuff by columns.  If I'm wrong (and I may be; I'm not 100% what issue we're fixing here) and "Jon says it's super fast."  If it is, let's do it.
