### ISSUE TITLE
"Teacher" field should only show on scheduling page for Classes

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#198]
Currently you can select a Teacher for any event. Selecting one will not break anything, but the selected person will then be the teacher for, say, the Main Event. This could be annoying. 

This can be fixed, but unless it's urgent I'm going to focus on getting volunteer scheduling in place. If not urgent, deferring until urgent items are taken care of. (like maybe Spring)

**Comment by jonkiparsky** [comment]
Compounding this issue, I've added "moderator" and "panelist", handling them the same way "teacher" is done.

**Comment by burlexpo** [comment]
Where are we on this issue?

**Comment by jonkiparsky** [comment]
Duplicate. Closing in favor of #210
