### ISSUE TITLE
Hotel reminder on homepage breaks formatting

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#202]
Betty and I made a nice 3-column layout for the home page.  I don't know if i was committed, but the new "Welcome" message (the reminder about making a hotel reservation) breaks it.

The version we had created was

Column #1: Welcome message (static text; in this case, reminder to make hotel reservations.  It would be nice if the reminder about hotel reservations appeared *below* the old welcome text instead of replacing it).

Column #2: User's schedule

Column #3: Personal Pane

**Comment by jonkiparsky** [comment]
This seems to be fixed, closing.

**Comment by burlexpo** [comment]
I re-opened this because I'm not seeing hotel reminder text.  What I'm seeing in the first (left-hand) column is: 

*This is your personal homepage. If you're logged in, you'll see all sorts of cool stuff about you on the right-hand side of this page. Things like the status of your submissions (acts and classes), your personal schedule (for classes you're teaching, shows your performing in, or shifts you've volunteered for) and all sorts of other cool stuff.*

Which is fine -- but we want the hotel reminder below it somewhere...

**Comment by jonkiparsky** [comment]
For some reason, that piece didn't come across on the code update. It's there now.
