### ISSUE TITLE
Difference in allocation between teachers and other sorts of workers

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#209]
Teachers are allocated directly to the Event in question, other workers are allocated to a volunteer opportunity which points to the event. (via an EventContainer).

This is likely to cause confusion and code mess in the long run. Does it buy anything we want? If not, should we fix it now or eat the cost of working with it until February and fix it then? 
@bethlakshmi Thoughts?

**Comment by bethlakshmi** [comment]
Teacher-wise, we need:
- to show the teacher, regardless of the type of the Event (Class, or Generic, for example) on the various event lists, calendars and description.  If we change how Teachers are allocated, we need to update code in those places.
- longer term - we'd like to give teachers the abilty to edit parts of their classes (like descriptions) but not all of that... so the connection is useful, but could be arbitrated either way.

The consistency is worth it, but not high on my list right now... marking as enhancement.
