### ISSUE TITLE
Time, Location, etc. wrong on Volunteer Allocation page

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#212]
A Volunteer opportunity created in the Edit view of a show asks for certain information: Title, number of Volunteers Needed, Duration, Day, Time, and Location.

After you click "Allocate Workers" on on a specific opportunity, you're taken to the Edit view of that opportunity. (i.e., http://gbeadmin.webfactional.com/deploy_stack/demo/scheduler/edit/GenericEvent/179)

The Day, Time, Location, Duration, and Max Volunteer fields are all displayed again -- but they are all different from the information displayed on the previous page.

**Comment by jonkiparsky** [comment]
I'm seeing this again, also other issues with locations on scheduled items. Re-opening.
