### ISSUE TITLE
Fix deploy script 

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#220]
Very low priority, I just don't want to loose it.

Jon's made changes to create the local_settings.py stack-specific settings work 

And I've made updates to the wiki just now:
https://github.com/bethlakshmi/GBE2/wiki/Test-Sites-on-GBEADMIN
to reflect some of that plus the changes for static URL

Ideally we should update the depoy script so that it sets up a local settings file and does some of the static-specific stuff automatically.

**Comment by jonkiparsky** [comment]
@BenignCremator I think this is in your wheelhouse? Can we assign it to you? 
(still low priority, but this helps me know which things I don't have to be worrying about)

**Comment by burlexpo** [comment]
What's up with this? Close it? Get rid of it? Assign it to @BenignCremator ?

**Comment by jonkiparsky** [comment]
I think we can close it. We might want to circle back around to this sort of thing, but if it becomes important in the future, we can worry about it then.
