### ISSUE TITLE
Still something wrong with classes

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#223]
I don't know if this was a fail in Betty's code or in @jonkiparsky's recent update, so I'm commenting him into the ticket.

When I am on http://gbeadmin.webfactional.com/admin/gbe/class/195/ and try and change the teacher to Mandy (from me) and then "Save", I get the following error:

IntegrityError at /admin/gbe/class/195/
(1452, 'Cannot add or update a child row: a foreign key constraint fails (`gbetest2`.`gbe_event_owner`, CONSTRAINT `event_id_refs_event_id_ad60618a` FOREIGN KEY (`event_id`) REFERENCES `gbe_event` (`event_id`))')
Request Method:	POST
Request URL:	http://gbeadmin.webfactional.com/admin/gbe/class/195/
Django Version:	1.6.5
Exception Type:	IntegrityError
Exception Value:	
(1452, 'Cannot add or update a child row: a foreign key constraint fails (`gbetest2`.`gbe_event_owner`, CONSTRAINT `event_id_refs_event_id_ad60618a` FOREIGN KEY (`event_id`) REFERENCES `gbe_event` (`event_id`))')
Exception Location:	/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
Python Executable:	/usr/local/bin/python
Python Version:	2.7.8
Python Path:	
['/home/gbeadmin/webapps/gbetest',
 '/home/gbeadmin/webapps/gbetest/expo',
 '/home/gbeadmin/lib/python2.7/psutil-2.1.1-py2.7-linux-x86_64.egg',
 '/home/gbeadmin/lib/python2.7/pip-1.5.6-py2.7.egg',
 '/home/gbeadmin',
 '/home/gbeadmin/lib/python2.7/pytz-2014.4-py2.7.egg',
 '/home/gbeadmin/lib/python2.7',
 '/home/gbeadmin/webapps/gbetest/lib/python2.7',
 '/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/home/gbeadmin/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages/PIL']
Server time:	Sun, 4 Jan 2015 04:38:21 +0000

**Comment by bethlakshmi** [comment]
I believe this is fixed... ?  I can't recreate it, and I think @burlexpo mentioned he was successful last night, and I see that this particular class is now Mandy...

**Comment by burlexpo** [comment]
On 1/9/15 5:08 PM, bethlakshmi wrote:
>
> I believe this is fixed... ? I can't recreate it, and I think 
> @burlexpo <https://github.com/burlexpo> mentioned he was successful 
> last night, and I see that this particular class is now Mandy...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/223#issuecomment-69407469>.
>
Yes, this is fixed.

-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com
