### ISSUE TITLE
Create Act Rehearsal type under GenericEvent

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#225]
Like volunteer, but participants can freely self-schedule as long as number allocated <=max_volunteer

Perhaps this should be handled in the same flow as the act tech info - we show the three tech forms plus checkboxes for the rehearsal slots, they fill the whole thing in at one go.

**Comment by burlexpo** [comment]
I like handling this as part of tech sign up, as long as they're not too entangled with each other. But is to say, as long as the rehearsal sign-up is not part of the text sign-up form, but rather a separate form displayed on the same page. If that makes sense. I can'tThink of a specific business case, but I just have a feeling that people are going to want to be able to access and rearrange their rehearsal schedule after they have submitted their tech info.

The Great Burlesque Exposition #9
February 20-22, 2015
www.Burlesque-Expo.com
#BurlExpo9

**Comment by jonkiparsky** [comment]
Yes, that makes sense. It's pretty much what I'd had in mind, in fact: give people a one-stop shop for this, but keep the different pieces separate.

**Comment by jonkiparsky** [comment]
I believe this is set.
