### ISSUE TITLE
Working with "Groups"

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#227]
Is there a way to see all members of a Group (http://gbeadmin.webfactional.com/admin/auth/group/) or to see how many members are in a given group?  I'd like to be able to double-check that all performers in a given show are assigned to the right group.

**Comment by jonkiparsky** [comment]
It would be pretty easy to produce that as a report, but I don't know of a
good way to do that in the admin.

**Comment by bethlakshmi** [comment]
The auth user screen has already been built out for this...

http://gbeadmin.webfactional.com/admin/auth/user/

I agree with @jonkiparsky  that we'd rather not have to hand create the groups, I think Jon offered to script an update.

But to close the ticket... go to the site above, and look in the sidebar, the groups are shown there, and the group is a filter option.
