### ISSUE TITLE
Deal with errors on complex forms

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#228]
We have at least one place (http://gbeadmin.webfactional.com/deploy_stack/demo/scheduler/edit/GenericEvent/179.... press "Edit/Create" on a row with empty text...) where instead of an error, we throw a 404.  We should be able to provide helpful red text or a warning popup here.  

Worthwhile is to find a solution we can use throughout.

**Comment by jonkiparsky** [comment]
This seems to be fixed, at least in the cited case. Can close?

**Comment by bethlakshmi** [comment]
Yepper... I left open hoping to think of more error cases to test, but I am out of creative ideas now...
