### ISSUE TITLE
Put Act Tech Info/Rehearsal update on the Bid area of the landing page

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#230]
Hey @burlexpo  - if you like this, assign it to @jonkiparsky  or me (@bethlakshmi)

Instead of the special menu....
- if the user is the contact point for an accepted act - show under "Username's Stuff" in the right hand column of the home page - "Reminder!  Submit your Act Details and Choose your Rehearsal!" and then a link to the act tech details page for each act that is accepted.

Reasons I like it:
- it doesn't confuse the use of special menu - which was other wise for truly privileged users
- it means that Scratch doesn't have to make and maintain a group for each show ... that will get old fast.
- it shows up where the user could already see accepted bid info
- it's pretty easy - the info is already available in that area, it's just some more display stuff.

**Comment by burlexpo** [comment]
I love this.  I just came up with the special menu/groups workaround as just that -- a workaround.  If this is a fast solution to implement, please go for it.  I like it for all the reasons you do.

**Comment by jonkiparsky** [comment]
This ticket comes after #235, can be paired with #234 
Jon or Betty take it, inform the other if you pick it up.
