### ISSUE TITLE
Class descriptions run off the edge of the screen

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#232]
If I go to http://gbeadmin.webfactional.com/scheduler/view_list/Class the text runs off the right edge of the screen -- and there's no slider at the bottom which allows me to see the text.

Link to screen capture

https://www.dropbox.com/s/5yctbhsztdekziz/Screenshot%202015-01-15%2015.47.14.png?dl=0

**Comment by jonkiparsky** [comment]
Working on this now.

**Comment by burlexpo** [comment]
Great. Can we get this change pushed up ASAP? This is a pretty big 
problem...

On 1/15/15 8:55 PM, Jon Kiparsky wrote:
>
> Closed #232 <https://github.com/bethlakshmi/GBE2/issues/232> via 
> 4ebf101 
> <https://github.com/bethlakshmi/GBE2/commit/4ebf1018db00e6aa147807578b19d8231fc1054f>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/232#event-219838637>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com

**Comment by jonkiparsky** [comment]
Pushed. Since css is cached, it might not show up immediately - in that
case, you'll have to clear your cache manually. But live is serving the
right css.

**Comment by burlexpo** [comment]
Thanks -- I refreshed my cache and this looks fine.

On 1/15/15 9:06 PM, Jon Kiparsky wrote:
> Pushed. Since css is cached, it might not show up immediately - in that
> case, you'll have to clear your cache manually. But live is serving the
> right css.
>
> On Thu, Jan 15, 2015 at 8:56 PM, Scratch <notifications@github.com> 
> wrote:
>
> > Great. Can we get this change pushed up ASAP? This is a pretty big
> > problem...
> >
> > On 1/15/15 8:55 PM, Jon Kiparsky wrote:
> > >
> > > Closed #232 <https://github.com/bethlakshmi/GBE2/issues/232> via
> > > 4ebf101
> > > <
> > 
> https://github.com/bethlakshmi/GBE2/commit/4ebf1018db00e6aa147807578b19d8231fc1054f
> > >.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bethlakshmi/GBE2/issues/232#event-219838637>.
> > >
> >
> >
> > --
> >
> > 
> ------------------------------------------------------------------------
> > The Great Burlesque Exposition of 2015
> > Feb. 20-22, 2015
> > Cambridge, MA
> > www.Burlesque-Expo.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bethlakshmi/GBE2/issues/232#issuecomment-70197145>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/232#issuecomment-70197964>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com
