### ISSUE TITLE
Purchased tickets not displaying on profiles

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#233]
If someone has bought a ticket, is that information supposed to show up on their personal pane? If not, how hard would that be to get to display?

Commenting in @jonkiparsky for a second opinion.

**Comment by jonkiparsky** [comment]
As I think I said last week, it might be difficult for me since I have absolutely no idea what's in the current ticketing code. If you want an estimate, I'd have to go look at that code and figure it out before I could even start to tell you.

**Comment by burlexpo** [comment]
No worries.  Stay on target.  I'll ask @BethLakshmi to look into it.

On 1/15/15 9:07 PM, Jon Kiparsky wrote:
>
> As I think I said last week, it might be difficult for me since I have 
> absolutely no idea what's in the current ticketing code. If you want 
> an estimate, I'd have to go look at that code and figure it out before 
> I could even start to tell you.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/233#issuecomment-70198040>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com

**Comment by bethlakshmi** [comment]
Checked into current code base.  
https://github.com/bethlakshmi/GBE2/commit/c8e1d50a449e3b64ea3acd07936c08bdfda784cb
Is the checkin
