### ISSUE TITLE
GenericEvents don't interpret HTML

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#239]
(I'm commenting @bethlakshmi into this, since she created the ticketing system which has the functionality I want.  @jonkiparsky - if this isn't an easy fix for you, maybe assign it to Betty?)

If I create a Generic Event using http://gbeadmin.webfactional.com/create_event/GenericEvent and use basic HTML in the "Description" field, when I look at the event after it is created (http://gbeadmin.webfactional.com/scheduler/details/180) the raw HTML is displayed.  

This is not the case (for example) with tickets.  If I go to http://gbeadmin.webfactional.com/ticketing/ticket_item_edit/4 I can use HTML in the description field which displays fine on http://gbeadmin.webfactional.com/ticketing/

**Comment by burlexpo** [comment]
Awesome.  I love this.

On 1/16/15 4:33 PM, Jon Kiparsky wrote:
>
> Closed #239 <https://github.com/bethlakshmi/GBE2/issues/239> via 
> b05ca71 
> <https://github.com/bethlakshmi/GBE2/commit/b05ca710c478de6acb5047d470dd643d130b7e81>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/239#event-220350465>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com

**Comment by bethlakshmi** [comment]
http://gbeadmin.webfactional.com/deploy_stack/betty/scheduler/view_list/Special

Something regressed.

I fixed costume display on the live site, because it looked awful.  But this isn't working as planned or it's broken.

**Comment by jonkiparsky** [comment]
I think I can get this one.
