### ISSUE TITLE
Issues with creating Drop-In Classes

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#240]
(commenting in @jonkiparsky)

I go Special > Schedule Events
I select GenericEvent from the dropdown menu
I'm taken to http://gbeadmin.webfactional.com/scheduler/list/GenericEvent
I click "Create A New Event".  I create a new Drop-in class (called "Test Drop-in Class")

So far, so good.

I go Special > Schedule Events
I select GenericEvent from the dropdown menu
I'm taken to http://gbeadmin.webfactional.com/scheduler/list/GenericEvent
I can see "Test Drop-in Class" on the list of events with options for "Detail" and "Add Session"
If I click "Detail" I see the details view (http://gbeadmin.webfactional.com/scheduler/details/186)
If I click "Add A Session", I can add a session.  I do, scheduling it for noon on Friday in the pool.  I make myself the teacher.
The session appears on http://gbeadmin.webfactional.com/scheduler/list/GenericEvent, just like it should.  There are now two listings for "Test Drop-in Class"; the 'parent' event and the one with a time and location.

So far, so good.

If I click on Detail for the scheduled event, I'm taken to http://gbeadmin.webfactional.com/scheduler/details/186 and it displays as it should.

If I click on Edit on that same line ("Test Drop-in", noon on Friday in Pool), I'm taken to 
http://gbeadmin.webfactional.com/scheduler/edit/GenericEvent/133 and get a 404 error.

This error is blocking the creation of the Drop-in Classes.

**Comment by jonkiparsky** [comment]
I cannot reproduce this. I've repeated your steps to create "Ce n'est pas une classe" http://gbeadmin.webfactional.com/scheduler/edit/GenericEvent/137 and schedule a session. ( @burlexpo is the teacher)
Both edit and detail links work. Also, edit and detail links for "Test Drop-In Class" are working for me. 

Can you confirm that you're still blocked?

**Comment by burlexpo** [comment]
Seems to be working for me now.  I'll check and make sure it's working 
for Mina.

On 1/17/15 1:38 PM, Jon Kiparsky wrote:
>
> I cannot reproduce this. I've repeated your steps to create "Ce n'est 
> pas une classe" 
> http://gbeadmin.webfactional.com/scheduler/edit/GenericEvent/137 and 
> schedule a session. ( @burlexpo <https://github.com/burlexpo> is the 
> teacher)
> Both edit and detail links work. Also, edit and detail links for "Test 
> Drop-In Class" are working for me.
>
> Can you confirm that you're still blocked?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/240#issuecomment-70378514>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com

**Comment by bethlakshmi** [comment]
It was still broken for Mina, I got pulled in on this right after dinner.

Mina's issue is an extremely weird and subtle one having to do with her permissions.

1 - if Mina has only "Schedule Mavens" - which is what her configuration SHOULD be, she can't do edit_event - and I'm fairly sure, it's 404ing out on "validate_perms".  It's definitely a 404

2 - if Mina has all the groups (or all the groups except for Sunday Show Case and Bordello) - she's OK, she can do the thread described in the original entry just fine.  OR - if she's Scratch, she's OK.

3 - if Mina has only 3 groups - Schedule Mavens + two others - same as state #1, 404 error.

I can't tell what the threshold is, but it's definitely in and around groups.

I made us a test user, and gave Mina enough power to keep her account working.

Test user to see this bug:

user: justonegroup
password: test

User has Schedule Mavens and nothing else and sees the original issue.

**Comment by jonkiparsky** [comment]
It's getting the wrong ID. It's hitting the exception after the permissions check. I'm tracking it back now.

**Comment by jonkiparsky** [comment]
(I still don't know why it wasn't giving me a problem earlier, but this is definitely the exception thrown when no item is found, and no Event has that id)

**Comment by jonkiparsky** [comment]
Hm. That event seems to have been deleted, which would explain why I'm getting this error, and also makes testing difficult.

**Comment by jonkiparsky** [comment]
Okay, found it. Pushing the fix to live

**Comment by jonkiparsky** [comment]
Mina should be fine now. Reopen if not.
