### ISSUE TITLE
Location "Crispus Attucks" not displaying

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#241]
When I assign a GenericEvent to a location using the pulldown menu, Crispus Attucks does not appear.

It is listed in both http://gbeadmin.webfactional.com/admin/gbe/room/ and http://gbeadmin.webfactional.com/admin/scheduler/locationitem/ and http://gbeadmin.webfactional.com/admin/scheduler/resourceitem/ 

So, I don't know why it's not available on the drop-down menu.

**Comment by jonkiparsky** [comment]
This is a weird one.

**Comment by burlexpo** [comment]
Yup. 

The Great Burlesque Exposition #9
February 20-22, 2015
www.Burlesque-Expo.com
#BurlExpo9

**Comment by jonkiparsky** [comment]
Fixed.
