### ISSUE TITLE
Class Admin page throws Unicode Error

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#244]
If I go try to go to http://gbeadmin.webfactional.com/admin/gbe/class/ I get a Unicode error.  Looks like there's a bad character in there somewhere...

UnicodeEncodeError at /admin/gbe/class/
'ascii' codec can't encode character u'\u2019' in position 10: ordinal not in range(128)
Request Method:	GET
Request URL:	http://gbeadmin.webfactional.com/admin/gbe/class/
Django Version:	1.6.5
Exception Type:	UnicodeEncodeError
Exception Value:	
'ascii' codec can't encode character u'\u2019' in position 10: ordinal not in range(128)
Exception Location:	/home/gbeadmin/webapps/gbetest/lib/python2.7/django/contrib/admin/util.py in lookup_field, line 250
Python Executable:	/usr/local/bin/python
Python Version:	2.7.8
Python Path:	
['/home/gbeadmin/webapps/gbetest',
 '/home/gbeadmin/webapps/gbetest/expo',
 '/home/gbeadmin/lib/python2.7/psutil-2.1.1-py2.7-linux-x86_64.egg',
 '/home/gbeadmin/lib/python2.7/pip-1.5.6-py2.7.egg',
 '/home/gbeadmin',
 '/home/gbeadmin/lib/python2.7/pytz-2014.4-py2.7.egg',
 '/home/gbeadmin/lib/python2.7',
 '/home/gbeadmin/webapps/gbetest/lib/python2.7',
 '/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/home/gbeadmin/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages/PIL']
Server time:	Mon, 19 Jan 2015 05:09:25 +0000
Unicode error hint

The string that could not be encoded/decoded was: ! You’re on
Error during template rendering

In template /home/gbeadmin/webapps/gbetest/expo/templates/admin/change_list.html, error at line 91
ascii
81	        {% endif %}
82	      {% endblock %}
83	
84	      <form id="changelist-form" action="" method="post"{% if cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %}>{% csrf_token %}
85	      {% if cl.formset %}
86	        <div>{{ cl.formset.management_form }}</div>
87	      {% endif %}
88	
89	      {% block result_list %}
90	          {% if action_form and actions_on_top and cl.full_result_count %}{% admin_actions %}{% endif %}
91	          {% result_list cl %}
92	          {% if action_form and actions_on_bottom and cl.full_result_count %}{% admin_actions %}{% endif %}
93	      {% endblock %}
94	      {% block pagination %}{% pagination cl %}{% endblock %}
95	      </form>
96	    </div>
97	  </div>
98	{% endblock %}
99

**Comment by jonkiparsky** [comment]
Fixed
