### ISSUE TITLE
Schedule items should be deletable

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#245]
A scheduler should be able to delete a schedule item from the lists.  It can be used from the list for the given event type (Generic, Show, Class).  When it goes, it kills off:
- all resource allocations for the scheduler.event
- ?volunteer opportunities for the event?

If we don't kill the volunteer opportunities, they are floating in limbo, and volunteers will appear to be assigned to them.

The counter concern would be that we eliminate a whole lot of work when we do that... but I don't like having too much dead data around - it just leads to confusion.

**Comment by jonkiparsky** [comment]
Issue #157 duplicates this

**Comment by bethlakshmi** [comment]
Both forms of delete are in.
the original event is marked invisible, not actually deleted, everything else gets actually deleted.
