### ISSUE TITLE
Registration Report - badge printing report

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#246]
I will need a report that lets me print badges.
I can do this with a *.csv that I then convert into printable labels using Word and Avery printable labels.

I used 1 Excel spreadsheet as a master list for printing last year.  What I needed on it was:
- ticket name (TicketItem.title - the same thing as is shown on the landing page now) of purchased tickets
   * I don't need any application or vendor fees
- email
- purchase_email
- first name
- last name
- username
- a badge name that I can use for printing - ideally this is: 
    1 - display_name
    2 - if no display_name, First Name & Last Name (format first<space>last)
    3 - if the ticket is for a limbo user - the First Name and Last Name of the purchaser

Because a user can buy multiple tickets, the csv shoudl be per ticket - at the risk of multiplying a user across many rows (I can always omit some)

For reference, see "Reports from 2014" and in it "printable badges.xls"

**Comment by bethlakshmi** [comment]
A great place to put this would be in Special -> User Administration - at the top or bottom of the page
Access control - Registrar.

**Comment by jonkiparsky** [comment]
@bethlakshmi This is a .csv export, right? 
(in that you need to fiddle the data to print as one or another Avery format)

**Comment by bethlakshmi** [comment]
Yep.

**Comment by bethlakshmi** [comment]
I'll take a crack at the data for this one next.

**Comment by bethlakshmi** [comment]
https://github.com/bethlakshmi/GBE2/commit/19313ac359356d292fb6fc85da48c2679677643a
https://github.com/bethlakshmi/GBE2/commit/8118950a4a6ff1b04f777de4760e926d14a2afa9
