### ISSUE TITLE
Room Report - Big List

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#247]
Scandal will need 2 classes by room report.  This is the bigger one.

She needs to know what class is in what room at what time and what it needs.

It's a nicely flat list that shows:

For each room with classes (class Class, not master classes, not dropins) in it, order by room, then by time/date:
- room name
- class name
- class start time
- class end time
- class type
- current teacher (the resource allocation)
- space_needs

**Comment by jonkiparsky** [comment]
csv

**Comment by bethlakshmi** [comment]
Yep.  And only for classes.

**Comment by bethlakshmi** [comment]
I'll try this next... easy to build from the other one.

**Comment by bethlakshmi** [comment]
Data is done... csv TBD

**Comment by burlexpo** [comment]
@bethlakshmi Has this been rendered moot by the reports page? If so, close it.

**Comment by bethlakshmi** [comment]
not entirely - but we could call it done...

/reports/setup/room

Does not show the teacher.

Could close it if we don't care about the specific detail or leave open to put in the teacher as a column.
