### ISSUE TITLE
Room Schedule for public

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#248]
The other thing conference classes and other rooms with lots of events in them will need is - a per room schedule that we can print out and stick on the room.  As such, the nicer it can look, the better.

The layout should be:
- 1 page per room per day 
- for each room/day
   - Header at top of page:  "Schedule for <room name>, <day>, <date" - for example "Schedule for Crispus Attucks, Friday, February 20, 2015"
   - each scheduled event with start time & end time (ie, 12:30 - 1:30 PM)
   - event title
   - teacher or moderator/panelist

Available to scheduling mavens
Should be able to either:
- get a list of rooms and select which one you want to get the listing for
- get the list of all rooms

If the page break is a big pain, it would be OK to have this in a format where it was easy to add a page break by pasting into work - for example, separate HTML tables for each room/day are much easier to insert a page break into.

**Comment by bethlakshmi** [comment]
pick a room, or *all* rooms.

**Comment by jonkiparsky** [comment]
PDF

**Comment by bethlakshmi** [comment]
Working on data for this one, and an HTML or CSS dump to verify that it's working... but a PDF would be nicer.

**Comment by bethlakshmi** [comment]
Data is done...

**Comment by bethlakshmi** [comment]
Done enough... 
https://github.com/bethlakshmi/GBE2/commit/59f9146c7fadb7ac12376e7d50ebe57d9a0632d4
