### ISSUE TITLE
Personal Schedule report

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#249]
I like to be able to give each guest a hardcopy schedule.  Preferably with as little screwing around in Word as possible, but if I have to insert page breaks for printable pages for each user... I will be OK with that.

Examples from previous years are here:
https://github.com/bethlakshmi/GBE2/tree/master/Reports%20from%202014

AttendeeSchedule 2013 and 2014

Important parts of layout:
- header = display_name for person getting schedule - see #246 for badge printing name logic... same deal here, except you can expect that ALL users have a GBE profile.
- same logic as the personal schedules on the landing page
- for each commitment - start - end time (11:30 AM - 12:30 PM), schedule item title, location for schedule item, role
 - if this is a volunteer opportunity, also include - title and type of volunteer opportunity

?? Did we want the Notes to be displayable?  If so, they could show up here...

NOTE:  if this is a class, it's all one thing, with teacher assigned directly to the class.  But if this is a volunteer opportunity, I want to show BOTH the parent event's title, AND the nature of the opportunity (it's title) and start time/end time are for the volunteer opportunity, not the overall event.

**Comment by bethlakshmi** [comment]
For each user, pretty layout.

**Comment by jonkiparsky** [comment]
PDF, one per page

**Comment by bethlakshmi** [comment]
Done enough for now... 
https://github.com/bethlakshmi/GBE2/commit/32306087d5697d7b15a7072d54458d088d35c2bc
https://github.com/bethlakshmi/GBE2/commit/c8735d7d12bed54d5489cc36f2687a218f74b171
