### ISSUE TITLE
Make it easy to stuff envelopes and give ribbons.

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#251]
I want to make it easy to do our stuff that we give to nifty people.

I want a report that says:
- person's badge name
- whether or not they are a teacher (teaching a class, drop in class or master class)
- whether or not they are a performer (in an act that is in a show)
- whether or not they are a volunteer (in a volunteer opportunity)
- whether or not they are super spiffy - teaching a master class

HTML is fine, PDF or Excel if it's easy.  
no Key

**Comment by jonkiparsky** [comment]
Taking this one so that I have data to play with for pdf creation

**Comment by bethlakshmi** [comment]
Done.  https://github.com/bethlakshmi/GBE2/commit/578a4de4b5a90c3866628eea507962d3a78dbfff
