### ISSUE TITLE
Creating an "Event" throws an error

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#252]
I think we've covered this, but I want to make sure...

If I go to http://gbeadmin.webfactional.com/scheduler/list, select "Event" from the dropdown menu (*not* "GenericEvent"), and hit submit I get

AttributeError at /scheduler/list
'Event' object has no attribute 'schedule_ready'
Request Method:	POST
Request URL:	http://gbeadmin.webfactional.com/scheduler/list
Django Version:	1.6.5
Exception Type:	AttributeError
Exception Value:	
'Event' object has no attribute 'schedule_ready'
Exception Location:	/home/gbeadmin/webapps/gbetest/expo/scheduler/views.py in get_events_display_info, line 75
Python Executable:	/usr/local/bin/python
Python Version:	2.7.8
Python Path:	
['/home/gbeadmin/webapps/gbetest',
 '/home/gbeadmin/webapps/gbetest/expo',
 '/home/gbeadmin/lib/python2.7/psutil-2.1.1-py2.7-linux-x86_64.egg',
 '/home/gbeadmin/lib/python2.7/pip-1.5.6-py2.7.egg',
 '/home/gbeadmin',
 '/home/gbeadmin/lib/python2.7/pytz-2014.4-py2.7.egg',
 '/home/gbeadmin/lib/python2.7',
 '/home/gbeadmin/webapps/gbetest/lib/python2.7',
 '/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/home/gbeadmin/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages/PIL']
Server time:	Wed, 21 Jan 2015 02:43:38 +0000

**Comment by jonkiparsky** [comment]
You should not be able to select "Event" from the dropdown. 
If you can, that's an error. 
(I think this was produced by a data error, which has been scrubbed)
