### ISSUE TITLE
Add "duplicate" to 'Staff Area' events

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#253]
In a discussion of how to create events that are not attached to a show, @jonkiparsky said:

"Yes. I created the "Staff Area" type for Generic Events to serve this purpose. Create one of those, doesn't matter what the duration is, and schedule it (doesn't matter what the start time or location are - this is a pretty abstract sort of event). 

Once you've scheduled it, you can attach volunteer opps. 

Looking at this, I realize that we haven't given you any way to duplicate volunteer opportunities  like "Reg Desk Shift" ("add session" won't attach it to the same parent event). Let me take a quick look and see if I can fix that."

**Comment by jonkiparsky** [comment]
@burlexpo I've added a "duplicate opportunity" button to the volunteer management form. This will create  a copy of the volunteer opportunity. As a bonus feature, you can select a new date and time, and hit "duplicate" - this will create a new copy with the new date and time (the old one will not be changed).

**Comment by jonkiparsky** [comment]
This is up on demo now.

**Comment by burlexpo** [comment]
I'll try and test it tomorrow (Saturday).

**Comment by burlexpo** [comment]
@jonkiparsky I'm not seeing the "duplicate opportunity" button.

I created a GenericEvent
I created a StaffArea ("Weasel Stomping")

but when I go here -- http://gbeadmin.webfactional.com/deploy_stack/demo/scheduler/edit/GenericEvent/286 -- I don't see any button.  Am I doing something wrong?

**Comment by jonkiparsky** [comment]
You want to be at the show edit page. It's in the manage allocations
section. So you create the staff area, say "Registration", and then you
create an opportunity, and then you duplicate that from the same place
where you created it.

.../scheduler/edit/Show/138

sent from my handy. typos are just part of the fun.
