### ISSUE TITLE
9 - Add a banner rotator

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#255]
Find a library, establish that it works.  Write the snippet to drop it in via DjangoCMS.

Add in https://pypi.python.org/pypi/django-ad-rotator/0.1 or something like it so we can easily display banner ads on pages.

**Comment by burlexpo** [comment]
May also be resolved with the new CMS -- remains to be seen.

**Comment by burlexpo** [comment]
I assigned this to @jonkiparsky in case you were looking for something new to work on.

**Comment by burlexpo** [comment]
I think that #864 will cover this functionality.

**Comment by bethlakshmi** [comment]
Find the library and include a demo snippet.
