### ISSUE TITLE
Class scheduling info from bid should show on scheduling

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#258]
The class bid info includes stuff from the teacher proposing the class on when they are available (specifically "Times I Would Like to Avoid" and "Preferred Teaching Times") with a clear label.

It would be very helpful to show this to the scheduling user on the event scheduling code for classes (only classes have this data) so that they can look easily for preferences.

This applies to both "create" and "edit"

**Comment by bethlakshmi** [comment]
http://gbeadmin.webfactional.com/deploy_stack/hunter_dev/scheduler/All/Friday

**Comment by burlexpo** [comment]
I think this can be closed -- but maybe we want to walk through the class review and scheduling process before I say that with any finality.

**Comment by bethlakshmi** [comment]
Nope, not closed yet.  Right now, the class bid has "Preferred Teaching Times".  You can see it in class review for a specific class:

http://localhost:8282/class/review/529

But... when you go to schedule the class - as in:

http://localhost:8282/scheduler/create/Class/320

You don't see those preferred teaching times.  My thought was to get the background information from the class bid showing up read-only in some place on the scheduler form.  This would happen ONLY in the case of classes, where they went through a bid process.  We'd have to specifically select what fields to care about, or the screen could get very cluttered.  As a basic idea - also provide a link to review the bid so that the scheduler can get all the information.
