### ISSUE TITLE
Finish Act Tech Info - page for performers

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#259]
- have a hook to poll people who need to give us info
- update with comments to be provided by Scratch

**Comment by bethlakshmi** [comment]
Saving logic should include
- 1 - user must confirm NO music or give track info, track artist, & upload a track 
- 2 - cue props requires notes on the cue??  
- 3 - stage info confirm is needed if no stage info is provided
- 4 - intro text is ALWAYS required, no matter what.
- 5 - stage light colors are always required (if they are on the form), "----" should be changed to "no lights" at the very least.
@burlexpo  - can you confirm?

**Comment by jonkiparsky** [comment]
@bethlakshmi see the "is_complete" functions on each tech item - feel free to change it, but it's how we're doing this now.
(might want to specify acceptable formats for audio if we're requiring tracks - are MP3s acceptable, for example?)

**Comment by bethlakshmi** [comment]
Ah.  I see "is_complete" is in the model and it could support an overload of "is_valid" in the form - a tech info form is not valid if it's data is not complete.  Cool.  Works for me.

**Comment by burlexpo** [comment]
Awesome! I'd love to run this through its paces and get it pushed up ASAP so I can send me the URL to performers.

The Great Burlesque Exposition #9
February 20-22, 2015
www.Burlesque-Expo.com
#BurlExpo9
