### ISSUE TITLE
Show/download Act Tech info by Show

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#261]
Have a way to have tech staff for show get a table and a CSV download of all submitted (or partial) act tech info data.

**Comment by bethlakshmi** [comment]
closed with commit https://github.com/bethlakshmi/GBE2/commit/5e8f42f164915d9a601a4fac9b9c9e06189b0a98

**Comment by jonkiparsky** [comment]
@bethlakshmi - closing this per your comment. Reopen if that's not right.
