### ISSUE TITLE
Giant TEST label on demo stack

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#262]
I'd like the banner on the http://gbeadmin.webfactional.com/deploy_stack/demo/ to make it really obvious you're not on the live site

**Comment by jonkiparsky** [comment]
Low-hanging fruit. This is up, any stack pointing to the demo static files will see this:

![gbe_pagebanner](https://cloud.githubusercontent.com/assets/5283553/5889061/a299854e-a3e3-11e4-9d7c-c1c5e27a6e91.png)

**Comment by burlexpo** [comment]
Love. It.

On 1/24/15 4:11 PM, Jon Kiparsky wrote:
>
> Low-hanging fruit. This is up, any stack pointing to the demo static 
> files will see this:
>
> gbe_pagebanner 
> <https://cloud.githubusercontent.com/assets/5283553/5889061/a299854e-a3e3-11e4-9d7c-c1c5e27a6e91.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/262#issuecomment-71337493>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com
