### ISSUE TITLE
Calendar: show volunteer opportunities

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#265]
Add third calendar type (see issue #257) 

3 - All GenericEvent volunteer opportunities

**Comment by jonkiparsky** [comment]
@BenignCremator Does your commit message on #257 mean this one can be closed as well?

**Comment by BenignCremator** [comment]
Yes, seems to be.  Thank you for pointing this one out, had missed it.  #257 item 3 is redundant to this issue, closing it.
