### ISSUE TITLE
Menu bars have a gap

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#273]
I don't know if this is due to Hunter's addition of the Calendar menu, or some other changes, but I'm now seeing a gap between Calendar and Special menus. See attached image. 
![menugap](https://cloud.githubusercontent.com/assets/5283553/5886098/cde6c8ac-a356-11e4-98da-778ec826b74e.png)

**Comment by bethlakshmi** [comment]
I got this too - and it came with Calendars.

It doesn't kill me.. but it'd be nice to fix.

**Comment by jonkiparsky** [comment]
Regressed with recent commit. @BenignCremator, please see Betty's fix. This stone should kill both birds again.

**Comment by jonkiparsky** [comment]
Fixed this again. @BenignCremator, please be sure to pull this change and not overwrite it.
