### ISSUE TITLE
Calendar generating extra table cells?

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#274]
Looking at the calendar output, I'm seeing some extra empty table cells in the right-hand border:

![extra_cells](https://cloud.githubusercontent.com/assets/5283553/5888858/6fd2ca14-a3dc-11e4-9754-8227462d7366.png)

It looks to me like these correspond to overlapping events - that might be a useful clue.

**Comment by BenignCremator** [comment]
Not able to recreate on my stack.  Pointers?  What stack are you looking at?

**Comment by jonkiparsky** [comment]
Looks like this is cleared up. Can't reproduce it now. Closing.
