### ISSUE TITLE
Is a description of the act and costumine required in Act Tech Info?

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#275]
I put them in, but I'm not sure they are required?

Right now, I set them as optional.

@burlexpo or @BenignCremator - if you want it optional, close this.  If not, comment with what should be required.

**Comment by burlexpo** [comment]
I have no preference. Done is good.

The Great Burlesque Exposition #9
February 20-22, 2015
www.Burlesque-Expo.com
#BurlExpo9
