### ISSUE TITLE
May want to make Act Tech Info editable later?

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#277]
I doubt we care right now, but it's possible to edit act tech info if the perfomer wants to change her mind.  the only thing missing is a navigational hook.

**Comment by eclecticmagpie** [comment]
Actually, this could be a very nice feature if we'll be doing tech directly
from the app and not from printed sheets.  I recall several acts whose tech
requirements changed during rehearsal.

--Michael

Mike Bergman
www.prospecthillforge.com
www.vintagedancers.org/teadance
www.isebastiani.com
reply-to: eclectic@mit.edu

**Comment by jonkiparsky** [comment]
Nothing hard about this -we could certainly give people edit access to
their tech info. And since the tech rehearsals only show rehearsals with
empty slots, they could even change rehearsals if they wanted - they're not
going to cause any harm, since they can't overfill a rehearsal.

If this would be a good thing, remove the question mark and give it a
priority.

**Comment by bethlakshmi** [comment]
The reason I posted this as an enhancement is:
1 - we were trying to publish this TONIGHT and we have too many issues on the plate already.
2 - we have 10,000 things to do and I need to know from @burlexpo if this priority rates over the reports we are trying to do.

If Scratch tells me it rates on Thursday, I'm glad to publish an add on.  For now, I think we need to fix cleaned data and decide, before going live, whether we want a "I'm bringing my own mic" switch - these are both things that block tonight's update.

**Comment by eclecticmagpie** [comment]
I deliberately didn't say it was urgent -- do it when time permits,
including deciding how important it is.



Mike Bergman
www.prospecthillforge.com
www.vintagedancers.org/teadance
www.isebastiani.com
reply-to: eclectic@mit.edu

**Comment by burlexpo** [comment]
Leave it as an enhancement.  The reports are more important.  If it gets implemented before 2/19/15that'd be nice, but not essential.  Pencil and paper work too.

**Comment by jonkiparsky** [comment]
Low-hanging fruit. Closing.
