### ISSUE TITLE
Act management now broken?

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#278]
http://gbeadmin.webfactional.com/deploy_stack/betty/scheduler/acts/

Not sure of the priority, but now this gives me:

DoesNotExist at /scheduler/acts/

ResourceAllocation has no ordering.

Happens when I select a show and go to work on the acts...

**Comment by jonkiparsky** [comment]
Fixed in commit 8663e80aae02d035439e4e567dc207fcd41e3f35
