### ISSUE TITLE
Act Tech Info (audio): performer-supplied audio inputs

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#279]
Posting this for Mike Bergman:

The issue: more and more acts are bringing their own wireless mics and other gear.  Last year, enough that we had several issues:

a) making sure we had enough open channels, and the board configured correctly
b) fussing about radio frequency interference -- we'd like to know in advance the make, model, and frequency or band of each piece of wireless gear.
c) we actually had one act that needed to be unplugged after the act so that we could ply a later act in the same show into that same channel, IIRC.  Certainly such a thing could happen if it didn't already.
d) we actually had problems finding space to PUT them all -- the actual physical space for all the receivers.
e) connections -- we'd like to know EXACTLY what cables their gear uses.  They're not all the same, and we don't have EVERYTHING.
f) for other gear (like instruments) we need to know if a DI is needed, and/or a guitar cable.

**Comment by jonkiparsky** [comment]
It shouldn't be very hard to add a check box for "I'm bringing my own microphone or other audio source".  Any further details, I think, should be registered in the notes, and the head of audio should be in charge of making sure they have the details they need, or contacting the performer for those details.

So we'd need to craft some text for this, but here's a two A.M draft:
"If you are bringing anything that goes through the sound board, give us a full description of what it is, including make and model numbers, frequency or band for wireless equipment, and what sort of connectors it uses. Please be aware that the Expo does have various wired and wireless microphones available. If you would like to use ours, please specify what you need and we'll be in touch to work out the details."

**Comment by jonkiparsky** [comment]
@burlexpo What do you think of this item? It's an easy add - just a boolean field - and now would be a good time to put it in if you think it's a good thing.

**Comment by burlexpo** [comment]
I'm fine with this.  Make it so.

**Comment by bethlakshmi** [comment]
Jon... are you taking this or are you busy with the #279?

I feel strongly that either we fix it pre Act Tech deploy or we wait until 2016.  

And I'm willing to take it if you are working #279...

**Comment by jonkiparsky** [comment]
It's done.

**Comment by bethlakshmi** [comment]
Kick ass.

You rock.

**Comment by jonkiparsky** [comment]
Can you add this to the live db for me?
    alter table gbe_audioinfo add column own_mic tinyint(1) not null default 0;

**Comment by eclecticmagpie** [comment]
You guys are awesome!

Mike Bergman
www.prospecthillforge.com
www.vintagedancers.org/teadance
www.isebastiani.com
reply-to: eclectic@mit.edu

**Comment by bethlakshmi** [comment]
@jonkiparsky

I added the db update to my working SQL script.  I haven't run anything on the live DB yet... figuring we would want to do all of it just before pushing code, and knowing you are still working #285.

For reference it's here:

https://github.com/bethlakshmi/GBE2/blob/master/Database%20upgrades/install%20for%20Jan%202014.sql

And my install approach is:

1 - login to https://my.webfaction.com/
(sending username/password by email)
2 - on the top menu - click Databases -> Databases and pick your db
- usernames/passwords are in the local_settings.py 
Just documenting in case I run out of juice tonight (likely) and Jon wants to do the update w/out me...

**Comment by jonkiparsky** [comment]
Yeah, I think I'm going to have to back up and do a little more work on this. Too much hack here, it's going to bite us. 

I should be able to push tonight, but it might take me a little while.

**Comment by bethlakshmi** [comment]
On this or #285?

**Comment by jonkiparsky** [comment]
Sorry, on #285.
