### ISSUE TITLE
db error on localhost after db upgrade

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#281]
Using Betty's db.sqlite3.newdb on the most recent iteration of the code, I'm getting

no such column: scheduler_eventitem.visible

Is this meant to be a working data instance?

**Comment by bethlakshmi** [comment]
It fell behind the times.

What I published was before I pushed the delete feature.  The publication was linked to the act tech info updates, not the delete feature.  I will check in a sql lite with visible/not visible now...
