### ISSUE TITLE
If "Show me Hotel info" is not checked, than nothing shows up in Column #1

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#283]
I'm not even sure if this is possible.

Currently, when a user creates an account they are asked if they want the hotel room reminder on their personal homepage.

If they check the "show' me the reminder' box, they get text in the first (leftmost) column on their personal page.

If they *don't* check the box, nothing shows up there.

Ideally, we'd have some basic text that displays no matter what, and the hotel info would be displayed in addition to (maybe below) this.  Can we do this easily?

**Comment by jonkiparsky** [comment]
Yes. What text would you like there?

**Comment by burlexpo** [comment]
**Welcome to The Great Burlesque Exposition of 2015**

This is written using GitHub mark-up.  It would use some light HTML formatting (bold and links) on our site

---------------------------

This is your personal landing page, or it will be as soon as you [create an account](http://gbeadmin.webfactional.com/accounts/register); if you've already created an account, you just need to [login](http://gbeadmin.webfactional.com/login).

Once you're logged in, the middle column will show you your personal schedule of events you're signed up for: rehearsals, shows, classes you're teaching, volunteer shifts, etc. and the right-hand column is where you can see acts and classes you've submitted, submit your tech info for acts, and [volunteer](http://gbeadmin.webfactional.com/volunteer/bid) for The Expo.

**Comment by jonkiparsky** [comment]
Okay, doing this. Did you want to update the hotel info, while we're at it?

**Comment by burlexpo** [comment]
No, the hotel info is accurate -- that is, the discounted rate of $149 *was* good until 1/19.  The hotel *may* still give it to people, but they're not obligated to...

**Comment by jonkiparsky** [comment]
Okay. Take a look on demo and let me know how it grabs you. If you want styling, we can do that.
