### ISSUE TITLE
Wrong tech form displayed?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#284]
(Ccing @bethlakshmi in the conversation)

I'm not sure if this is a bug or a question.

I'm logged in as Scratch and, as such, have been accepted for The Rhinestone Revue.

I see the "We need your tech info" alert.  I click the link and I am directed to

http://gbeadmin.webfactional.com/deploy_stack/demo/acttechinfo/edit/177

My act is assigned accepted for The Rhinestone Revue.  I should get "Main Stage" tech information, but I get the "Vendor Hall" tech form.  Am I doing something wrong? Or is something wrong?

**Comment by bethlakshmi** [comment]
Are you absolutely, 100%, you-will-buy-me-dinner-if-I'm-right-certain that you clicked on:

*"You need to schedule a rehearsal slot and/or update act tech info for "Boston Babydolls". Fix this now!"*

And NOT on:

*"You need to schedule a rehearsal slot and/or update act tech info for "Test Act". Fix this now!"*

I wanted to give you BOTH forms.

Act id 177 - "Test act" is scheduled for Late Friday (only in the test environment) and as such gets the Vendor Hall Tech form

Act id 198 - "Boston Babydolls" is scheduled for the Rhinestone Review and gets the Theater tech form.

Judging by the URL you posted, I think you clicked the wrong link.

Can you confirm??

**Comment by burlexpo** [comment]
You are correct.  I didn't realize there were two links there.  There's no break between the two paragraphs.
