### ISSUE TITLE
Can someone set up some more rehearsal slots?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#286]
Hey folks,

When I look at my tech info, I get a message that says all rehearsal slots are closed.

I can't test and see if #270 is actually closed.
I also can't test switching from one rehearsal slot to another.

**Comment by jonkiparsky** [comment]
Working on this. I have to clean up some of the stuff in act tech info, so I can create an act, since I can't even test this until act create works again.

**Comment by jonkiparsky** [comment]
Okay rehearsals are set up.
