### ISSUE TITLE
Calendars - "Shows" needs to be "Shows & Special Events"

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#289]
We put both on one calendar, because they fit well together and fill up the view.

And... it's not just Generic Events that are "special events" - it's also Master Classes, Drop in Classes, and anything that ISN'T a volunteer opportunity.

I thought we said this was higher priority than volunteer opportunities... so I'm nervous it got lost in the shuffle

**Comment by bethlakshmi** [comment]
I read @BenignCremator's checkin comments... and he covered this as something he did.

But the code doesn't work as described... AND I think there is something seriously different between hunter_dev and the current code base - it may be that part of the scheduler is not checked in... but also something else is out of phase, since:

gbeadmin.webfactional.com/deploy_stack/hunter_dev/scheduler/Show/Saturday

is throwing an error.

And the betty and demo stacks do not, but they do not show the costume display (which is a special event)... I'm wondering if we have a checkin gap.

**Comment by BenignCremator** [comment]
The code was working and committed in commit 91f507c.  Some of the relevant code was then removed in commit 8dac8231.  It other people remove my code, my code will not work as described.  We need to discuss our merging practices, as this is not the first, or even tenth, time someone shot down working code with poor merges.

Also, I continued working from where I left off, and had a half completed query in the code while I was researching the error.  Which is why:

gbeadmin.webfactional.com/deploy_stack/hunter_dev/scheduler/Show/Saturday

was not working for a day.  Hunter_dev is a dev stack, and not expected to be functional all the time, only at code checkins from it.

Have double checked that this will work by deleting stack autobuild, pulling it and connecting it to the test DB.  Worked.

**Comment by jonkiparsky** [comment]
Huh. I see that one of my fixes was also reverted in that commit. Yeah,
this is a problem.

**Comment by bethlakshmi** [comment]
The demo stack shows this working better but still not exactly as described...

Reading the code, I do think it's working as intended:

+ event_info(confitem_type = 'Special Event', cal_times = cal_times)

makes me think that somewhere in here we aren't getting Drop-In classes and Master Classes, but we are definitely now getting special events and shows.

**Comment by BenignCremator** [comment]
On 01/29/2015 09:44 PM, bethlakshmi wrote:

> The demo stack shows this working better but still not exactly as
> described...

Ok, then I am missing something about what was requested.  I have 
included shows and special events, and the request, as I read it, was 
for shows and special events.

> makes me think that somewhere in here we aren't getting Drop-In classes
> and Master Classes, but we are definitely now getting special events and
> shows.

So what are the detail types for Drop-In classes and Master Classes? 
This is the first that I have heard that they have different types then 
the other classes, and have not seen them in the types of classes that I 
have been getting from DB queries.

Hunter

**Comment by bethlakshmi** [comment]
http://gbeadmin.webfactional.com/deploy_stack/demo/scheduler/view_list/Master
http://gbeadmin.webfactional.com/deploy_stack/demo/scheduler/view_list/Drop-In

Are both GenericEvent lists of events that should be in the Shows & Special Events menu.

One are GenericEvents of type "Master" and the other is "Drop-in" in the GenericEvent persistence.

**Comment by bethlakshmi** [comment]
If we can get the sum of what's there already + these, i think we are good.

**Comment by BenignCremator** [comment]
On 01/29/2015 11:45 PM, bethlakshmi wrote:

> One are GenericEvents of type "Master" and the other is "Drop-in" in the
> GenericEvent persistence.

Ok, so I add 'Master' and 'Drop-In' to the list of GenericEvents to not 
filter out.  They are showing up (at least, when I schedule them - I 
hope you were not attached to the test DB not changing).  We should be 
good to go.  Take a look, and let me know what you think.

Hunter

**Comment by burlexpo** [comment]
Where are we on this, folks? @BenignCremator?

**Comment by jonkiparsky** [comment]
@burlexpo - Demo stack has the current code for the calendar, as reflected in the repository. If that's what you want, I can push it tonight. If not, I can't fix it tonight.

**Comment by burlexpo** [comment]
The calendar on demo stack still doesn't display all of the Special events (except volunteer shifts) on the calendar -- specifically, it's not displaying the Drop-In classes.

@BenignCremator says "Ok, so I add 'Master' and 'Drop-In' to the list of GenericEvents to not
filter out.  They are showing up (at least, when I schedule them - I hope you were not attached to the test DB not changing).  We should be good to go.  Take a look, and let me know what you think."

But, I'm not seeing the drop-in classes on the calendar.

**Comment by BenignCremator** [comment]
On 02/02/2015 11:08 PM, Scratch wrote:

> The calendar on demo stack still doesn't display all of the Special
> events (except volunteer shifts) on the calendar -- specifically, it's
> not displaying the Drop-In classes.

Are you certain that you have cleared your cache?  I am comparing the 
demo stack to the output of the hunter_dev stack, and seeing a series of 
Drop-In Classes in Crispus Attucks, all hosted by B.A.B.E.  Both seem to 
have them, and the site is listing them as Drop-In classes.

http://gbeadmin.webfactional.com/deploy_stack/hunter_dev/scheduler/All/Saturday

If I am missing something, what is it that I should be looking for?

Hunter

**Comment by jonkiparsky** [comment]
I'm honestly not sure what the cache would have to do with it. This is a matter of the data that's delivered, not the client-side processing it undergoes.
