### ISSUE TITLE
Do we need something better for volunteer opportunity detail displays

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#290]
If you look on the test site right now, and go to:

Calendar -> Volunteer Opportunity (any day) 

You get a list of opportunities.  When yo do that and click on any opportunity, you see something like this:

http://gbeadmin.webfactional.com/deploy_stack/betty/scheduler/details/203

Is that good enough or do we need more detail on this view?

Assigning to @burlexpo so he can say what he wants and set the priority.

**Comment by burlexpo** [comment]
Who sees this? Anyone (i.e., potential volunteers)? Or just staff 
people? If it's "anyone", it should have a description attached to it so 
we can include requirements, experience, etc.

**Comment by bethlakshmi** [comment]
Anyone.  We never said this was private.

If this is awful, I will comment out volunteer opportunities before we go live.

The new way of doing volunteer opportunities does offer a way to give all the info you are talking about, so that is more than a *right now* update.

**Comment by burlexpo** [comment]
I don't understand the questions here.  Maybe we can talk about it on the phone later?

**Comment by burlexpo** [comment]
Can I close this @bethlakshmi ?

**Comment by bethlakshmi** [comment]
We talked about this, and I am updating the display side.  I will make a ticket for Jon for the data input side.
