### ISSUE TITLE
No live rehearsal slots

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#291]
We need to put the actual rehearsal slots onto the live site before I can send out the email to performers asking them to do their tech info.  I would do this myself, but the process seems pretty arcane.

These is the rehearsal time info I sent you on 1/17/15, here for convenience

*The Rhinestone Revue*
Friday, Feb. 20, 2015
Location: Main Theater
Doors open: 7:30pm
Showtime: 8pm
Show ends: 10pm
Rehearsal slot #1: 4pm - 5pm; max 9 people/troupes
Rehearsal slot #2: 5pm - 6pm; max 9 people/troupes

*The Bordello*
Friday, Feb. 20, 2015
Location: Vendor Hall
Doors open: 10:30pm
Showtime: 11pm
Show ends: 1am
Rehearsal slot #1: 5pm - 6pm; max 9 people/troupes
Rehearsal slot #2: 6pm - 7pm; max 9 people/troupes

*The Main Event*
Saturday, Feb. 21, 2015
Location: Main Theater
Doors open: 7:30pm
Showtime: 8pm
Show ends: 11pm
Rehearsal slot #1: 4pm - 5pm; max 10 people/troupes
Rehearsal slot #2: 5pm - 6pm; max 10 people/troupes
Rehearsal slot #3: 6pm - 7pm; max 10 people/troupes

*The Sunday Showcase*
Sunday, Feb. 22, 2015
Location: Main Theater
Doors open: 7:30pm
Showtime: 8pm
Show ends: 11pm
Rehearsal slot #1: 4pm - 5pm; max 10 people/troupes
Rehearsal slot #2: 5pm - 6pm; max 10 people/troupes
Rehearsal slot #3: 6pm - 7pm; max 10 people/troupes

**Comment by jonkiparsky** [comment]
Rehearsals are scheduled. Please verify and close.

**Comment by burlexpo** [comment]
Hard to test on the live site.  I was able to test that rehearsal slots existed for The Rhinestone Revue on Friday (because The Boston Babydolls are part of that show).  I'm going to tell Prima Vera (who submitted the complaint) that she can sign up for a tech rehearsal slot now.  I'm sure I'll hear if she can't ;-)
