### ISSUE TITLE
2015: Create a tool for scheduling rehearsal slots

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#292]
Currently, rehearsal slots are created through some complicated back-end magic.  Let's create a tool so a privileged user can create them and no one has to bug the development team.

**Comment by jonkiparsky** [comment]
As I've said before, this is a complex piece of code to write that's not going to be needed for a while. There are many things that will be done before this one.

**Comment by burlexpo** [comment]
Thanks for the violent agreement.  As I said -- this is an *enhancement* 
for *next year*.

On 1/27/15 11:08 AM, Jon Kiparsky wrote:
>
> As I've said before, this is a complex piece of code to write that's 
> not going to be needed for a while. There are many things that will be 
> done before this one.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/292#issuecomment-71673878>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com

**Comment by burlexpo** [comment]
That said -- we urgently need rehearsal slots on the live site.  I've gotten email already this morning from someone who filled out their tech form but can't sign up for a rehearsal slot...

**Comment by jonkiparsky** [comment]
Okay, they're set up now.

**Comment by burlexpo** [comment]
I think this can be closed.  I can created rehearsal slots.
