### ISSUE TITLE
Calendar: Volunteer shifts are overwriting their parent events

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#294]
Looking at the "All" calendar for Friday, I see that the big thing that's happening 10 PM to 1:00 AM in the Vendor Hall is "Stage Kitten". Surely we'd rather the Bordello take that slot?

**Comment by burlexpo** [comment]
Yes, we would.  Any ideas how to fix this?

**Comment by jonkiparsky** [comment]
I'll discuss it with @BenignCremator

**Comment by BenignCremator** [comment]
On 01/27/2015 03:01 PM, Scratch wrote:

> Yes, we would. Any ideas how to fix this?

Yes, I am going to tailor the query for 'All' to not be 'All' but a list 
of things we want on that calendar.

Hunter

**Comment by jonkiparsky** [comment]
@BenignCremator - it's all yours, then.

**Comment by BenignCremator** [comment]
Have tweaked the 'All' query to query for shows, classes, and special events instead of querying for absolutely everything.
