### ISSUE TITLE
Evie is Disconnected from Persona?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#296]
Sorry for the vague headline; I'm not sure how to describe this in brief.

If I look at http://gbeadmin.webfactional.com/scheduler/details/191 I see that the class and the teacher bio (for Evie) displays properly.  It even has a picture, because I went and used /admin to add a picture to Evie's persona (http://gbeadmin.webfactional.com/admin/gbe/persona/605/).

However, if I use the "View Landing Page" function  and look at http://gbeadmin.webfactional.com/profile/landing_page/533, she has no persona and none of her scheduled events (like her class or The Boston Babydoll's rehearsal time or show time) shows up here.

This is **not** true for D.D. (http://gbeadmin.webfactional.com/profile/landing_page/582) or Stella (http://gbeadmin.webfactional.com/profile/landing_page/580)

**Comment by jonkiparsky** [comment]
Is this an issue that Evie is reporting, or is it an issue that you've found by looking at her profile?

**Comment by burlexpo** [comment]
On 1/27/15 6:43 PM, Jon Kiparsky wrote:
>
> Is this an issue that Evie is reporting, or is it an issue that you've 
> found by looking at her profile?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/296#issuecomment-71753113>.
>
One that I found by looking at her profile.

-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com

**Comment by bethlakshmi** [comment]
View landing page does use additional code - I would doubt the 'let admin view landing page' work over the actual data underneath.

I'll take a look later...

**Comment by bethlakshmi** [comment]
Couldn't help myself... this is true when you log in as Evie as well... 
I went to the test site, reset Evie's password and logged in as EvieSphinx and I don't get get her persona or bid info.

@burlexpo - did you make Evie's stuff or ever change it?  She applied herself, right?

**Comment by burlexpo** [comment]
Evie created her own account.  I added a profile picture using the /admin tools -- which is how I noticed the bug (going to check after I made the change).

Evie's profile displays fine at http://gbeadmin.webfactional.com/scheduler/details/191 but not at http://gbeadmin.webfactional.com/profile/landing_page/533 (which shows she has no persona).

**Comment by bethlakshmi** [comment]
Mystery solved... Evie had TWO accounts.

"Evie" account - 
"Slivara" account -

the email addresses are 1 character off.

The Slivara is the one that actually has the data attached correctly.  The other one has nothing actually connected to it.  To remove confusion, I killed the non-useful account.  This was not a code bug (hooray!)
