### ISSUE TITLE
9 - Fix menus

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#300]
( @bethlakshmi  or @jonkiparsky can you spec this one out a little better? @bethlakshmi said that there was an open ticket which referenced menus, but I can't find anything clear and relevant)

Replace the existing menus with Jscript pulldown menus

**Comment by burlexpo** [comment]
May be resolved by installation of new CMS

**Comment by bethlakshmi** [comment]
GBE-412 and prior tickets closed this with django-cms
