### ISSUE TITLE
Clean up "Show pages" display

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#301]
Take a look at the various items on the "Show" menu
- http://gbeadmin.webfactional.com/scheduler/details/138
- http://gbeadmin.webfactional.com/scheduler/details/139
- http://gbeadmin.webfactional.com/scheduler/details/140
- http://gbeadmin.webfactional.com/scheduler/details/141

In the first place, the pages are just ugly as sin.  We're supposed to be all about beauty and sexiness and these pages are stark.  We could use a little color and maybe a background image.  I like the red velvet curtain we use on the www.Burlesque-Expo.com site and wouldn't mind using that throughout -- or, at the very least, as a background on the show pages.

We could use some "retro-ing".  I think using the "groove" or "double" border on some of the boxes might help, as would using the 'border-radius' to round the corners on some of the boxes.

Come to think of it, those notes could apply to any page on the site...

Specifically for the show pages, we use a hover to display information about a performer when you mouse over their picture.  The boxes that pop up are ugly, and, in some cases, very large.  I'd also like to add a little shadow to them, since right now they sit "right on" the page.

**Comment by jonkiparsky** [comment]
@HonestCoders - if you need changes from the back end (ie, better classes, more divs, that sort of thing) we can provide that, just let us know what you need. 
Also, it would be a great improvement if we got away from hover and went to click-triggered events wherever possible. A site shouldn't ambush its users, and we're doing that all over the place.

**Comment by burlexpo** [comment]
On 1/28/15 12:11 PM, Jon Kiparsky wrote:
>
> @HonestCoders <https://github.com/HonestCoders> - if you need changes 
> from the back end (ie, better classes, more divs, that sort of thing) 
> we can provide that, just let us know what you need.
> Also, it would be a great improvement if we got away from hover and 
> went to click-triggered events wherever possible. A site shouldn't 
> ambush its users, and we're doing that all over the place.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/301#issuecomment-71874093>.
>
Jon -- I don't mind the hovers in certain cases (like the show pages).  
I just don't like the way they look and the fact that some are huge.  I 
understand that you have some strong opinions about site aesthetics, but 
please stop phrasing things in absolutes.

-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com

**Comment by bethlakshmi** [comment]
@HonestCoders - Welcome!

Ditto on Jon's offer if you need a django refactor... I know I have overloaded classes in some places, and would gladly refactor them to give you more freedom for example.  I'm also glad to try to write up a note on what template is used for what - but only if you tell us it helps.

**Comment by bethlakshmi** [comment]
Clarification;  When I said "class", I meant CSS class as referenced in HTML tag.   Not django class... generally we chat about major design stuff as a group. :)

**Comment by HonestCoders** [comment]
Beth,

Any commentary within code will definitely help when it comes to template files. Any iterative objects that are passed to themes annotated would also help me.

Right now I'm mainly  trying to gather scope and what all items we're set on fixing as a "stage 1" feature request. I'm sure more will come to light as time goes on but I think what we're trying to nail down is what absolutely needs to be fixed for user experience, to add value.

Also, do you have a predetermined launch date ? Want to make sure I can meet any time constraints. Thanks.

**Comment by HonestCoders** [comment]
@burlexpo, @jonkiparsky   No problem on beautifying the hover over's. I'm trying to workout what we can do with minimizing the amount of text displayed. Perhaps we can use a "more..." link to segment the description , or some kind of pagination.

Not sure if it's needed but we could use a jquery easing / scrolling parallax affect when a hover occurs at the bottom of the page and the model's pic/description is clipped from view. The jquery effect could reposition the hover over box to bring it into the viewport.  Just some thoughts.

**Comment by burlexpo** [comment]
@HonestCoders, 

Both @jonkiparsky and @bethlakshmi have said kindly offered to help you out if you have any GitHub issues.  If you need to actually talk to a living human being about code, that'd likely be @jonkiparsky, partially because he's more accessible these days.  I'll PM you contact info for both of them.

As far as "Also, do you have a predetermined launch date ? Want to make sure I can meet any time constraints"  ... look behind you.  We're launched already.  We're playing catch-up.  So, ASAP.  Ideally, I'd love to see first pass stuff up and running by a week from today at the latest, with the possibility of more to come.
