### ISSUE TITLE
"All" calendar does not display classes

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#302]
http://gbeadmin.webfactional.com/scheduler/All/Saturday shows drop-in classes, tech rehearsals, and shows.

I have a vague impression this was fixed already, so it may just be that the fix isn't on the live site.  Can we get a push on this @jonkiparsky or @bethlakshmi ?

**Comment by jonkiparsky** [comment]
Will push the current state tonight - the demo stack reflects that state.

**Comment by burlexpo** [comment]
OK -- then closing.
