### ISSUE TITLE
Hide out of date items on menu

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#303]
I'm making this low priority because a) it's not that bad, and b) it may be moot if @HonestCoders is reworking the menus anyway.

There are a couple of items on the **I Want To...** menu that have passed their expiration date:

- ...Perform at The Expo
- ...Submit a class
- ...Be a Presenter

arguably, we could drop "Suggest a Class" too, but we can always use those suggestions for next year.

**Comment by jonkiparsky** [comment]
The menu rework is about presentation on the page, which is separate from the content of the menus. Fixed, this will go in tonight.

**Comment by burlexpo** [comment]
Agreed.  But if @honestcoders was going to both and soon, there'd be no 
point in one of you doing this work.  As it is, it seems like it was a 
quick fix, so, thanks.
