### ISSUE TITLE
Profile Image issue

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#304]
Just got a note from Carmen del Fuego.  She uploaded an image to her profile and saved it.  It displays a broken image on the show page (http://gbeadmin.webfactional.com/scheduler/details/141), but when you click on the "broken image" in the popover, you're taken to the image (http://gbeadmin.webfactional.com/uploads/images/Carmen_2.jpg).  

I already had her resize the image (the original was large and hi-res) and that doesn't seem to have solved the problem.

**Comment by burlexpo** [comment]
Just found the same error with Mistress Leona Star on Main Event page.  Image is http://gbeadmin.webfactional.com/uploads/images/225879_10200880562552198_892206619_n.jpg.

Escalating.

**Comment by jonkiparsky** [comment]
See #231 - we're serving minified images, but when they upload a new image, it's not automatically resized. I'm fixing these two, but anyone else changing their image is going to have to be fixed manually until I get #231 done.

**Comment by jonkiparsky** [comment]
Okay, these are fixed. 
@BenignCremator - is there some way we can watch the uploads directory, so I can know when there are new files to resize?
