### ISSUE TITLE
2015: Display profile image on profile page

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#305]
![photo on 7-21-16 at 8 48 pm](https://cloud.githubusercontent.com/assets/4542707/17043438/a21615e4-4f84-11e6-951e-2b5a71051858.jpg)

2 - Display thumbnails (75-100 pixels tall) of persona images next to related persona. (See sketch above)

**Comment by bethlakshmi** [comment]
The page to show it on is:

http://localhost:8282/gbe

Show:
- all the images

**Comment by bethlakshmi** [comment]
Here's a fiddly detail question - the performers are currently editable when you click on the performer name.
Q:  Should the performer image also be clickable?
If so, can I presume that we *don't* want any sort of clickable link looking margin around the image (a la web development circa 1998), but that it's just clickable.

**Comment by burlexpo** [comment]
Yes, no border.

Just so I'm clear, clicking the image would take me to editing my profile? Seems excessive.  I think don't make the image a link in that case.

**Comment by bethlakshmi** [comment]
That's what I'm asking - I can stick it inside the <a href=".... tag or I can put it outside.  Not linky (outside) it is.

**Comment by bethlakshmi** [comment]
![screen shot 2016-08-21 at 5 32 27 pm](https://cloud.githubusercontent.com/assets/4542707/17839908/54e66720-67c5-11e6-8563-807474c961d6.png)
OK... see attached image.  I don't love this this is fixing the height to 75 pixels.  I'm going fool with this and see if I can find something that doesn't mess with the layout so badly
