### ISSUE TITLE
1 Audio download per show

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#308]
Best implementation:
- make a checklist of all songs,
- turn on/off each song & select all/deselect all
- press button to download what you need

That makes it easier to download just one file when a special snowflake sent you a late breaking addition.

For now - Settle now for 1 big blob per show, ordered by order of acts.

**Comment by bethlakshmi** [comment]
I made some cheesy download links on the act tech review pages I just finished...  there is no compression - it's file by file (ugh), but it's a bare minimum of "shake the system and make the file fall out"...   unless @eclecticmagpie's head explodes, can we make this low?

@eclecticmagpie - if you want a preview - go here:

http://gbeadmin.webfactional.com/

And make yourself a login.  Then let me know and I'll do the rest and set you up.

**Comment by eclecticmagpie** [comment]
Ok, I've created a new account.

--michael

**Comment by eclecticmagpie** [comment]
Hey, bethlakshmi!  I have an account, but I think you need to do something to authorize me to do anything useful.  I'd like to review tech requests and performer music.

**Comment by burlexpo** [comment]
I've added @eclecticmagpie to the "Tech Crew" group.  Mike, check your "Special" menu on http://gbeadmin.webfactional.com/   Do you see something that says "Review Act Tech Info"?

**Comment by eclecticmagpie** [comment]
Yes!  It worked!  Thank you!


Mike Bergman
www.prospecthillforge.com
www.vintagedancers.org/teadance
www.isebastiani.com
reply-to: eclectic@mit.edu

**Comment by burlexpo** [comment]
Mike -- If David is going to need similar access, can you ask him to set up an account too?

**Comment by eclecticmagpie** [comment]
Fooey.  It blew up on me when I clicked on "download all info"

UnicodeEncodeError at /reports/acttechinfo/view_details/138
'ascii' codec can't encode character u'\u2018' in position 49: ordinal not in range(128)

**Comment by eclecticmagpie** [comment]
Before it blew up on me, it was showing me Act, Performer, Contact, Rehearsal Time, and Music -- no sound or light requirements, which I was also expecting.  Is there a different way to get that additional info?  Or is that what "download all info" was supposed to do?

**Comment by eclecticmagpie** [comment]
@bethlakshmi I will ask David to do that.

**Comment by burlexpo** [comment]
There will be.  They're working on a way to display that info in a sensible way.  But this way you've got access to music files

**Comment by eclecticmagpie** [comment]
OK, but I need that info now (well, soon) to generate my pick&pack list.  In particular, how many mics, how many mic stands, any special adapters, how many people are bringing their own wireless gear and which ones are in the same show, and whether anyone needs personal monitors (or thinks that they do)

So, for now, I'd settle for displaying it in ANY way -- it doesn't have to be pretty.

My default is to bring 2-3 mics & stands, and all my standard adaptors but no "special" adaptors (that is, things that I have to go out and buy).  I guess I'll bring two DIs as general insurance--which is usually plenty.  If this is the year that the Kit Kat Orchestra is playing, that won't be enough.

**Comment by eclecticmagpie** [comment]
David Silber has set up an account.  Can someone give him the appropriate
privileges so he can view tech info?

Thank you!

--Michael

Mike Bergman
www.prospecthillforge.com
www.vintagedancers.org/teadance
www.isebastiani.com
reply-to: eclectic@mit.edu

**Comment by burlexpo** [comment]
Took care of @eclecticmagpie's request.  

(Mike, that really should have been a new issue.  Maybe if we have 5 minutes at The Expo I can talk you through Github a little).

**Comment by eclecticmagpie** [comment]
Sorry; I thought it was a follow-up to your request that I have him create
an account.  I know how to create new issues, at least I think I do.
There's lots of other stuff I don't know about, though!

Mike Bergman
www.prospecthillforge.com
www.vintagedancers.org/teadance
www.isebastiani.com
reply-to: eclectic@mit.edu

**Comment by burlexpo** [comment]
Kicked this up to High Priority *if* it can be coded, tested, and implemented before Jan. 30th.  If not, it rolls over for yet another year.

**Comment by jonkiparsky** [comment]
@bethlakshmi I have this working on my local. No PR yet since I haven't got any tests, but if you have time to take a look it's on GBE-308. 
Download link is at the bottom of act tech review for each show. It creates the download if needed, and serves it to the user. The downloads are nuked if someone changes an AudioInfo, forcing a refresh the next time someone goes for a download. Obviously, I'd like to be a bit more targeted about that, but I'm going to call this a good start at this point. 

I also added a few new tricks - management commands and signals, so we should talk about how much we want to make use of each of those.
