### ISSUE TITLE
Demo stack down

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#310]
@bethlakshmi this looks like your fault ;-)

If I go to http://gbeadmin.webfactional.com/deploy_stack/demo/

I get 

NameError at /
name 'reporting' is not defined
Request Method:	GET
Request URL:	http://gbeadmin.webfactional.com/deploy_stack/demo/
Django Version:	1.6.5
Exception Type:	NameError
Exception Value:	
name 'reporting' is not defined
Exception Location:	/home/gbeadmin/webapps/gbetest/deploy/stack/demo/expo/gbe/reports.py in <module>, line 10
Python Executable:	/usr/local/bin/python
Python Version:	2.7.9
Python Path:	
['/home/gbeadmin/webapps/gbetest/deploy/stack/demo',
 '/home/gbeadmin/webapps/gbetest/deploy/stack/demo/expo',
 '/home/gbeadmin/lib/python2.7/psutil-2.1.1-py2.7-linux-x86_64.egg',
 '/home/gbeadmin/lib/python2.7/pip-1.5.6-py2.7.egg',
 '/home/gbeadmin',
 '/home/gbeadmin/lib/python2.7/pytz-2014.4-py2.7.egg',
 '/home/gbeadmin/lib/python2.7',
 '/home/gbeadmin/webapps/gbetest/lib/python2.7',
 '/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/home/gbeadmin/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages/PIL']
Server time:	Fri, 30 Jan 2015 11:12:10 +0000

**Comment by jonkiparsky** [comment]
Now, that's me. Some work half-done at meeting time, that I interrupted to
deal with things that came up in the meeting.

sent from my handy. typos are just part of the fun.

**Comment by jonkiparsky** [comment]
Fixed.
