### ISSUE TITLE
Calendar of co-located concurrent events

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#311]
If I create two events in the same space at the same time (i.e., The Art Show and The Costume Display both take place in The Vendor Hall on Saturday from noon to 8:00 p.m.) the calendar only displays the most recently created one.

**Comment by BenignCremator** [comment]
Potential fix is up on hunter_dev.  Basically, it creates an '(alt)' column for every room that has overlapping events.  Take a look and let me know what you think.

Also, we should consider move the text portion of this to being a variable option in the text options file, and changing it to something clearer.  Thoughts?

**Comment by burlexpo** [comment]
"Also, we should consider move the text portion of this to being a variable option in the text options file, and changing it to something clearer. Thoughts?"

I don't know what this means...

**Comment by burlexpo** [comment]
OK --took a look at http://gbeadmin.webfactional.com/deploy_stack/hunter_dev/scheduler/calendar 

Looks good for now.  May get too big at some point... but we'll deal with that when we need to.

**Comment by BenignCremator** [comment]
Ok, code changes committed and have moved the alt text to a variable in the gbetext config file.  Considering this done for now.
