### ISSUE TITLE
Review Act Tech Info

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#317]
Just making sure things are as they should be...

Under "Special" on the *live* site, there's a menu item for "Review Act Tech Info" (http://gbeadmin.webfactional.com/acttechinfo/view/1) which throws an error (no data)

I think this just may be a URL issue.  Should the menu point to http://gbeadmin.webfactional.com/acttechinfo/view/138 etc?

The menu item doesn't show up at all on the deploy_stack/demo, which makes me nervous because I'm used to things being on Demo which aren't on the live site, but not the other way around...

**Comment by bethlakshmi** [comment]
i know this.  That is why i sent you speciality links!  Note message in the top of the page, this is totally untested but gave you what you needed just as fast as possible.  I pushed this in the middle of the night knowing I hadn't finished navigation.

Please avoid logging bugs on act tech info until we push an update, I've been working on this code radically.
