### ISSUE TITLE
missing act_techinfo_review function

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#318]
@bethlakshmi, I think this is you. 

NoReverseMatch at /scheduler/list
Reverse for 'act_techinfo_review' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['acttechinfo/view/(\\d+)/?$']

Perhaps some part of a commit is missing? 

I can get around it by commenting out the offending lines until you post a fix.

**Comment by bethlakshmi** [comment]
I have been working in that areas, but not seen that... 

I just did a commit after a serious refactor.  If this is still happening, give me a URL that does the problem...?  Also double check that in report_urls there are two lines for acttechinfo/view - one with, one w/out a \d+ in there.

If that is not true... I DEFINITELY missed a commit!

Leaving open in case it's not closed.

**Comment by jonkiparsky** [comment]
Looks like your latest commit fixed it. Thanks.
