### ISSUE TITLE
Current selection of act rehearsal does not appear in act tech info edit form

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#319]
If a user does the following  (after login):

1 - go to home page, get alert, fill out act tech info here:

http://gbeadmin.webfactional.com/acttechinfo/edit/198

Including picking a rehearsal slot

2 - come back later, decide to change something, use the "View/edit" link to go back to:
http://gbeadmin.webfactional.com/acttechinfo/edit/198

Change something (let's say a cue...)

------ 

Then the user will likely have accidentally rescheduled themselves for the first available rehearsal slot - because the rehearsal selector does not load from their current choice the way the rest of the form does.

I tried debugging this for half an hour on the T, and got lost in our various layers of abstraction.  

Assigning @jonkiparsky who may find this a no brainer
Asking verification on priority from @burlexpo 

--- Reason I think this is a HIGH - this bump creates no errors and is very subtle.  Users will not know this happened until/unless they check their slot OR show up at the wrong rehearsal time.  There is also no conflict checking here, so we place a high degree of trust in the fact that the user chose the right thing in the first place.

**Comment by burlexpo** [comment]
Yes. I think this is HIGH also.

**Comment by jonkiparsky** [comment]
Fixed. @bethlakshmi,  the new logic says: if the user has a scheduled rehearsal, put it at the top of the list of choices, even if it's no longer open. If they save, it'll do an extra round of delete-add, take them out of the slot and put them back in. This is fine, no harm done.
