### ISSUE TITLE
My mail is down

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#320]
The email at burlesque-expo.com seems to be down (and at the worst possible time, too).  I've logged a trouble ticket with my ISP, but I have no idea how long it'll take to resolve.

In the meantime, I'll be logging into Git periodically to check for anything with my name on it, and if it's urgent you can email me at scratch@bostonbabydolls.com or text/call me on (617) 869-2000 ( @HonestCoders , I'm in Boston, so not past 8pm your time please).

I'll close this ticket as soon as I have reliable email service again.

**Comment by jonkiparsky** [comment]
@burlexpo Please remember to close this issue once your email is back.

**Comment by burlexpo** [comment]
My email appears to be back up.  5 days without email two weeks before the event... that's what I needed.
