### ISSUE TITLE
You need to have a persona to be an area head

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#324]
I was updating the "Security" Staff Area --http://gbeadmin.webfactional.com/scheduler/edit/GenericEvent/521 -- to make Seth the head of security, but he doesn't appear on the drop-down list of Teachers; my guess is it's because he doesn't have a persona.

*Temporary Fix* make sure all staff have personae on site (they should anyway; hey, @BenignCremator do you?).  *Longer term fix* Is there some bit that identifies a persona as a teacher vs a performer vs a volunteer vs a general dude? Make sure that Staff heads get that bit too.

**Comment by jonkiparsky** [comment]
Scratch, I thought I was to add "area head" as a new item, similar to
teacher, not that we were going to reuse the "teacher" field for this.

sent from my handy. typos are just part of the fun.

**Comment by jonkiparsky** [comment]
In that case, I can tie that to profile, not persona, and this ticket is
mooy

sent from my handy. typos are just part of the fun.

**Comment by burlexpo** [comment]
I'll close this until we get @bethlakshmi 's notes from last night.  I may have misinterpreted how we were doing this.  I thought I was just using the Teacher pulldown for area heads, and the moderator field for shift supervisors, but I may have misunderstood.
