### ISSUE TITLE
Add the mechanisms for Volunteer shifts to have been info on their details page:

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#327]
1 - make there be a head of staff entry place on the parent event - same place as teacher and moderator... same mechanism. (I already made a role for it in the tuple of roles)

2 - add description text boxes to each volunteer opportunity w/in an area.

**Comment by jonkiparsky** [comment]
@burlexpo - please take a look at a volunteer opp edit screen, eg
http://gbeadmin.webfactional.com/deploy_stack/demo/scheduler/edit/GenericEvent/390
and let me know if this works for you.

**Comment by jonkiparsky** [comment]
@burlexpo, @bethlakshmi - please review and let me know if this is what you were looking for

**Comment by burlexpo** [comment]
That looks pretty good -- I'm still seeing "Teacher", "Moderator", and "Panelist" in the upper half of the page -- is that going to switched over to something else?

**Comment by jonkiparsky** [comment]
@burlexpo try 'er now

**Comment by burlexpo** [comment]
No change-- I'm still seeing teacher etc.  I refreshed the page and 
logged out and back in again...

**Comment by jonkiparsky** [comment]
Look under "panelist"
I'm not going to make this a dynamic form tonight, but you've got a selector for staff lead.

**Comment by burlexpo** [comment]
Ah -- see it now.  "Staff lead" = "Area head"? Or "Staff lead" = "shift supervisor"?

Also, since we can't apply teacher, panel, or moderator to volunteer opportunities, is there a way to remove them from volunteer opportunities?

**Comment by jonkiparsky** [comment]
"I'm not going to make this a dynamic form tonight."
All of these use the same form - I know how to make the form have just the fields we want, but that's down in enhancement land.
