### ISSUE TITLE
Volunteer info entry/display for later

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#328]
Have "shift captain" for a given opportunity, and then display on event lists.  

Not needed now.

**Comment by jonkiparsky** [comment]
I notice that there is a "staff lead" role under the volunteer types ("Role" dropdown under volunteer allocation). Could we make use of that?

**Comment by burlexpo** [comment]
I think "Staff leads" are department heads.

**Comment by bethlakshmi** [comment]
Darn it.  I added "head of staff" not noticing.

We should condense, but that means a template I checked in may need an update.
