### ISSUE TITLE
Orders and act tech info

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#329]
Add the magic of orders to the act tech info.  Let's do this 4 ways:

1 - put the order as new column on the summary page here:

/reports/acttechinfo/view_summary

2 - sort by order on the summary page

3 - sort first by order, second by cue #,  in the downloaded CSV table on the link that page.

4 - put a column in the downloaded CSV that is <order #>.<cue #>  (##.## - so basically a decimal)
   This makes it super easy in excel to return to the sort order that was delivered and gives a very clear order of what's going to happen during the show.  

Mostly how to grab orders is something I haven't tried yet

Low... but needed 2 days before expo.

**Comment by jonkiparsky** [comment]
Note that the secondary sort by cue sequence # brakes if two acts get the same primary order.

**Comment by burlexpo** [comment]
Just to make sure I understand -- don't make two different acts "Act number 3", right? Shouldn't be a problem.

**Comment by jonkiparsky** [comment]
Correct. Also, make sure you order all of the acts, since they get a
default order of -1.

**Comment by jonkiparsky** [comment]
This is done. @bethlakshmi please verify at http://gbeadmin.webfactional.com/deploy_stack/demo/reports/acttechinfo/view_summary/139

and let me know if that's what you'd wanted.

**Comment by bethlakshmi** [comment]
Looks perfect.

Act order #2 is overloaded rightnow, right?  I see 2 number 2s.

I'm good for closing this.

**Comment by jonkiparsky** [comment]
Order is act order - where this person comes in the lineup. Sort order is
how this sorts on the page. (as you requested)
Sort order will differ from act order where there are act techs.
