### ISSUE TITLE
Add "Photography/Media" as volunteer interest area

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#332]
For 2016 -- there's no reason for John Bilotti to not manage the photographers through the site, since we can set up shifts, etc.

**Comment by burlexpo** [comment]
I'm making this one active and High Priority.  I think it's a quickie; if I'm wrong, someone tell me.

**Comment by jonkiparsky** [comment]
Should be pretty easy.

**Comment by jonkiparsky** [comment]
PR #606 issued.
