### ISSUE TITLE
*Legal* first name and last name

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#333]
Change the text on the profile page (http://gbeadmin.webfactional.com/update_profile)

From
- "First Name" to "Legal First Name"
- "Last Name" to "Legal Last Name"

Add help text which reads "Please provide us with your legal first and last names.  This information is only used by the event staff never shared with anyone without your prior permission.  Please use your stage name in the *Badge Name* field."

**Comment by gawaineo** [comment]
Hi,

How can I get to the live version of this link (http://gbeadmin.webfactional.com/update_profile) that was posted above?

G

**Comment by bethlakshmi** [comment]
Oh wow, right ! old link!

On your local, should be:

http://localhost:8282/update_profile

or on test:

http://gbe2016test.gbeadmin.webfactional.com/update_profile

**Comment by bethlakshmi** [comment]
you need to login, first, though.

**Comment by gawaineo** [comment]
ok great.

**Comment by gawaineo** [comment]
Also is it necessary to add test cases for this update? A test case would be checking if the the label "Legal First Name" exists.
