### ISSUE TITLE
Act Tech form shows "Waitlisted" "Rejected" etc.

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#335]
When I evaluate an act there are two fields -- the state of the act (Accepted, Waitlisted, etc) and the show.  If I say an act is "Rejected", and the show menu is on "Main Event" that performer will show up in the Main Event tech section.

I can work around it for the time being, but this needs to be fixed before Expo Thursday or it will cause trouble for the techs.

**Comment by bethlakshmi** [comment]
Updated on the live site, too, since it was a pain and a one line fix.
