### ISSUE TITLE
URGENT: Volunteer Review not reflecting Volunteer form accurately!

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#336]
I got a volunteer submission form from Tom Creed.  If I use the "Review" tool to assign him to shifts, it clearly shows that he is both "available" on Friday morning and "not available" on Friday morning. (http://gbeadmin.webfactional.com/volunteer/review/289) No problem, right? Clearly a user error. 

Wrong.  If I go and "edit" Tom's form (http://gbeadmin.webfactional.com/volunteer/edit/289) to fix the conflict, I can see that there is no conflict... the information on the "Review" page doesn't accurately reflect the information indicated here.  This makes it *really* hard to schedule volunteers accurately.

**Comment by bethlakshmi** [comment]
OK... will try to look at at rehearsal tonight

**Comment by bethlakshmi** [comment]
This was a really bizarre case where Friday morning appears erroneously.  Just Friday morning, because of how the data is stored.  I'd like to revisit a better way than the fix I provided... after the expo, but this is hacked and fixed for now.

I pushed to live immediately given the urgency.
