### ISSUE TITLE
Show Volunteer Schedule not working

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#337]
I went to http://gbeadmin.webfactional.com/scheduler/edit/Show/17 and clicked on "See Schedule" to see what holes I had in my volunteer coverage.  I was taken to

http://gbeadmin.webfactional.com/reports/staff_area/139

which is a 404 error.

Page not found (404)
Request Method:	GET
Request URL:	http://gbeadmin.webfactional.com/reports/staff_area/139

@jonkiparsky I *think* this is your code; if it's @bethlakshmi please reassign to her.

**Comment by bethlakshmi** [comment]
it's me.  I added this code in the last push.

**Comment by jonkiparsky** [comment]
Yeah, but I think I see the error - working on it now, unless you've got it

**Comment by jonkiparsky** [comment]
Got it. Closing.

**Comment by bethlakshmi** [comment]
Added to it, found it again in class scheduling so I fixed it more... pushed to live along with some other view related fixes (I think I was smoking something on Friday, ick).
