### ISSUE TITLE
Shrink a picture

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#340]
I just had a host upload her image and it's huge.  Can you do your picture magic on http://gbeadmin.webfactional.com/uploads/images/IMG_04814-3.jpg? And, if you can't, let me know and I can do it by hand.

**Comment by jonkiparsky** [comment]
This will have already happened. If you go to a show and look at the path
to an image, you'll see that it points to a subdirectory, and the images
are all small. If her image isn't in that subdirectory (with the same name,
IMG_04814-3.jpg) then let me know and I'll see what's failed.

It's possible that we still have links to the larger images on the site. If
you find such, let me know and I'll fix that.

**Comment by burlexpo** [comment]
Found it.  Thanks.  I was following the image connected to her profile which still links to a large image.
