### ISSUE TITLE
CSS not getting pushed from Demo to Live

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#341]
I know there have been a couple of updates to the live site since I made my test tweak to the .css page (the blue box displaying time and location).  It shows up on the Demo stack (i.e., http://gbeadmin.webfactional.com/deploy_stack/demo/scheduler/details/139 on the right, just above the perfomers), but not the same page on the live site.

Did I do something wrong?

**Comment by jonkiparsky** [comment]
I think neither of us did a full push last night. (if Betty did, she didn't
collect static) I'll have a little time between work and meeting, I'll see
to this then.

**Comment by jonkiparsky** [comment]
Done
