### ISSUE TITLE
Profile image points to large image, not minified

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#342]
All images should point to the minified versions, unless we're explicitly looking to offer a high-res download link

Currently, image on profile page points to full-size, not minified.

**Comment by BenignCremator** [comment]
On 02/12/2015 12:12 PM, Jon Kiparsky wrote:

> All images should point to the minified versions, unless we're
> explicitly looking to offer a high-res download link

> Currently, image on profile page points to full-size, not minified.

This is chicken and egg problem.  Currently, the image minification is 
occurring as a cron job, every 5 minutes.  Linking with the profile 
occurs when the image is uploaded.  To get this to work, we will either 
need to relink the image to the profile, using the minified one, after 
the cron job runs, or have the upload process kick off the minification, 
and then link the profile to the image.  My preference is for the 
second.  Will look into the feasibility of doing that after I get 
volunteer shift calendars working.

Hunter

**Comment by burlexpo** [comment]
Let's back burner this until after this years expo. We can fix it then.

**Comment by jonkiparsky** [comment]
@benigncremator - Long-term, I suggest we consider moving to a library like
sorl-thumbnail
Short-term, it's a bearable pain, but I'd really prefer not to force users
to download a high-res image.

**Comment by jonkiparsky** [comment]
Closing this with #350  - apparently it wasn't back-burnered after all. 
One caution: under the current situation, if we start displaying a promo image on a user's profile, we'll have to check for the minified image, since it won't be there for ~5 minutes after creation. So what'll happen is that when they first create their account, we'll have to show the large image, until the minified one is generated.
