### ISSUE TITLE
"All Details" not working

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#344]
Clicking on "All Details" to download the.csv from http://gbeadmin.webfactional.com/reports/acttechinfo/view_summary/138 throws an error (below).

I haven't tested the other shows yet, but I assume they're the same.

UnicodeEncodeError at /reports/acttechinfo/view_details/138
'ascii' codec can't encode character u'\u2018' in position 49: ordinal not in range(128)
Request Method:	GET
Request URL:	http://gbeadmin.webfactional.com/reports/acttechinfo/view_details/138
Django Version:	1.6.5
Exception Type:	UnicodeEncodeError
Exception Value:	
'ascii' codec can't encode character u'\u2018' in position 49: ordinal not in range(128)
Exception Location:	/home/gbeadmin/webapps/gbetest/expo/gbe/report_views.py in export_act_techinfo, line 152
Python Executable:	/usr/local/bin/python
Python Version:	2.7.9
Python Path:	
['/home/gbeadmin/webapps/gbetest',
 '/home/gbeadmin/webapps/gbetest/expo',
 '/home/gbeadmin/lib/python2.7/psutil-2.1.1-py2.7-linux-x86_64.egg',
 '/home/gbeadmin/lib/python2.7/pip-1.5.6-py2.7.egg',
 '/home/gbeadmin',
 '/home/gbeadmin/lib/python2.7/pytz-2014.4-py2.7.egg',
 '/home/gbeadmin/lib/python2.7',
 '/home/gbeadmin/webapps/gbetest/lib/python2.7',
 '/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/home/gbeadmin/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages/PIL']
Server time:	Fri, 13 Feb 2015 13:02:21 +0000

**Comment by jonkiparsky** [comment]
Encoding bullshit. Cleaning the data.

**Comment by jonkiparsky** [comment]
Data cleaned. All acts download correctly now.

**Comment by bethlakshmi** [comment]
Sweet!  Thank you!

**Comment by jonkiparsky** [comment]
@bethlakshmi - Just to loop you in on this, what was happening seems to be that csv writer requires ascii, and barfs when it comes across non-ascii characters. Some of the acts had used smart quotes and other cute stuff (there was an accented 'a' in "Tyranna Suarez") which worked fine for display, but not for download. 

I've put in a ticket that basically says "we need to figure this out" for next year.
