### ISSUE TITLE
Staff leads could be filtered by "is staff" quality of user account

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#346]
We're never going to have Staff Leads that we don't give some privileges to... we could make the drop down smaller and nicer next year by filtering on them either having:

(A) the "staff" setting in the user account
(B) any of our groups for special roles 

Or both.  That would give us a list of 12 or so people instead of the 100 or so with profiles.

(also I'm too lazy to write another ticket... but profiles don't have pictures, so all we can show is the same of the profile of the staff lead.  No adorable picture.  D'oh)

**Comment by jonkiparsky** [comment]
We can certainly do privilege management better, which I would say is the key point of this ticket. Implementation details, we can worry about when we get there.

**Comment by bethlakshmi** [comment]
Totally agree on the "later" part.   But this wasn't privilege management - this was usability.

When I try to pick a "staff lead" on the pull down in editing an event, I have the list of all profiles ever entered in the system.  Staff leads will always have some type of privilege, so we can make the form way more useable by limiting the values in the drop down to only the privileged users.

It won't change the access control logic at all - it just makes one field a little easier to use.

**Comment by bethlakshmi** [comment]
I ended up creating a "staff lead" search based on whether the user is currently leading a staff area or special event.  Once the conference has passed, a lead of this type looses their staff lead status, which works well for our flow.  No more need to mess w. this ticket.
