### ISSUE TITLE
Gah!  Something changed while I was testing!

### ISSUE THREAD

**Issue by eclecticmagpie** [bethlakshmi/GBE2#347]
Now I'm getting file not found errors again.
The Mooch: 
Request Method:	GET
Request URL:	http://gbeadmin.webfactional.com/reports/acttechinfo/view_summary/uploads/audio/Lucy_The_Mooch_short.mp3
"reports/acttechinfo/view_summary/uploads/audio/Lucy_The_Mooch_short.mp3" does not exist

I *was* getting a mix of behaviors.

All M4a files tested used to download when clicked.  I had to drag the first one to iTunes manually, but they've all opened automatically since then.  NOW they all seem to give file not found errors.

Several MP3 files downloaded, and most started playing without downloading, in streaming mode.  I did not have a chance to test whether I could force a download on the laptop. NOW they all seem to give file not found errors.

The behavior was somewhat different on the iPhone than on the laptop.

Right now, I'm getting file not found errors on everything I select.

**Comment by jonkiparsky** [comment]
Looks like someone forgot a leading / in a url... :)

**Comment by burlexpo** [comment]
@jonkiparsky -- can you fix and push? I know @bethlakshmi is in transit to the show already.

**Comment by burlexpo** [comment]
(this is Betty on Scratch's computer)
I can't fix this - my computer has no Net, and Scratch's computer will take too long to get used to (since I should be warming up for a show right now)

Notes on recent fixes:
- I pulled the / to fix the problem in the first place.  
- I pushed code at ~3:30 PM today as what what in the queue was 90% bug fixes
- I recommend changing *.name to *.url in the href tag rather than adding a slash.

**Comment by jonkiparsky** [comment]
Not going to be able to do anything with this until tonight.

sent from my handy. typos are just part of the fun.

**Comment by burlexpo** [comment]
No worries, @jonkiparsky (it's Scratch, reasserting control over my account).  We'll all be snowed in tomorrow with plenty of time to code... yay.

**Comment by eclecticmagpie** [comment]
Sounds like you guys understand the problem; I don't really need a fix till Monday myself. Have a great performance!

**Comment by bethlakshmi** [comment]
Fixed it.
This time 4 real.
pushed just this to live.
