### ISSUE TITLE
Change "Performer Items" to "Participant Items"

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#348]
Because we have participants (teachers, volunteers, vendors) who aren't performers, we should change the language on the Personal Pane to reflect this.

Change _Performer Items_ to **Participant Items**
Change _Create a New Stage Persona_ to **Create a new profile**
Add a label **Profile:** just below the headline, so the second line in the Personal Pane would read 

**Profile:**  profile name  (i.e., I would see **"Profile:** Scratch")

**Comment by jonkiparsky** [comment]
I think there's some confusion here that needs to be resolved. 
**Profile** is the underlying user information. Internally, it's a combination of two objects, but essentially you can think of it as the user profile and you won't be very wrong. This is the actual user. In general, this will be the name that people can write checks to. 
**Persona** is a public face that an individual user adopts for various purposes (here, teaching and performing). It's who you become when you put on your costume and adopt your mannerisms, it's also what you're marketing. In general, this will be the name people know. 
**Performer** is a collection of one or more personae - a single person, adopting a persona, can be a Performer. A group of persons, all having adopted personae, can become a collective Performer (ie, a Troupe or a Combo, though we've for some reason lost Combo)

We can probably come up with better ways to present this, but I definitely don't want to confuse "profile" and "persona" - that would make life very difficult.

**Comment by burlexpo** [comment]
Yeah.  As it is, the terminology is terrible and clunky (at best), 
opaque at worst. Fortunately, it's within our power to change that 
terminology.

Table the conversation until after the Expo.
