### ISSUE TITLE
Deal with "Persona" (now "Profiles") better.

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#349]
While the idea behind a single user having multiple "personae" is good, we don't execute it very well.  Unless I'm going to name my personae something like "Scratch - Teacher" and "Scratch - Performer" (and have one of those weird names show up wherever a persona was displayed), it'd be nice to have the user be able to label their profiles so they could tell which was the teacher bio and which was the performer bio.

Additional thought -- add a assignment function to the profiles.  If I have multiple profiles (and only if I have multiple profiles?), have a drop-down menu that says "Display this Profile with..."  where options are "Performance; Classes; Panels; All"

**Comment by jonkiparsky** [comment]
I don't see why you'd have two personae, both called "Scratch". I'd assume that Scratch the MC is the same persona as Scratch the teacher of "Simple Magic Tricks For Dancers". The point of the multiple personae is for someone who, for whatever reason, performs/teaches/vends under multiple distinct identities, which need to be kept separate. (for example, someone who has a "side project" performing in a distinct style or genre, and wants to keep the two personae distinct for marketing reasons)

If people are creating multiple personae in the way you're describing, I think the answer is to clarify the use of personae, not to exacerbate the problem.

**Comment by burlexpo** [comment]
Table the conversation until after the Expo.

**Comment by bethlakshmi** [comment]
Did this after Divio port
