### ISSUE TITLE
Weirdness on Conference Schedule 

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#351]
If you look at http://gbeadmin.webfactional.com/deploy_stack/demo/scheduler/Class/Saturday

you'll see that "Big Hair, Don't Care" appears at 2pm in both Molly Pitcher and Molly Pitcher (alt).  My guess is this is a problem with data -- possibly something Scandal messed up, but I thought I'd bring it to your attention before I go deleting classes.

**Comment by jonkiparsky** [comment]
It was double-booked. Cleaned up.
