### ISSUE TITLE
Can't use () or . in Show due to schedule_acts URL lookup

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#353]
I had a test show called "The Bordello (Fri. Late)" in my test database.

It failed on a URL reverse lookup until I changed it to "The Bordello".

I'd much rather we use ids than names for any URL lookup.  We do absolutely nothing to guarantee names are unique, so looking up names will always produce non-deterministic results.

**Comment by jonkiparsky** [comment]
This is not changing between now and the expo. Enhancement.
