### ISSUE TITLE
Editing the order of a show?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#354]
Weren't you going to put a link to editing the order of a show some place obvious?

When I'm on (for example) http://gbeadmin.webfactional.com/reports/acttechinfo/view_summary/141 I can see the act order, but no way to edit it.

**Comment by jonkiparsky** [comment]
On the act schedule page. 
![schedule_acts](https://cloud.githubusercontent.com/assets/5283553/6222382/8ed0179a-b620-11e4-97e4-28b5e23e4d8e.png)

**Comment by burlexpo** [comment]
Thanks.  I knew it was around here somewhere -- I was looking for it in 
the act tech stuff.
