### ISSUE TITLE
Hide "Type: Show" on show pages

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#355]
Just above the list of performers, there's a slug which reads "*Type:* Show"  

Let's hide this on the show pages.  It's weird.

**Comment by jonkiparsky** [comment]
The simple fix broke show scheduling. Back to the drawing board

**Comment by burlexpo** [comment]
An inelegant fix might be to set it as a css class and set that class to 
be white font on a white background.  It doesn't free up the real estate 
but it hides the text.

**Comment by jonkiparsky** [comment]
Sorry, if it were that easy I'd just pull it off the page.

**Comment by burlexpo** [comment]
It looks like the DIV class is sched_detail; we can't just add a line 
into the .css which says

.sched_detail {
     color: white;
}

?

**Comment by jonkiparsky** [comment]
Yes, if we want to hide any payload information we show on any event. But
if we want to do that, I can just remove the loop that displays that stuff
in the first place.
