### ISSUE TITLE
Lucie Luxe image broken on class display page

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#356]
See http://gbeadmin.webfactional.com/scheduler/details/185

**Comment by jonkiparsky** [comment]
Okay, fixed - I've set it to show no image if no image is there to show. 

Someone (@burlexpo) might want to tell Lucie Luxe to upload an image, but at least now it doesn't look like we broke it.

**Comment by burlexpo** [comment]
Image up.

We should probably have a default profile image when none is found.

**Comment by jonkiparsky** [comment]
We do have a default profile image, but it really looked a lot better to
not use it in this case.
