### ISSUE TITLE
teacher bio/images repeated on class display

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#357]
http://gbeadmin.webfactional.com/scheduler/details/185

**Comment by burlexpo** [comment]
On 2/16/15 11:38 PM, Jon Kiparsky wrote:
>
> http://gbeadmin.webfactional.com/scheduler/details/185
>
Yeah, that's because Mina (who set these up) is gaming the system -- and 
it doesn't work.

I'll work with her tomorrow to re-create and re-schedule these.

But it won't fix the broken image ;-)

**Comment by jonkiparsky** [comment]
Okay, this is in your court, then.
