### ISSUE TITLE
Default profile image 

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#358]
If someone doesn't upload a profile image, we should have a default one to use.

**Comment by jonkiparsky** [comment]
We have one, and it's in place on shows (where you sort of need an image
for the layout to work)

For teachers, it looks a lot better to just do without the image - if you
want an image, we can either require the user submit an image if they're
going to teach, or we can find some better stock images and assign one per
customer, so it doesn't look as terrible.

**Comment by bethlakshmi** [comment]
I agree w. Jon on this, particularly in light of all the bootstrap stuff we just did.  If we want default images places we don't have them, I'll want to know:

1 - what URL
2 - what image (attach to ticket)

Which means a whole new ticket.
