### ISSUE TITLE
Seth can't get Staff Reports

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#359]
User Swilhelm is our head of security.

He has a "Special" menu on his homepage, and he can see the "Reports" item on that menu.

When he clicks on the "Reports" menu, he is still on his homepage.

When I look at the Security Staff Report I see "Staff Lead - Seth Wilhelm".  I looked at http://gbeadmin.webfactional.com/admin/auth/user/242/?_changelist_filters=q%3Dseth and I think he has all the right privileges.  What is Staff Reports part of?

**Comment by jonkiparsky** [comment]
Privilege model for reports assumed that users had staff permissions, which none of them should have.

**Comment by burlexpo** [comment]
Can this quick fix get pushed?

**Comment by jonkiparsky** [comment]
Pushed. You can test by modifying your own groups. If you have at least one
permission group, you should see the special menu and the "reports" item in
it, and you should be able to view the reports list.
