### ISSUE TITLE
Ginge O'Lolly has two accounts

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#361]
Ginge O'Lolly successfully created two accounts -- one named "Ginge" (http://gbeadmin.webfactional.com/admin/auth/user/31/?_changelist_filters=q%3Dgin) and one named "Gingeololly" (http://gbeadmin.webfactional.com/admin/auth/user/157/?_changelist_filters=q%3Dgin) -- same email address for both.

She successfully submitted an act with one of the accounts, but I can't figure out which.  I'd like to delete the 'bad' account.

**Comment by jonkiparsky** [comment]
Going to the user administration page and searching for that email, I was able to look at the profile pages for each account. "Ginge" had an act submitted. The other has been consigned to the flames.
