### ISSUE TITLE
Unicode Error is back

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#362]
http://gbeadmin.webfactional.com/reports/badges/print_run

Gives the dred unicode error, probably from syncing w. BPT.

@jonkiparsky  - what are you doing to fix this?  I know you are cleaning the data, if there's a manual process... let me know, so I can know if this breaks again at the last minute.

Also - would there be a reasonable pre-CSV generation option?  For example, would wrapping "__unicode__" around every field help?

**Comment by bethlakshmi** [comment]
It's here too:

http://gbeadmin.webfactional.com/reports/stuffing

**Comment by jonkiparsky** [comment]
Basically, I look at the data. The error message tells you what you're
looking for ("\xef") and where to look for it (in the thing you're calling
"row")

The main trouble is working out what the data item is. In this case, I have
the header directly above, so I can see that it's in the "Last Name" field
of


row

[u'Joy Va Voi',
 u'Joy',
 u'Va Vo\xef',
 u'badge & pool party wristband, ',
 'Joy Va Voi, ',
 '',
 '',
 '',
 'Late Friday at the Bordello, Late Friday at the Bordello: Tech Rehearsal, ']




so I'm guessing that's in the User.last_name field. And when I look, yes, I
see an umlaut on the i. (I'll leave it in place, so you can follow the
trail)

I don't know what the right fix would be, off the top of my head. There may
be a function that would fit the bill, but I don't really want to dive into
that rabbit hole at this stage. I'd just fix the data and move on.

**Comment by bethlakshmi** [comment]
thanks
