### ISSUE TITLE
Another Unicode error

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#365]
@bethlakshmi 

We can't get the info for The Sunday show -- http://gbeadmin.webfactional.com/reports/acttechinfo/view_details/141

gives

UnicodeEncodeError at /reports/acttechinfo/view_details/141
'ascii' codec can't encode character u'\u201c' in position 66: ordinal not in range(128)
Request Method:	GET
Request URL:	http://gbeadmin.webfactional.com/reports/acttechinfo/view_details/141
Django Version:	1.6.5
Exception Type:	UnicodeEncodeError
Exception Value:	
'ascii' codec can't encode character u'\u201c' in position 66: ordinal not in range(128)
Exception Location:	/home/gbeadmin/webapps/gbetest/expo/gbe/report_views.py in export_act_techinfo, line 229
Python Executable:	/usr/local/bin/python
Python Version:	2.7.9
Python Path:	
['/home/gbeadmin/webapps/gbetest',
 '/home/gbeadmin/webapps/gbetest/expo',
 '/home/gbeadmin/lib/python2.7/psutil-2.1.1-py2.7-linux-x86_64.egg',
 '/home/gbeadmin/lib/python2.7/pip-1.5.6-py2.7.egg',
 '/home/gbeadmin',
 '/home/gbeadmin/lib/python2.7/pytz-2014.4-py2.7.egg',
 '/home/gbeadmin/lib/python2.7',
 '/home/gbeadmin/webapps/gbetest/lib/python2.7',
 '/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/home/gbeadmin/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages/PIL']
Server time:	Wed, 18 Feb 2015 17:34:55 +0000

**Comment by jonkiparsky** [comment]
Fixed
