### ISSUE TITLE
process usage over  memory limit again

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#367]
Whatever we are doing to minify is causing problems again.

got the message:
"Memory usage way over your limit - processes killed "

And I saw some weird restart behavior.

**Comment by jonkiparsky** [comment]
More details? This doesn't tell me what the problem is, whether it's still a problem, or where to go to diagnose and fix. 
It doesn't even tell me that it's got anything to do with minifying, and that seems unlikely considering that there have been only two images resized into mini in the last week: 

    [gbeadmin@web462 images]$ ls -lt mini|more
    total 6604
    -rw-r--r-- 1 gbeadmin gbeadmin  54293 Feb 18 17:20 IMG_8586_wecopy_copy.jpg    
    -rw-r--r-- 1 gbeadmin gbeadmin  50063 Feb 17 15:20 Lucy_Lux-0867.jpg
    -rw-r--r-- 1 gbeadmin gbeadmin  37570 Feb 12 17:15 bbblogo.jpg
    -rw-r--r-- 1 gbeadmin gbeadmin  22645 Feb 12 07:15 IMG_04814-3.jpg
    -rw-r--r-- 1 gbeadmin gbeadmin  20163 Feb 10 03:35 JZBich_3-8-14_r_w_001.jpg
    -rw-r--r-- 1 gbeadmin gbeadmin  66760 Feb  9 18:55 WP_20131119_040_1.jpg
    -rw-r--r-- 1 gbeadmin gbeadmin  66760 Feb  9 18:40 WP_20131119_040.jpg


I'm sure there's something going over limit, but two resize operations separated by a day wouldn't do it. 
If you have anything detailing the usage problems, please get it to me so I can figure this out.

**Comment by bethlakshmi** [comment]
Messages like this can be seen in the web console:

https://my.webfaction.com/messages/196127/edit-message

username: gbeadmin
password is in your email, I've sent it several times.

This was received on Feb. 19th, and this is all the detail I have:

Hello,

Right now (2015-02-19 14:28:00 UTC) it appears that your processes on Web462 are using a lot more memory than your plan allows.

If you haven't read it yet, we recommend that you have a look at our "Reducing Memory Usage" article (http://docs.webfaction.com/software/general.html#reducing-memory-usage) for tips on how to keep your memory usage down.

Your total allowed memory is 512MB and your current memory usage is 570MB.

Since your high memory usage is impacting other users on the server we had to kill your processes (our watchdog first sends a SIGTERM to your processes and then sends a SIGKILL a few seconds later).

You need to either find a way to keep your memory down or you'll have to upgrade to a plan that allows more memory.

Please respond to this message to let us know how you're dealing with the problem.

Below is the list of processes that you're running with the memory that they use (the command used to list these processes is "ps -u gbeadmin -o rss,etime,pid,command"):

User - Memory - Elapsed Time - Pid - Command:
--------------------------------------------
gbeadmin - 1MB - 1 day, 10:19:12 - 156608 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 2MB - 1 day, 10:19:12 - 156609 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 33MB - 1 day, 10:19:12 - 156610 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 52MB - 1 day, 10:19:12 - 156611 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 60MB - 1 day, 10:19:12 - 156612 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 38MB - 1 day, 10:19:12 - 156613 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 36MB - 1 day, 10:19:12 - 156614 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 51MB - 1 day, 10:19:12 - 156615 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 41MB - 1 day, 10:19:12 - 156616 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 2MB - 1 day, 10:19:12 - 156617 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 2MB - 1 day, 10:19:12 - 156618 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 123MB - 1 day, 10:19:12 - 156619 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 99MB - 1 day, 10:19:12 - 156620 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start
gbeadmin - 30MB - 1 day, 10:19:12 - 156621 - /home/gbeadmin/webapps/gbetest/apache2/bin/httpd.worker -f /home/gbeadmin/webapps/gbetest/apache2/conf/httpd.conf -k start



Regards,

WebFaction team - http://www.webfaction.com
