### ISSUE TITLE
6 - Force Uniqueness of user info

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#385]
-	username
-	badge name
- emailaddress

People make multiple accounts and that's a pain, we should get them to stop it.  Username, email, ~~and badge name~~ should both be unique

**Comment by burlexpo** [comment]
People are going to start registering in May or June, so we need to have this sewn up by then.

**Comment by jonkiparsky** [comment]
Are we sure we want badge name to be unique? This means that if we have two John Smiths at the expo, only one of them can get their name on their badge. It's easy enough to do, but since we're not using the badge name for anything inside the system, I'm not seeing the value.

**Comment by bethlakshmi** [comment]
My impression was that we were forcing uniqueness of usernames and email
addresses - not Badge Names.

I agree with Jon on this - people may just use first names for Badge names.

My thought is that when a user tries to make an account with an email or
username that already exists, we could:
- catch it
- offer to send the password reset link (our current passowrd fixing thing)

So that we're making it easy to do the right thing.

-Betty

**Comment by burlexpo** [comment]
I agree with all of this. 

S.

**Comment by jonkiparsky** [comment]
Question on this ticket: how do we handle uniqueness of purchase_email?
I think it can't be required to be unique, since we might have, for example, John and Jane holding separate GBE accounts (since they're separate GBE performers) but having the same purchase_email (since they manage their finances together, and buy their tickets together).

Is this a correct understanding of the situation?

**Comment by bethlakshmi** [comment]
An interesting question and probably good for another ticket sometime.

I think that a purchase email should only be on 1 account (so... not
conflicting with OTHER purchase emails), but not have any relationship with
the user's regular email, other than the idea that by default they are the
same.

But I want to think through and it's not that urgent -  so I'd be happy to
call the ticket of "don't let people make multiple accounts with the same
email" closed without figuring this out.

**Comment by burlexpo** [comment]
So... can we close this one?

**Comment by jonkiparsky** [comment]
Let me review this, I don't see these changes checked in.

**Comment by bethlakshmi** [comment]
Wasn't that this one?
https://github.com/bethlakshmi/GBE2/pull/483

**Comment by jonkiparsky** [comment]
Yes, that's the one.
