### ISSUE TITLE
4 - Get off www.burlesque-expo.com by May

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#386]
-	CMS tools in django for – relatively high
     - Flat pages for HTML
     - Set templates 3 or so layouts (Scratch can write to be static)
     - Source code flip over
     - Check-in presentation
     - Content is in DB
-	Dynamic Menus – low priority
     - Name, structure, URL, privilege

**Comment by jonkiparsky** [comment]
I'd assume we'd like to keep the www.burlesque-expo.com domain, but use our django for the whole thing, right?

**Comment by burlexpo** [comment]
Yes and use Webfactional to host. 

The Great Burlesque Exposition #9
February 20-22, 2015
www.Burlesque-Expo.com
#BurlExpo9

**Comment by burlexpo** [comment]
I think this is really more of a placeholder for multiple issues that may be detailed elsewhere.

**Comment by burlexpo** [comment]
Our Bandzoogle account expires in 5 days.  I'm going to move all of the email list information off of there, and figure out who the heck the mail admin is for the URL and close the account.  I'll set www.Burlesque-Expo.com and www.BurlesqueExpo.com to point to gbelive.webfactional.com

**Comment by bethlakshmi** [comment]
Yay!.  I'm good with closing this whenever you are.

**Comment by burlexpo** [comment]
Why did you close this? I don't think we've actually done it...

On 10/17/15 12:31 PM, Jon Kiparsky wrote:
>
> Closed #386 <https://github.com/bethlakshmi/GBE2/issues/386>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/386#event-438265498>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2016
Feb. 5-7, 2016
Cambridge, MA
www.Burlesque-Expo.com

**Comment by jonkiparsky** [comment]
I closed it because the comments suggested that it was ready to close.
Current status?

**Comment by burlexpo** [comment]
Technically, we are off of the Bandzoogle servers.  I'd like to have the 
current site show www.Burlesque-Expo.com rather than 
gbelive.webfactional.com  I said I would look into taking care of this, 
but I've fallen down on the job.

On 10/17/15 1:09 PM, Jon Kiparsky wrote:
> I closed it because the comments suggested that it was ready to close.
> Current status?
>
> On Sat, Oct 17, 2015 at 12:32 PM, Scratch <notifications@github.com> 
> wrote:
>
> > Why did you close this? I don't think we've actually done it...
> >
> > On 10/17/15 12:31 PM, Jon Kiparsky wrote:
> > >
> > > Closed #386 <https://github.com/bethlakshmi/GBE2/issues/386>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bethlakshmi/GBE2/issues/386#event-438265498>.
> > >
> >
> >
> > --
> >
> > ------------------------------------------------------------------------
> > The Great Burlesque Exposition of 2016
> > Feb. 5-7, 2016
> > Cambridge, MA
> > www.Burlesque-Expo.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bethlakshmi/GBE2/issues/386#issuecomment-148929741>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/386#issuecomment-148934899>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2016
Feb. 5-7, 2016
Cambridge, MA
www.Burlesque-Expo.com

**Comment by bethlakshmi** [comment]
We did it!
