### ISSUE TITLE
Extra types of Roles for an Event

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#393]
MC
Featured Guest

Show up special in a Show - not in the grid with everyone else, before it with a snazzy display.

Have a way for the power user to make this stuff show up “Special”

**Comment by bethlakshmi** [comment]
@burlexpo  - how does this look for what you had in mind for selecting featured acts & hosts?

![screen shot 2017-06-27 at 4 37 50 pm](https://user-images.githubusercontent.com/4542707/27608894-13863072-5b57-11e7-9b4b-223ed34eb448.png)

The default is "Regular Act" which shows up in the grid we currently have.

The words shown here for featured performer/host will be what I use when annotating the special stuff.  Anything not a "Regular Act" gets treated as special.  The special list is pretty easily extensible, but it will take a code update.

Let me know:
- that you like the look of it
- any changes to the words in the drop down
- any changes to the text label - "Special Display Selections:" was a real mouthful and makes the screen kind of ugly (OK, this is one wart among many...)
- I'm alphabetizing by performer name in the featured performer display, right?

I'm not blocked, I'll be another few days at the rest of it.

**Comment by burlexpo** [comment]
The mechanism looks fine.  Are the "Special Display Selections" stored somewhere on /admin so I could go and add another one without bugging you?

Do the words in the drop down also appear on the show page? If so, I'd want to change them to "Featuring..." and "Hosted By...".  We could add a third category of "Returning Winners" for use with the winter conferences.

I think changing the label to "Section" is fine and clear.

Yes, you're alphabetizing by performer name within any display group.

**Comment by bethlakshmi** [comment]
OK, first prototype done, and now I really DO need feedback:

![screen shot 2017-06-27 at 11 13 56 pm](https://user-images.githubusercontent.com/4542707/27619119-624b3298-5b8e-11e7-85d7-0f66442a83d2.png)

Here's the image - yes, I faked in a bunch of data to give myself something real to play with.

Problems I see 
**1 - the irregular size of boxes makes this look choppy.  I know I can do the following:**
- set a standard height and force them all to it.  
- (probably w/in my grasp) fix the text to go to a "..." when the last line is reached.

**2 - the irregular image sizes makes a more awkward display** - I have a ticket to force people to do our bidding, we haven't prioritized it - #1052 

**3 - the "featuring" rather blends into the background**, so does the "Check out our fabulous Performers!" which gets smooshed in below (and off the bottom of this page). 
- I could really use thoughts on this, I don't have a strong sense of what do --- maybe whitespace?  Or color the underlying area differently?

![screen shot 2017-06-27 at 11 20 12 pm](https://user-images.githubusercontent.com/4542707/27619285-37180956-5b8f-11e7-90df-4a512e986559.png)

**4 - What to do for the hover.**  My recommendation is:
- make an eye, a link and a modal icon.
- the eye makes the picture big
- the modal icon makes the same modal as the regular performer (in case bios got cropped)
- link takes to website - I figure featured performers deserve a little extra love.

FYI - known bug that I don't intend to fix...  there are as many boxes as there are cast acts - so a performer can end up with multiple boxes if they are cast multiple times in the same show.  Let me know if I have to deduplicate and if so - what role takes precedence?

I still have a few days of work, but I want feedback before the weekend.

**Comment by bethlakshmi** [comment]
_The mechanism looks fine. Are the "Special Display Selections" stored somewhere on /admin so I could go and add another one without bugging you?_

Not yet - want me to do that?

**Comment by burlexpo** [comment]
@BurlExpo: The mechanism looks fine. Are the "Special Display Selections" stored somewhere on /admin so I could go and add another one without bugging you?

@bethlakshmi: Not yet - want me to do that?

@BurlExpo: Yes, but I think it's lower priority than some other stuff we've got going on.

**Comment by burlexpo** [comment]
**_1 - the irregular size of boxes makes this look choppy. I know I can do the following / 2 - the irregular image sizes makes a more awkward display_**

I like the way Bea Trouble's looks and I think it's because it's the only image which is square as opposed to portrait or landscape.  It gives a good balance of text and image and, if we force all the images to display at the same size, makes the entries all the same size,

**_3 - the header (Special Guests) rather blends into the background,_**
Yup.  A dark background bar with text the color of the center pane would work fine as a divider (see image), as would simply using 20th Century Poster, which we use for every other header.
![featrued-perf-sample](https://user-images.githubusercontent.com/5369404/27689895-bd665cdc-5cad-11e7-9edd-9eab067d13a6.png)
