### ISSUE TITLE
Text for front page of parked website

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#394]
(I'll also probably send you an image of the 2015 winners)

The Great Burlesque Exposition of 2015 has come and gone and what a weekend we had! We proved that neither snow nor rain nor more snow nor gloom of night nor "Really?! More snow?!" could keep you from coming to Boston.  Thank all of you who participated and attended.  You're what makes the Great Burlesque Exposition truly great.

Congratulations to the winners of the *2015 Howard Awards:*

**Best Hybrid** Kiki Allure
**Most Humorous** Cherie Nuit
**Most Beautiful** Gala Delicious
**Most Classic** Mika Romantic
**Best Solo Performer** Sailor St. Claire

We're taking advantage of a little bit of downtime to make some major improvements to our already awesome website.  Look for a prettier, easier to use, website sometime around June 1 -- and mark your calendars with these important dates!

August 1, 2015: Application period opens
November 5, 2015: Applications close
December 5, 2015: Acceptance notifications sent
February 5-7, 2016: The tenth Great Burlesque Exposition!

**Comment by jonkiparsky** [comment]
Done.

**Comment by burlexpo** [comment]
So here's a question ...

If I still need to get at pages that are on the parked site (like the act tech info) can I? Because I need to...

**Comment by jonkiparsky** [comment]
That would require a little more work. I've taken the site down, which means cutting off all access through the normal interface. If you want "down except for..." then we need to figure out what exactly you want the ellipsis to contain. 
What is it you need to be able to do?

**Comment by burlexpo** [comment]
I need access to the Act Show Tech Info summary sheets, so I can see the 
order of performances for all shows, and I can download the music for 
acts.  This is because the quality of the recordings on the video isn't 
good enough and need to be enhanced.  I really just need access to the 
two Friday shows (Rhinestone Revue and Bordello), but I figure that's 
harder than just giving me access to all of them.

John Bilotti would like to be able to see the lists of performers with 
pictures so he can identify the people in photographs are.

**Comment by eclecticmagpie** [comment]
What was the problem with the quality of the recording on the video?  It
may not be possible to do anything about it, but it may -- please log it as
a separate issue.

Also, you should have all the audio on your show computer.

Finally, there were several known audio source problems with the late night
show; you probably remember that, but I thought I'd mention it just in
case.  I don't recall any source problems with the Review audio.
--Michael


Mike Bergman
www.prospecthillforge.com
www.vintagedancers.org/teadance
www.isebastiani.com
reply-to: eclectic@mit.edu

**Comment by jonkiparsky** [comment]
I can provide "backdoor access", either through a deploy stack tied to prod db or through a backdoor url.
