### ISSUE TITLE
3 - Mailing List Manager

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#395]
Currently, emails are managed through Bandzoogle.  When the Bandzoogle site goes away, so will my ability to send mass emails.

I'd like to install ccMail (https://www.softaculous.com/apps/mail/ccMail) or OpenNewsletter (https://www.softaculous.com/apps/mail/OpenNewsletter) on the site.  Both of them are php scripts and I don't know if we're running php on the site.  If we're not, there are a bunch of Django newsletter packages (https://www.djangopackages.com/grids/g/newsletter/); I just need one installed.

**Comment by jonkiparsky** [comment]
Closed, see GBE-417.
