### ISSUE TITLE
1 - Set up "hidden" old website

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#397]
Please reactivate the 2015 Expo site on a deploy stack so I (and others) can access it.  We're using security by obscurity and anyone who accesses it will understand that it is purely an historical record and any changes made to this site will not be reflected in the actual site.

**Comment by burlexpo** [comment]
I think this is done and can be closed.  Am I right @bethlakshmi ?

**Comment by jonkiparsky** [comment]
Closing.
