### ISSUE TITLE
Auto download and install changesets from GitHub on a2hosting server

### ISSUE THREAD

**Issue by BenignCremator** [bethlakshmi/GBE2#40]
Subticket of #35 

Setup a means of selecting a changeset from GitHub, download it, and install it.  Install this onto the GBE2 server on a2hosting.

**Comment by BenignCremator** [comment]
No longer using a2hosting, closing this ticket as out-of-date.

**Comment by jonkiparsky** [comment]
Surely the server you're pulling from is irrelevant? I think this is about pulling changesets, not about a2hosting.
