### ISSUE TITLE
Incorrect argument to TextField: "max_length"

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#402]
TextField does not take a max_length, so this is simply confusing. Removing this argument from TextFields in gbe/models.py

**Comment by bethlakshmi** [comment]
So... how does one cap the length of a TextField?  Via the form?  These
shouldn't be open ended in size, in fact, I dislike open ended
text/character chunks in any form.

-Betty

**Comment by jonkiparsky** [comment]
I believe we'd do this with validators. I'll take a look at what we're
doing on the Accelerate platform and let you know.
