### ISSUE TITLE
Internal error or misconfiguration

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#415]
In trying to login to either http://gbe2016.gbeadmin.webfactional.com/ or http://gbe2016test.gbeadmin.webfactional.com/ I get HTLML Error 200:

"The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, [no address given] and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log."

**Comment by bethlakshmi** [comment]
The two sites have been up for a week+ with no crash.  I posit that the 2 account system is working.  Please reopen if you find differently.
