### ISSUE TITLE
Send Betty the Go Fund Me snippet

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#418]
I can see that Go Fund Me is a Flash widget that can be embedded in the page.

And they give you a snippet of code to build the widget. Can you please send me whatever it is they give you for the widget on GBE?  There are two pieces I'm missing on the home page - the snippet, and the mailing list which @jonkiparsky  is working on.

**Comment by burlexpo** [comment]
Here is the widget code:

`<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="258" height="338" title="Click Here to donate!" type="application/x-shockwave-flash"><param name="movie" value="//funds.gofundme.com/Widgetflex.swf" /><param name="quality" value="high" /><param name="flashvars" value="page=burlexpo&template=4" /><param name="wmode" value="transparent" /><embed allowScriptAccess="always" src="//funds.gofundme.com/Widgetflex.swf" quality="high" flashVars="page=burlexpo&template=4" type="application/x-shockwave-flash" wmode="transparent" width="258" height="338"></embed></object>`
