### ISSUE TITLE
How much do we care about "Home" page.

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#419]
What I'm finding is that the very first page in the menu MUST be "/" and what that resolves to for us is the landing page of the logged in user or the "please create an account for yourself" message that we used as the landing page last year.

I have a feeling you want to create your own page for the site - like you have for the "home" on Burlesque-Expo.  Please confirm.

It's a bit of work I don't want to start on w/out asking.

**Comment by bethlakshmi** [comment]
to be noted - I'm close on the look and content - Its the landng page nature that is hard.

**Comment by jonkiparsky** [comment]
The landing page can redirect in various ways if we want. My thought was that the new landing page would more or less mimic the burlesque-expo site, and we add in navigation from there to functionality.

**Comment by burlexpo** [comment]
*I have a feeling you want to create your own page for the site - like you have for the "home" on Burlesque-Expo. Please confirm.*

Yes, I want the first page someone sees to have useful information and a bit of hype -- more options than just 'please login' or (if they're already logged in) their personal info.

**Comment by bethlakshmi** [comment]
I'm going to fix this in my GBE-412-alt work.

**Comment by bethlakshmi** [comment]
https://github.com/bethlakshmi/GBE2/commit/dd5c4a300243c69c10fe059b9521a0cb24720b1a
