### ISSUE TITLE
Replicate "Drop Us a Line" interface 

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#424]
A widget to get Name, Email, and a message. Send same to some address, which should be set in settings.py,  (I believe it's going to be info@burlesque-expo.com, confirm)

Validate email field is a legitimate email address. 
Current implementation shows green "Thank you for your submission" banner on successful submit, and removes form from page.

**Comment by jonkiparsky** [comment]
@burlexpo the widget as implemented on burlesque-expo.com does not allow for a subject line. This would be easy to add if you want. Would this be an improvement?

**Comment by burlexpo** [comment]
On 6/20/15 12:53 PM, Jon Kiparsky wrote:
>
> A widget to get Name, Email, and a message. Send same to some address, 
> which should be set in settings.py, (I believe it's going to be 
> info@burlesque-expo.com <mailto:info@burlesque-expo.com>, confirm)
>
Confirmed.
>
> Validate email field is a legitimate email address.
>

**Comment by burlexpo** [comment]
On 6/20/15 1:10 PM, Jon Kiparsky wrote:
>
> @burlexpo <https://github.com/burlexpo> the widget as implemented on 
> burlesque-expo.com does not allow for a subject line. This would be 
> easy to add if you want. Would this be an improvement?
>
Yes, please add the ability to enter a subject line.  Thank you.

**Comment by jonkiparsky** [comment]
Subject line is included.

**Comment by jonkiparsky** [comment]
There is a pull request up covering this. I expect there might be some changes requested by reviewers, so I'm leaving this as "in progress" for now.

**Comment by jonkiparsky** [comment]
Closed in PR#425. Further improvements will go on new tickets.
