### ISSUE TITLE
Where should the contact-gbe form redirect?

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#435]
Right now, it takes you to the account page - which is there if you are logged in, but will be an error if the user isn't logged in or doens't have an account.

Where do we want it to go?  Ideas include:
- root of website
- the page that they came from (no message will be shown, though, that would be harder)
- the home page of the logged in user (needs an alternative if they didn't log in)
- some kind of static "thanks!  We've got your request!" type page.

**Comment by jonkiparsky** [comment]
I lean towards a "thanks, we've got your message" page.

**Comment by burlexpo** [comment]
I think we build a static 'got the message' page which redirects to the 
homepage after 10 seconds.

**Comment by jonkiparsky** [comment]
I think that sounds like it would be better handled with javascript -
redirect to homepage, with an overlay saying "got the message", which can
self-dismiss after a timer expires. This is something we could do, but for
the moment I think that's more effort than I think we can promise for the
deadline we're working under.

For now I think it's best to redirect to a static page, with a "continue"
button that takes them to home - either root or their home page if logged
in. (this logic is pretty easy)

The improved version would take them to home (again, root or their page if
logged in) and drop a "got your message" overlay which would dismiss on a
click or after a timer expires - but that's a bit more of a ticket.

**Comment by burlexpo** [comment]
Redirect to [URL] after X seconds is basic HTML.  No need to use 
JavaScript at all; it just goes into the page header with a META tag.

<meta http-equiv="refresh" content="5;url=pagename.html">

where "5" is the number of seconds before refresh.

**Comment by jonkiparsky** [comment]
Yes, I know what you meant. What I'm saying is, I think that's not a good choice from the user experience perspective.

**Comment by burlexpo** [comment]
OK.  We disagree.  I think it's fine UX -- and better than having the 
user push a 'continue' button -- so we'll do it the easy way (using the 
meta tag redirect).

**Comment by jonkiparsky** [comment]
Apparently a decision has been made. Closing this issue.

**Comment by bethlakshmi** [comment]
Did you already implement it?  I have not...  Please leave open if we
didn't actually make the change ...  Or link to the commit if you're way
ahead of me.

**Comment by jonkiparsky** [comment]
The ticket asked for a decision. Decision was made, so I closed the ticket.

sent from my handy. typos are just part of the fun.
