### ISSUE TITLE
User messaging

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#436]
We need a method to drop user-facing messages into an arbitrary page, to meet the following needs:
1. General messaging. ("Site going down for maintenance", "Two days until act submission deadline!")
2. Group-focused messaging. ("Congratulations, your act has been accepted. Please fill in your act tech info form by [DEADLINE]")
3. Event-based messaging. ("Your act has been submitted", "Your message has been sent"). 

There are three standard ways to serve this sort of message: a brightly-colored strip inserted along the top of the frame, an inserted div in the page content, beneath the title, and an overlay. Ideally we'd be able to do all three, but the first of the three is the most general-purpose and least disruptive to layout, so it should be preferred if we want only one.

**Comment by bethlakshmi** [comment]
I do really like #1 and I could see a way to put it into django-cms in the
base.tmpl.

They have classes for info, error and maybe warn... which could be tricked
out to also give color and style, and it would make it easy to both:

- add django-cms blobs to a specific page unrelated to our business logic
- add developer-driven messages.

My thinking is we really have 2 cases:

- Scratch/other writer - needs to make an alert based on random things
happening in the business
- Developers have needs to alert users of the status of their activities
based on the logic of their actions (draft saved... , bid submitted...)

And so it really needs to work for both django-cms stuff and our code.

I have an idea on how to do this in base.tmpl using containers than can
work for both cases... but I need to think on it some...

**Comment by jonkiparsky** [comment]
To be a little more precise about the two cases, we need 
# Arbitrary messaging on demand, scheduled by an administrative user responding to exigencies in the world. 
# Programmatic messaging responding to expected events in the state of the data. 

Obviously, it would be best if the text/form of the latter were configurable by administrative users. (should not be necessary to make a commit to change any text on the site)

I agree that this isn't a hugely difficult item, but we shouldn't just bang it out. Serious thought should go into the UI for managing alerts, for example.

**Comment by bethlakshmi** [comment]
Yep.  And we may want to design the visuals based on what we want the user to do...  thoughts for moving forward:
- put together a list of the basic messaging types we need (example - admin messages for FYI, deadlines, emergencies, developer error statuses for system is broken, user did something that MUST be fixed, user did something that they should be cautious about, user succeeded/FYI) 

- figure out how to clarify the message for the action we expect to provoke in the user and where we have distinct behaviors we'd like to trigger 

- design the visuals

- design the backend connection for both admin trigger and code trigger.

**Comment by burlexpo** [comment]
I'm commenting on this to pop it to the forefront.  A piece of this that I would love to see before 12/5 is "Programmatic messaging responding to expected events in the state of the data." (I think).

What I want is when the status of a bid is changed, that the owner of that bid receives an email which says something like

Dear (user name),

The status of your (type of bid -- i.e., act, class submission, vendor application, costume submission, etc.) has been changed to (new status).  You can always check the status of your submissions or your schedule by visiting your personal pane on www.Burlesque-Expo.com

Is this possible? How long do we think it would take? Can it be done before 12/5? It would be really useful.

**Comment by bethlakshmi** [comment]
This ticket needs a review and a breakdown.  The comments don't match the original description.

@burlexpo - can we sit and refine this into other tickets and then close this one?
