### ISSUE TITLE
Update requirements.txt, write appropriate install script

### ISSUE THREAD

**Issue by BenignCremator** [bethlakshmi/GBE2#439]
The install procedures listed in requirements.txt are not completely clear, and some of the listed requirements are misleading.  Rewrite this doc to reflect the actual needs for install, with correct install paths and locations.  Later, write an install script to partially automate the process of setting up a new site.

**Comment by jonkiparsky** [comment]
requirements.txt is not a list of procedures, it's a list of dependencies. 

`pip install -r requirements.txt`

-b is the option to specify a build directory. 
`pip install --help`
