### ISSUE TITLE
What do we actually want on the /gbe?

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#454]
Right now it's:

http://gbe2016test.gbeadmin.webfactional.com/gbe

(logout, then click the link)

I think this less useful for our it's currently used - the logout text is most visible now right after logout - when both the form for contact, and the text about creating an account are irrelevant.

Give me thoughts and assign to Betty for fixing.

**Comment by burlexpo** [comment]
Hi there,

I'm sorry -- I've read this several times and I just can't tell what you're asking me.  I'm pretty sure there are some key words missing; this doesn't make any sense to me at all: "I think this less useful for our it's currently used".

**Comment by bethlakshmi** [comment]
@burlexpo  - take a look at the updates, you'll see that the "Your Account" menu has an item called "Your Expo" - that was my approach to this problem.

The problem is that:

http://gbelive.webfactional.com/gbe

didn't have any sort of a menu item, because it used to be the home page of the gbe site.

Now - the static home content is the home page.

So... where would users go to see their account stuff?  

If you don't like how I solved it, give me a better idea.
If you are OK with this fix, close the ticket.
