### ISSUE TITLE
New layout with Volunteer Scheduling for an Event is ugly

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#463]
it's not unusable, but it deserves a review.  The problem is on

/scheduler/edit/_any_event_class_/_event_id_
- where the event class is not of type Volunteer Opportunity

The Volunteer Management table is very long and as a result, it drifts way off the fixed width working area in the new layout.

It's 100% useable, the visual breakage isn't a blocker to the user.  But it's ugly and this is the placeholder to review when we have time.

It will benefit from the wise use of CSS, but I believe template work will be needed for this to be nice looking.

**Comment by burlexpo** [comment]
@jonkiparsky I *think* this is the issue I was talking about...

**Comment by jonkiparsky** [comment]
@burlexpo  I'll want to consult with you about this in more detail if I'm going to take this on. Probably a one-one thing. 
Can you modify the priority so it reflects your wishes?

**Comment by bethlakshmi** [comment]
enough layout work happened recently that if we want it more useable, we need to redefine what actions we want.  The problems cited here are largely fixed on a laptop sized screen.
