### ISSUE TITLE
Make ticket list easier to read... easier changes

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#469]
The page at:

/ticketing/ticket_items

Is excrutiating.

I have two ideas:

1 - make the huge descriptions something that appears as about 100 characters of text and a ...

 (Bonus... it's a bit more work) - make the cropped text have a "more" type icon/text link that when clicked pops up all the text.  Arguably not worth it, since the "edit" button will get you to all that text and you can edit it.

@burlexpo  - would love a sense on priority.

**Comment by burlexpo** [comment]
100 or so characters and an ellipsis are fine.

And, the ticket item IDs all need to be updated.  It might be easier to blow these all away and add this year's tickets new.
