### ISSUE TITLE
Make ticket list hierarchial (harder... but not way hard) and thus easier to use

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#471]
The ticket list is actually two levels of stuff:

- level 1 = the event - marked by the event id, for example:

www.brownpapertickets.com/event/1999418

is the event for application fees, and "1999418" is the id.

- level 2 = the prices - for example, right now, in live and test, application fee has 3 prices:
   - discount code free
   - an early bird price
   - a regular price

As the system is currently designed, ticket items are flat - so each row of the table is the event+price - and in the database each ticket of this level has stuff like:
  - title 
  - description
  - active (visible)/inactive
  - linked events
  - registration info (badgeable and ticket style)

In our business logic some of this could be boiled up more highly:
  - linked event and registration info is common across all price points

and it could be displayed on the 

/ticketing/ticket_items

in the hiearchy - letting the user pick the type of "event" - Whole Shebang, Application Fee, Vendor Fee, etc.  Then letting the user work with a given price point.  

Which would make the table a the URL above less of a mind-boggling, hallucinatory experience. 

This is harder work than the previous issue, so relative priority is even more important (that is directed at you, @burlexpo)

**Comment by burlexpo** [comment]
This seems like it kills two birds with one stone, so I'd like to make it a high priority.
