### ISSUE TITLE
webfactional + drop us a line form don't work

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#476]
Everything seems to function OK, but no email is sent.

Other code using the send_mail command works and Jon's pull request is submitted.

I suspect it's either:
A - my configuration on gbe2016test in the gbeadmin account (like the local settings)
B - that the webfactional servers won't let me send the from_address from an external account, since that failed when I tried send_mail from the manage.py shell.

Taking a break to clear the head and grab dinner... then will pound head against wall until victory.

**Comment by jonkiparsky** [comment]
This works:
```
>>> from django.core.mail import send_mail
>>> send_mail("Foo", "Bar", "jon@kiparsky.net", ["jon.kiparsky@gmail.com"])
1
>>> 
```

So it's not about external account. 

This also works:
```
>>> send_user_contact_email("JON", "jon@kiparsky.net", "foo bar baz")
```

So it's something about the way it's being called, I think.

**Comment by jonkiparsky** [comment]
Working on this.

**Comment by jonkiparsky** [comment]
PR issued

**Comment by bethlakshmi** [comment]
Pull request looked good, I approved.
But it's not working - I get:

SMTPRecipientsRefused at /user_contact

{u'jon.kiparsky@gmail.com': (554, "5.7.1 <bethlakshmi@gmail.com>: Sender address rejected: Please use Gmail's SMTP servers"), u'bethlakshmi@gmail.com': (554, "5.7.1 <bethlakshmi@gmail.com>: Sender address rejected: Please use Gmail's SMTP servers")}

My only change on the site was to turn Debug to True.
