### ISSUE TITLE
Edits to http://gbelive.webfactional.com/conference/volunteer/

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#481]
_Existing Text_ 
## Volunteer to be a Teacher or Panelist

Please check the box and fill out the relevant information for any class or panel you might be interested in.
### Panel

The Great Burlesque Exposition is looking for Moderators and Panelists for the following Panels. Moderators are expected to organize the other Panelist volunteers, guide the discussion and be prepared with points for discussion in the panel they are moderating. Panelists are expected to provide a unique perspective on the topic of the panel and to be able to participate eloquently in a discussion of the topic.

_Replace with..._
`<H2>Apply to be a Panelist or Moderator</H2>`
`<P>The Great Burlesque Exposition is looking for Moderators and Panelists for the panels listed below. <strong>Moderators</strong> are expected to recruit and organize the other panelists, prepare to guide the discussion ahead of time by creating key questions and topic suggestions, and keep the conversation moving and civil at the panel.  <strong>Panelists</strong> are expected to provide a unique perspective on the topic of the panel and to be able to participate eloquently in a focused discussion.</P>`
`<P>In order to be a panelist or moderator, please indicate which panels interest you, what role you'd like to commit to, and any qualifications or personal connection you have to that particular panel.</P>`
`<P>If you would like to <em>suggest an idea for a panel</em>, please do that <a href=http://gbelive.webfactional.com/class/propose/>here</a>.`

**Comment by bethlakshmi** [comment]
This section actually covers the ability to volunteer for specific classes, panels or "either" - 

http://gbelive.webfactional.com/conference/volunteer/

Take a look at the more complex range and let me know if you want other updates before I checkin.

**Comment by burlexpo** [comment]
I want to re-write this business logic entirely.  This is clunky and complicated.  Since we won't have any panels immediately, I'm just going to hide this link until after 8/1.

**Comment by bethlakshmi** [comment]
OK - for the record, this is what I implemented to last year:

https://github.com/bethlakshmi/GBE2/wiki/Volunteer-as-panelist-%28or-teacher%29

It took enough time and was tricky enough as it was, that I want to carefully revisit this before redoing it.

**Comment by bethlakshmi** [comment]
removed this
