### ISSUE TITLE
Additions to http://gbelive.webfactional.com/act/create/

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#484]
I'd like to add a series of checkboxes after the section "I am interested in..." and before "Name of act".

This is *not* a required field.

Label: Other performance opportunities

Help Text:  Don't feel badly if you're not accepted to perform in one of the formal shows.  We have a ton of other ways to get your performance fix! Indicating that you are interested in doing one or more of these activities has no effect on whether or not you are accepted to perform in a show.  You may be accepted to perform and still do these activities.

Checkboxes:

- Go-go dance during one or more of the shows (we'll ask which one later)
- Be part of the opening number for The Main Event
- Model in the Fashion Show (Sunday afternoon)
- Model in the Swimsuit Show (Saturday night late)

Can this be done for 8/1?

**Comment by bethlakshmi** [comment]
Not easily, you are asking for an update to the same space Jon is working in and I don't want to try to deconflict changes with so few days left.

**Comment by bethlakshmi** [comment]
Now on live
