### ISSUE TITLE
Event Schedule does not filter for conference 

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#515]
@burlexpo  - please review and comment

Right now - /scheduler/list - returns ALL the events - last years and this year's.

Right now, I posit that we want it to display only upcoming and current conference's events.

We do want current events, because if we have to edit something after the GBE conference has gone "Current" (say we want to update a last minute location change) - then we want it available.

**Comment by burlexpo** [comment]
Yes.  I agree.
