### ISSUE TITLE
Event List should have filter for conference.

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#516]
@burlexpo  - please review and approve.

We have a collection of lists based on event types:

/scheduler/view_list/
/scheduler/view_list/Class
/scheduler/view_list/Special
/scheduler/view_list/Show

all of which boil down to 1 function in the gbe/views.py

They should have a switch so we can specify what conference - I'd say it makes sense to tread this as a linkable GET request and do something like

/scheduler/view_list/Show?conference=gbe10

where "gbe10" is the slug for the GBE 10 conference

When the filter is omitted, it could display all events from all upcoming conferences.

I strongly feel that we want a way to to define ANY conference here (old conferences as well) because when an old conference is over and a new conference is in the bid process, we like to say things like "go here to see classes we've run in the past..." 

And I strongly feel it should be a bookmarkable URL, because that will play well with menus in django-cms. :)

**Comment by burlexpo** [comment]
I'm Scratch and I approve this product or service.

**Comment by jonkiparsky** [comment]
Basic functionality in place. Need to write tests.
