### ISSUE TITLE
Eliminate "print"

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#532]
There are calls to "print" in our code. This is incorrect. Find them and either turn them into log calls or just delete them.

**Comment by BenignCremator** [comment]
Find print statements in code (seems to mostly be ticketing related) and change them to logging statements.

**Comment by BenignCremator** [comment]
Have gone through the code and changed all of the print statements to logger.info.  Also dropped in a couple of logger.error statements at locations where error messages where generated.  Committing and asking for a PR.

**Comment by jonkiparsky** [comment]
I will be much more comfortable accepting pull requests once the PR for
GBE-531 (fixing the state of testing) is merged.
What you're looking for in that PR is, first, do the tests all pass without
error, and second, note the four tests which have been commented out. I
haven't been able to get these tests into a passing state, and I tried for
quite a while. I'm willing to leave them in the codebase commented out for
a month, in case anyone thinks they can fix them and wants to try. After
that, I'll remove them, since they're not doing us any good.

Once this is merged, it'll be possible to merge nontrivial pull requests
(including Hunter's most recent) and to start moving forward on features
again.

**Comment by jonkiparsky** [comment]
@BenignCremator see note on the pull request. There's a breaking test which needs to be fixed. There are a few ways the fix could be done, get in touch if you're not sure which way this should go.
