### ISSUE TITLE
Hard-coded constants in scheduler/views.py (2016 date)

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#546]
There is a hard-coded reference to February 21, 2015 in the volunteer_shifts function of scheduler/views.py
This is probably going to make some havoc sooner or later and should be replaced with a reference to a date that lives in a sane place in the database.

**Comment by jonkiparsky** [comment]
Same in calendar_view

**Comment by jonkiparsky** [comment]
Related to #488

**Comment by bethlakshmi** [comment]
I just searched views.py and this is now gone.

**Comment by jonkiparsky** [comment]
The date has changed, but there are still plenty of hard-coded dates to be rooted out from scheduler/views.py (and scheduler/functions.py as well). See for example the volunteer_shifts function.
