### ISSUE TITLE
Use Case for COSTUME DISPLAY BID

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#548]
Hi there,

This is me taking Mina's email and putting it A) some place where it is easier for you to find and refer to it, and B) in a format that's a little more useful.

If someone wants to bid a costume for the costume exhibit, the must have a profile.  If they click on 'I Want To... > ...Display a Costume" and they do not have a profile in the system yet, they are redirected just as if they had tried to bid an act and did not have a profile.

There is no application fee to bid a costume.

Assuming they have a profile or create one successfully, they are shown the following form:

Header - Displaying a Costume
Body - Thanks for your interest in our costume display.  Each year a team of creative volunteers puts together a remarkable collection of burlesque costumes in our Exhibit Hall.  The core of the team are BettySioux Tailor and Blitzen vonSchtupp, with the curatorial assistance of Miss Mina Murray.  

Costumes are selected for their historical significance, their 'wow' factor, their individuality (that is, we're not likely to take two similar costumes or more than one costume from the same person), and their craftsmanship.  Not all costumes that are offered are accepted.  You can check on the status of your submission on your personal homepage.

If you are offering a costume for display, it is your responsibility to make sure that the costume is on-site before 9:00am on Saturday morning.  Dropping it off on Friday is fine.  If you drop it off before 6:00pm on Friday, it is likely it will be on display during <I>The Bordello</I>.  Costumes will be available for pick-up after 9:00pm on Sunday evening.  It is your responsibility to pick up your costume and make sure all pieces are retrieved when you do so.  In rare cases and with previous arrangements, a costume can be picked up earlier on Sunday or shipped to you after The Expo.

If you have questions about The Costume Display, please drop a note to BettySioux Tailor at Costumes@Burlesque-Expo.com.  If you'd like to be one of the volunteers who puts up the display or one of the docents who helps educate people about the costumes over the weekend, please check our Volunteer Opportunities.

{BETTY - Here's the form}:

                                           / Contact Name:
All pulled from persona    -| Email:
                                           \ Stage Name (if any):

(required) Costume Creator: [small text field]
Help Text:  Please put the stage name, legal name, or company name of the creator, whichever is appropriate.  If multiple creators, please separate them with a comma.  If unknown, just put 'unknown'.

Name of Act: [small text field]
Help text: The name of the act for which you use the costume, if any.

Debut Date: [small text field]
Help text: Please enter the month and year the costume first appeared on-stage as "MM/YYYY" if known.  If unknown, just put 'unknown'

(required) Is the costume still being used on-stage?: [radio button Y/N]

<HEADER> - Costume Information:

(required) How many pieces are there? [Dropdown list with numbers from 1 to 20]
No help text.

(required) Please list all pieces:  [large text field]
No help text.

(required) Will you be bringing pasties?: [radio button Y/N]

(required) Dress Size [Dropdown list with numbers from 1 to 20]
HELP TEXT Measurements are in USA dress sizes.  A close approximation is fine.  This is to help us select which mannequin to use.

Is there anything special about the costume you want us to know?: [large text field]

(required) Please upload a picture of the costume: [upload]
HELP TEXT Please upload a portrait-oriented (taller than wide) image of the costume that shows it to best advantage.  This can either be in performance or displayed on a mannequin or model.

-------------------------------------

The form follows the usual "draft/submit" schema we use for bids.  That is, the submitter can either save a draft to come back and edit, or submit the costume for consideration.  

ONCE THE COSTUME IS SUBMITTED
It shows up on a list of reviews like acts do.  The page can be seen by members of the group "Costume Reviewers" (so we'll need to create that group) and shows up under the 'Special' menu for people with that privilege. There's also needs to be a 'Costume Coordinator' role which gets the approval functionality on the review page.

The submissions are listed like Acts are, with five columns: Performer;Act Title;State; Reviews; Action

Once an costume is accepted by the Coordinator, it gets displayed on the Costume Exhibit page (like the Vendor page).  The display is:

[Picture]
On loan from: [name of lender]

**Comment by bethlakshmi** [comment]
Notes from phone call w. Scratch, some things are redudant:
- bidding requires user to have login & profile and NOT persona
- the form will let them pick a persona if they have one (and make one if desired) - form above says "Stage Name" but I argue that we want to only hold Stage identity info in the persona, so let's reuse it.
- Date - is a text box, not a date box, so people can say unknown.
- Yes they can save a draft.

Also to do on this ticket:
- review panel
- roles for coordinator and reviewer 
- Costume exhibit page that is a direct imitation of vendor display page.

**Comment by bethlakshmi** [comment]
Further discussion today:
- I'm changing "Please upload a picture of the costume" to "Picture of the costume" so it will work in reviews
- I'm not putting email on the costume bid form, the user is forced to login, they can put their email in their profile like all other bids.

**Comment by bethlakshmi** [comment]
Question @burlexpo  

This isn't a blocker.
We now have a "clone" capability for historical bids.
Should Costume Bids be cloneable when a user is looking at their old conference bids?

I opted for - 
- historical view of bids shows bids from old conferences
- they are not editable in historical view
- they are NOT cloneable in historical view

Theory for now: - we don't have 2015 bids in the system yet, so extra effort for cloning is not urgent.

Last thought - we may not want accepted bids to be cloneable, we want the costume display to change every year...

BUT - if we want cloneable costume bidding - @burlexpo  - please put in a ticket to tell me so.
