### ISSUE TITLE
Act Tech Info Form looks bad

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#549]
The preview of act tech info submitted information looks pretty bad - it needs a header and better layout.

**Comment by jonkiparsky** [comment]
Closing this in favor of #568

**Comment by bethlakshmi** [comment]
Sorry for not being clear, but this is actually on a different page:

http://localhost:8282/acttechinfo/edit/397

the Act Tech Info data entry page.

Specific things that are wrong:
- There is a summary at the top - there is no header saying that it's a summary of the information they've submitted.
- the summary is a collection of forms, but no form sub-section headers show up.
- the text refers to 2015 and shoudl change to 2016
- on the data entry sections, there are headers, and they are in normal sized text, so they are completely overlookable and that sucks since the error text refers to the various sections.
