### ISSUE TITLE
Filter for all events is not right

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#556]
All event filter includes classes that have not been accepted.  I believe this is a bug in the original code and nothing recent, and we did not see it because we did not use this aspect of the filter last year.

example URL:

http://localhost:8282/scheduler/view_list/All?conference=GBE2016

**Comment by bethlakshmi** [comment]
There's a couple of other high priorities that I'd rather have help with, since I see them as blockers.  #555 and #554 are the ones I'm thinking of.

**Comment by jonkiparsky** [comment]
Wish I'd known that before I'd started in with this. I'll mark those to take on next.
