### ISSUE TITLE
refactor bid functionality to eliminate duplication

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#559]
Code around bids - submit, review, list, etc - is horribly WET. 
Refactor to gather common functionality and eliminate duplicated code.

**Comment by burlexpo** [comment]
Yup, we are all in agreement on this.  Feel free to start on it *after* the BurlExpo.  This is the sort of major code change I want to avoid between now and then.

**Comment by bethlakshmi** [comment]
done
