### ISSUE TITLE
What's the right way to organize files to be used in vagrant but not under config mgmt?

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#563]
Example, - I now have a copious quantity of variants of DB install scripts.
1 - is live today
2 - is test today
3 - is live when scratch couldn't edit CMS pages for no apparent reason (but very replicable) - 

In the future I want to continue to be evil to create freaky test conditions that are 1 or 2 + more Betty Evil.

Ongoing, I can see a desire for other test-like stuff that I'm not ready or able to check in, but that I want across branches.

In vagrant, I can easily find anything inside my "expo" main directory - but what do I do for stuff I want vagrant to ignore?  

is there way to add to vagrant's frame of reference?
or is the right answer to create folder (say "ignore/") and then add to the git ignore file?

**Comment by jonkiparsky** [comment]
The easiest thing to do for the moment would be to store that stuff in a directory that's not going to get blown away when you toss your current clone of the repository, and then just create a symbolic link when you do a vagrant up. 
To improve on that, I would locate that file in some standard place outside of the repo tree, and modify the Vagrantfile to look for it and link it up if found. Let's get on the phone and do some requirements gathering about this.
