### ISSUE TITLE
Act Tech info review is ugly as sin

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#568]
http://localhost:8282/reports/acttechinfo/view_summary/139

Example - (this is one of last year's shows, if you are using the test DB)

The easy fix would be to make the music link into something that says "Download This" and then downloads the file.  There really is enough real estate on this page, we don't need to get exotic.

**Comment by jonkiparsky** [comment]
Duplicate of #549

**Comment by jonkiparsky** [comment]
Copying text from #549 here:
> The preview of act tech info submitted information looks pretty bad - it needs a header and better layout.

**Comment by jonkiparsky** [comment]
This needs more detail here. It's not at all clear what I would do to close this ticket.

**Comment by bethlakshmi** [comment]
Could break this into separate tickets, but I recommend that it comes in in 1 pull request:
1 - put a conference chooser at the top (like bid reviews) and then have the list of shows at the top be the list of shows for the currently selected conference.   Right now, they show the list of EVERY show and that's more than most users will care about most of the time.

2 - change the music link so that only the file name is shown (crop off "/uploads/audio" which is the relative path w/in the server)

3 - crop the music link so that long files names show only the first 20 characters (example "01_Proud_Mary_Karaoke_With_Background_VocalsIn_the_style_of_Tina_Turner.mp3" becomes "01_Proud_Mary_Karaok..." - it should still download with the full title but it will make the table display readable.

4 - verify that all 3 fixes result in a table display that fits in the light-colored part of the current display.

5 - bonus - add the datatables *.js settings here, so that the headers are sortable.

6 - bonus - also consider #308 to make downloading better.

**Comment by jonkiparsky** [comment]
I see several different tickets here 1, 2&3, and 5 are new tickets, and #308 can be promoted to higher priority if desired. There's no reason to do these on one pull request, since they're all distinct work. Breaking them up will make both the work and review easier and faster, so that's what I recommend.

**Comment by bethlakshmi** [comment]
Closing now that we have:
#627
#626 
#625 
and 
#308 - which is an old duplicate of item 6
