### ISSUE TITLE
Fix registration reports for conference switching before conference

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#569]
http://localhost:8282/reports/staff_area
http://localhost:8282/reports/schedule/room
http://localhost:8282/reports/setup/room
http://localhost:8282/reports/schedule/all

**Comment by bethlakshmi** [comment]
Medium - now
High - if it's still open in Jan.

**Comment by jonkiparsky** [comment]
@bethlakshmi We need to make this more clear. From reading this, I don't know what is broken that needs fixing.

**Comment by burlexpo** [comment]
I took it down to Medium priority.  @jonkiparsky please tackle the High priority stuff now. @bethlakshmi, please document this issue better in case Jon has room to tackle it.

**Comment by BenignCremator** [comment]
I understood what Betty meant, and am tackling this now.  Already have it working for reports/staff_area and replicating the tmpl and filters across the rest of the requested views.

**Comment by BenignCremator** [comment]
Ok, to clarify, what I took Betty to mean is that the listed URLs need to be able to select which conference we are working on so that reports can be generated for either 2015 or 2016.  Right now, all reports are for Expo 2015, or include all info for Expo 2015 and 2016.  Need to add select conference button, and filters for the selected conference, so we can choose what Expo we are getting reports for.  @bethlakshmi, is that what you wanted?

**Comment by bethlakshmi** [comment]
Yes - exactly what Hunter is pointing out.

Every one of these reports gets ALL events - and every one should be changed so that the user can pick the conference and by default receive the current or most-close-to-now conference (upcoming, if not current).

Also of note:
http://localhost:8282/reports/schedule/all
Isn't working at all on my local vagrant install - it *should* download a CSV.  It doesn't.

http://localhost:8282/profile/manage
is just crazy ugly - it runs off the edge of the page due to the new formatting.  Should be a separate bug for that.
-------
Relevant to multi-conference work - the profile/manage and the schedule/all report ought to leave in users from previous years and show nothing for them if they aren't participating in any way (don't have tickets, aren't volunteering, aren't teaching, etc.).  I'd actually rather NOT screen out users, since it makes them hard to find, and being able to say "hi! you were with us a previous year, but we don't have anything signed up for you right now!" is a good thing at reg desk.

http://localhost:8282/reports/stuffing

is actually more broken than just conferences and likely needs it's own ticket.  The ticket refactoring make a connection between events and their associated sets of tickets and moved some of the information that we need to the event level.  The reports/stuffing report gives me all sorts of ticket info so I can get my reg desk volunteers stuffing packets, so each column of the report needs to be fixed so that the mapping is:

- person -> ticket item -> bpt event -> details about ticket.

Right now the report simply does not work at all - shows an error when you run it.


 http://localhost:8282/reports/badges/print_run
- is also broken in ways similar to reports/stuffing - the badges are labeled for "whole shebang", "conference", "vendor" and only the list of people that actually get badges (there's a boolean for that at the bpt event level)

For reference:
http://localhost:8282/reports

Lists what each report was supposed to do.

**Comment by BenignCremator** [comment]
First commit on this issue.  Got 2 of the 4 listed URLs working with the conference picker, reports/staff_area and reports/schedule/room.  Made the changes to reports/setup/room, but it did not seem to work properly, and sleep is sounding like a good idea.  Will tackle that and reports/schedule/all tomorrow.

**Comment by bethlakshmi** [comment]
Hi Hunter, how's this going.
If you're still chewing through this on the next meeting, I'm going to propose that:
- you give us a pull request on the 2 URLs that are done.
- we break the other 2 into 2 tickets, and I'll take the one you've worked on the least.  

This one is going to go hot mid-Jan.
