### ISSUE TITLE
Fix act info displayed on personal pane

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#572]
The workflow is if an act bid is accepted and assigned to a show the following shows up on the personal pane of the users associated with the act:
* a reminder to sign up for a rehearsal slot
* the current status of any act bids (draft, submitted, accepted, etc.)
* if accepted, to which show the act was accepted

Currently, if an act is accepted, what is displayed is
* that the act has been accepted (but not to which show)
* the reminder to sign up for a rehearsal slot

On the screenshot, we see the rehearsal reminder at top; under 'Act Bids' we see that the act "Try" has been accepted; and, at the bottom, we see 'Shows Mimi maShuga is appearing in:' is blank.

It is possible that the fixes to separate the 2016 show from the 2015 shows will fix this.

![screenshot 2015-11-18 09 05 51](https://cloud.githubusercontent.com/assets/5369404/11243031/a523d334-8dd3-11e5-9fe8-bb7c4caa56a4.png)

**Comment by jonkiparsky** [comment]
Will review this once current PRs are accepted.

**Comment by bethlakshmi** [comment]
please remember, everyone currently cast in a show is cast in a show in 2015!!!!

Before fixing this, Scratch, can you please make new shows for 2016 and cast people into them and remove them from the 2015 castings.  Otherwise we're trying to fix a weird data state that shouldn't exist.

**Comment by bethlakshmi** [comment]
I'm closing this, having verified that when the act is assigned to an upcoming show, the functionality works as expected.
