### ISSUE TITLE
Mystery edit bug is back

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#573]
I login to www.Burlesque-Expo.com, all is fine.
Whether or not I'm logged in, if I go to http://burlesque-expo.com/guests-2016/ all is still fine.
I click the 'edit' button and the content of the page vanishes (to me).
If I logout, the content of the page returns.

I can consistently reproduce this bug.

**Comment by bethlakshmi** [comment]
The other one is still not closed.  Would you mind adding to it so it's all in one place?

**Comment by burlexpo** [comment]
Closed in favor of #552
