### ISSUE TITLE
On webfactional transaction_cron_job logging is weird

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#578]
Because of where I'm running it (in the bin directory) the transaction cron job logging is weird - it logs to ~/bin/gbelogs/main.log instead of ~/gbelogs/main.log

I don't mind running it differently but need a recommendation.  I used trans_cron.sh in the bin directory to start the script, and I"m betting that's what's doing it.  

@BenignCremator  can you help or give a recommendation here?

**Comment by BenignCremator** [comment]
Ok, taking a look at this....  Um, we have three different layers of logging going on here.  Granted, we kinda need to, but going to deal with this from top to bottom.

First, on the cron job level, the process is kicked off with this cron statement:

*/1 * * * * cd ~/bin/;./trans_cron.sh >> $HOME/logs/user/cron.log 2>&1

So it is cd'ing into bin and running the shell script from there, so anything that takes a relative path starts from $HOME/bin instead of / or $HOME.  Changing that to use explicit paths.  And this is probably where the path problem begins....

**Comment by BenignCremator** [comment]
Looking at the log made by the cron job shows that the output is not timestamped.  The error that was logged there looks out of date, and the file it claimed was not there was, and the transaction logging has been running, so the error was not describing anything current.  Wiping the old log, and running the output through stramper to give errors a timestamp.  We may wish to do that to all of our cron jobs.

**Comment by BenignCremator** [comment]
Looking at ~/bin/trans_cron.sh and its logging.  I do not believe that we need logging at this layer.  The logging in cron gives us printed output from the shell script, so we log shell errors, and the python script itself seems to be logging as well (in the wrong location, but it is logging useful information).  This appears to be attaching to the python interpreter and logging its messages, so not much useful output (a bit is quoted below the bar).  Also, this script is being executed in a weird way, from the script:

/usr/local/bin/python2.7 ~/webapps/gbelive/expo/manage.py shell < ~/webapps/gbelive/expo/transaction_cron_job.py &>> ~/logs/user/transaction_cron_job.log

So we have an executable script being read into a shell as text from another script.  We do not need this many layers of redirection, am going to see if I can simplify this down to only one.

------------------------------------------------------------
 Python 2.7.9 (default, Dec 14 2014, 05:14:54) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)

>>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> Executing Cron J
ob Script....
>>> 
>>> >>> 0 transactions added to the system.
>>> 
>>> >>> >>> >>> >>> >>> >>> >>> >>> >>> Python 2.7.9 (default, Dec 14 2014, 05:14:54) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)

>>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> Executing Cron J
ob Script....

**Comment by bethlakshmi** [comment]
Sounds great.

I set up that indirection because I had trouble running it directly.  What
the trouble was... i have no guess anymore.

**Comment by BenignCremator** [comment]
Oh, wow....  This just gets deeper.  So the environment that cron runs is highly minimal.  This is normal.  However, #! is not finding the python interpreter.  The file is there, I can execute it, but it does not appear to be listed in /etc/shells, so the exec kernel function is not allowing python scripts to load directly.  Added python to the cron line, explicitly calling the script.  This is now working, however, the amount of logging done into ~/logs/user/cron.log is excessive.  Four line every minute, even if there are no transactions or errors.  Altering script to only print output when something happens, so we only log activity or errors.

**Comment by BenignCremator** [comment]
Ok, that is done.  However, the process itself is logging into main.log, as part of the logging inf from the rest of the GBE code.  So, every minute, 40 lines of code is added to mail.log, because at the INFO level, all imports are logged.  Changing the log level to ERROR.

**Comment by BenignCremator** [comment]
Ok, that is done.  Am now going to monitor this to make certain everything is functioning.  Seeing no errors....  Yet....

**Comment by bethlakshmi** [comment]
A good cross check is to also go here:

http://www.burlesque-expo.com/ticketing/transactions

(you must be logged in)

And verify that the sync happened recently.  The time stamp is updated when
the bpt function is called.

Right now there are 246 transactions. That number doesn't go up every day,
but if we get purchases in BPT it should go up.  That's the most obvious
example that all is well. :)

**Comment by BenignCremator** [comment]
On 11/21/2015 05:26 PM, bethlakshmi wrote:

> A good cross check is to also go here:
> http://www.burlesque-expo.com/ticketing/transactions

I am not able to access this on the website.  I was able to yesterday. 
The drop down menus are also not working, but were yesterday.  Did 
anything on the site change in under 24 hours?  Everything else seems to 
work if I type in the URL by hand, but that is not the fun way to use a 
website.  The good news is that the transaction cron job is running 
cleanly, logging into the GBE logs, and seems to be working nicely.  So, 
yay that.  Anyone experiencing anything else odd?

Hunter

**Comment by burlexpo** [comment]
As of 10:26pm, the live site is fine -- drop down menus work as they are supposed to.

When I go to http://www.burlesque-expo.com/ticketing/transactions I get the page I'm supposed to get.

**Comment by BenignCremator** [comment]
On 11/22/2015 10:27 PM, Scratch wrote:

> As of 10:26pm, the live site is fine -- drop down menus work as they are
> supposed to.

> When I go to http://www.burlesque-expo.com/ticketing/transactions I get
> the page I'm supposed to get.

Ok, something wrong with this boot, then...  Will try a different 
system.  Thanks.

Hunter

**Comment by BenignCremator** [comment]
Ok, still waiting for a transaction to process for positive evidence that this change is working.  Can not confirm that the transaction is working until a purchase is made, and either it generate an error or logs a success.  Worse, there is not a page that can list pending transactions so I can see that the code is not failing silently and processing nothing even when there is something to process.  Last, reading the logs on this has left me wanting to refactor logging so we either have multiple levels or types of info logging, or can specify a verbosity level.  Not until March 2016....  Or 2017.

**Comment by BenignCremator** [comment]
W00T!!!  Transaction incremented today without poking, prodding, or triggering the transaction script!  I now have actual proof that the transaction sync is working properly!  Closing this issue.
