### ISSUE TITLE
Personal schedule per conference

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#581]
I believe we pulled personal schedules from display so as not to display old conference info.

We need to return them to being functional - I suggest:
- a personal schedule is available for any "current" and "upcoming" confernces, that we organize them in blocks per conference and then by day:
 - conference 1 (current first, upcoming second)
   - schedule item 1
   - schedule item 2 
 - conference 2
   - schedule item 1... etc.

~~Also - ASAP, we should pull the text saying that your personal schedule is appearing... it isn't...~~

**Comment by bethlakshmi** [comment]
Putting to high to get attention
@burlexpo - could be a medium?

**Comment by burlexpo** [comment]
Yes, this should happen.  I like the design.

>Also - ASAP, we should pull the text saying that your personal schedule is appearing... it isn't...

Did this happen? If not, should it be broken out into its own ticket and taken care of?

**Comment by jonkiparsky** [comment]
Yes, have broken this out as separate ticket.

**Comment by jonkiparsky** [comment]
Done (#605)
