### ISSUE TITLE
Act Tech Review form loses header info on submit

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#585]
When a user fills in their Act Tech info (eg http://localhost:8282/acttechinfo/edit/419) and hits the submit button, their act info disappears from the top of the form. 

To reproduce: create an act, mark it as submitted, and accept it into some show. Navigate to the acttechinfo/edit page. Note that header information is present. Fill in some fields in the tech info. Save changes. Note that information about act - Title, Description, etc - is now blank

**Comment by bethlakshmi** [comment]
Closed with #817
