### ISSUE TITLE
General Updates and Enhancements to the Vagrant file

### ISSUE THREAD

**Issue by BenignCremator** [bethlakshmi/GBE2#591]
The Vagrant file is not yet perfect, and this issue is to track general improvements, updates, and enhancements to it.

**Comment by jonkiparsky** [comment]
This ticket is not ready to work. Please specify what improvements should be made.

**Comment by BenignCremator** [comment]
Add the line:

  chown -R vagrant:vagrant /home/vagrant

between these lines in the Vagrantfile:

  cp /vagrant/aliases /home/vagrant/
  echo "source /home/vagrant/aliases" >> /home/vagrant/.bashrc

**Comment by BenignCremator** [comment]
Add this line to the aliases file:

alias runserver='/usr/bin/python /vagrant/expo/manage.py runserver 0.0.0.0:8111 &> /vagrant/expo/logs/runserver.log'

**Comment by BenignCremator** [comment]
Add this line to the Vagrantfile:

  mkdir /vagrant/expo/logs; chown vagrant:vagrant /vagrant/expo/logs

**Comment by BenignCremator** [comment]
Add file to reset_db.sql to /home/vagrant and make it executable in the Vagrantfile:

  mysql -u root -proot -e "DROP DATABASE IF EXISTS gbe_dev"
  mysql -u root -proot  -e "CREATE DATABASE gbe_dev"
  mysql -u root -proot  -e "USE gbe_dev"
  mysql -u root -proot  -e "GRANT ALL ON gbe_dev.* to 'django_user'@'%' IDENTIFIED BY 'secret' WITH GRANT OPTION"
  mysql -u root -proot  -e "GRANT ALL ON gbe_dev.* to 'django_user'@'%' IDENTIFIED BY 'secret'"
  mysql -u root -proot  -e "GRANT ALL ON test_gbe_dev.* to 'django_user'@'%' IDENTIFIED BY 'secret'"
  mysql -u root -proot  -e "flush privileges"

  if [ $# -eq 1 ]
  then
      cat $1 | /vagrant/expo/manage.py dbshell
      expo/manage.py migrate --fake gbe 0001
      expo/manage.py migrate scheduler
      expo/manage.py migrate ticketing
      expo/manage.py migrate gbe
  fi

**Comment by BenignCremator** [comment]
Have added a database reset and restore script, can use any appropriate SQL file you choose.  Have done a good bit of functional testing, and it all works, but the tests are not exhaustive, so I still expect some bugs.  Also, there are some.... quirks.  Since Django keeps its database settings in local_settings.py, I have included a way to filter it for settings.  However, there is also a command line way to do the same thing, for use with test scripts and the like.  However, because Django pulls the database and user information from the local_settings.py file, it is not able to run migrations with custom database or user information without also altering the settings file.  Usually not an issue, but important to know about.  With the additions to the Vagrantfile and the aliases, this concludes this ticket.  Further work on the script, etc, should be in other tickets.  Issuing PR.
