### ISSUE TITLE
Remove cue sheet from Newcomer's Showcase Act Tech Form

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#592]
Remove the Cue Sheet (both form and example) from the Act Tech form for acts booked into the Newcomers Showcase.

**Comment by bethlakshmi** [comment]
This is done - was there something different than this that you were looking for?

http://gbe2016test.gbeadmin.webfactional.com/acttechinfo/edit/496

**Comment by BenignCremator** [comment]
On 12/06/2015 10:36 AM, bethlakshmi wrote:
> This is done - was there something different than this that you were
> looking for?

That looks good, we can close the ticket on it.

Hunter

**Comment by jonkiparsky** [comment]
Sorry, I understood from Hunter's review comments that this had not been done. Closing.
