### ISSUE TITLE
Eliminate lookup by show name in act tech info edit flow

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#593]
The act tech info edit view  (/acttechinfo/edit/389) does a lookup by show name, which fails if show name is duplicated. This lookup should be done by show ID, so that show names are not forced to be unique. 

See issue #587 for the details of the server error which revealed this issue.

**Comment by bethlakshmi** [comment]
show = get_object_or_404(
                Show,
                title=request.POST['show']).scheduler_events.first()

**Comment by bethlakshmi** [comment]
sigh

**Comment by jonkiparsky** [comment]
see also #353 for similar problem

**Comment by BenignCremator** [comment]
BLOCKER:  Went to URL listed in original ticket, altered some data (changed a backlight color from white to OFF), and pressed submit.  Error when submitting an edit:
MultipleObjectsReturned at /acttechinfo/edit/389
get() returned more than one Show -- it returned 2!

Is this is the same error that this ticket covers in a different but dependent location?  Either way, submit is broken, and I can not approve until there is basic functionality in standard cases.
