### ISSUE TITLE
Make Show Cue Sheet updatable

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#594]
I put the switch into shows that we discussed - there is now a 'cue_sheet' value that can be set within a Show.

It needs a bit more cleanup:
- the Show create form should include this value
- the Show EDIT form should NOT include it (if the show is set up, people may have started responding and making up cues for us)

It can be done now via /admin, so there is a workaround, and we only need this once per show... so I say low priority.

**Comment by burlexpo** [comment]
/Has /this been done for the current shows? Not has the functionality on 
this ticket been created, but are the current shows all configured so 
that we get the right tech info for each show? @BenignCremator?

**Comment by bethlakshmi** [comment]
The Act Tech form functionality is on test.  The code is not on live yet.
I'd like someone besides me to give a thumbs up on pushing to live - if you want to take a look at test based on the release notes I sent out and OK it, that'd be fine by me.

**Comment by bethlakshmi** [comment]
Now that I've updated the master, I also went in and fixed the current shows to do the right thing.  Tested with 2 hijacked users (a bordello performer and a newcomer)

**Comment by bethlakshmi** [comment]
https://github.com/bethlakshmi/GBE2/wiki/Cue-Sheets-for-Shows 

instructions in case I am hit by a bus

**Comment by bethlakshmi** [comment]
deprecated by act tech refactors
