### ISSUE TITLE
Getting to Ordering Acts is almost secret

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#598]
I think this every time I have to work with it.  It was a last-minute add-on last year and it kind of shows.  If I didn't know how to get to the shows, I'd never figure it out.  Let's revisit the dashboard on this after BurlExpo10.  Also, when you hit the 'submit' button after ordering the acts, you're taken back to your home page instead of shown the results of the submit, which is odd.

**Comment by bethlakshmi** [comment]
It would be pretty easy for me to make an addition to the special menu if there's a link you'd like me to link it to, throw it here...

Redirecting shouldn't be hard either, but that one particular line of code isn't in my head...

**Comment by burlexpo** [comment]
Appreciate it, but since I only need to manage four shows and I've done two of them already, it can wait until March.  And since this is one part of a UI redesign I'd like to do, it can wait until March...
