### ISSUE TITLE
Narrow the "Volunteers Needed" Column

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#608]
Volunteer Management runs off the edge of the screen.  This can be fixed if we narrow the text field associated with the "Number of Volunteers" field to 3 characters and (possibly) change the label to "No. Vols." or something similarly abbreviated.  I'd use "# vols" but I don't know if the pound sign/number sign/ hashtag is a reserved character.

![screenshot 2015-12-12 21 24 22](https://cloud.githubusercontent.com/assets/5369404/11765080/21ad46dc-a117-11e5-96dc-18b6da69abd7.png)

"Volunteers Needed" can split across two lines to avd excsv abbrvtion. Can also narrow Duration.

**Comment by bethlakshmi** [comment]
Same as #463
