### ISSUE TITLE
Problem with Django Hijack tag

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#610]
The problem of the django notification tag being an invalid block tag is back on test and @bethlakshmi  has no clue how to fix it since she can't restart the installation from scratch on test without it being a much bigger project.

@bethlakshmi removed the tag from the base.tmpl to fix the problem so that @burlexpo could review other stuff - but she needs help figuring out what's missing.  It's consistently replicatable on test if you copy back the current git-drop code:

cp -r ~/git-drop/GBE2/expo/ ~/webapps/gbe2016test/

I'll come back on any page load.

It works great on her local machine so she doesn't think it's a bug in the master.. it's an inconsistency on the test account.

**Comment by bethlakshmi** [comment]
Thank you!

**Comment by jonkiparsky** [comment]
Took a look at this. Wasn't able to get it working, but I did notice that I wasn't able to start up the django shell, which is a problem. @bethlakshmi have you noticed this?

**Comment by bethlakshmi** [comment]
yes.  The script to call the django shell is not:

    ./manage.py shell

it is:

   python manage.py shell
