### ISSUE TITLE
Can't reject classes

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#611]
From the Class Review page, if a privileged reviewer selects 'Reject' and clicks submit, the change of status doesn't get saved.  This is *not* true for other statuses (Wait list, accept, etc.)

Scandal and I have both tried, and gotten the same results.

@bethlakshmi , if you can't tackle this ASAP, can you assign it to @jonkiparsky ? This is a major blocker and something I'd like to see fixed ASAP.

**Comment by jonkiparsky** [comment]
Have pushed a fix and test. @bethlakshmi - ready for your review.

**Comment by bethlakshmi** [comment]
Hot fix applied live.
