### ISSUE TITLE
Two accounts with the same email?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#615]
I thought we had something in place which prevented someone from registering the same email address twice.

I was contacted by Egypt Blaque Knyle and so went to look up her account using http://burlesque-expo.com/profile/manage.  I searched for "Blaque" and discovered she has two accounts which use the same email address (account names: egyptblaqueknyle and eegyptt415).  As far as I can tell, she has done all of her work through eegyptt415.

**Comment by jonkiparsky** [comment]
I thought I'd deleted that extra account when we decided to uniquify email names. Deleted.
