### ISSUE TITLE
Staff Lead appears twice on page

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#630]
Why? This may have something to do with the way I created the event(s)?

http://burlesque-expo.com/scheduler/details/403

![screenshot 2015-12-20 20 21 56](https://cloud.githubusercontent.com/assets/5369404/11921577/9d51f510-a759-11e5-99f3-26965a5f8311.png)

**Comment by bethlakshmi** [comment]
I see it post-update, so it's real.
Looking more now...

**Comment by bethlakshmi** [comment]
Hm... OK, I verified that:
1 - the double staff lead comes from the fact that Jennie is scheduled in two sessions of the Athenaeum, so she's staff lead "twice".

2 - I believe this comes from the fact that our data selection for this is trying to get "distinct" information and failing (expo/schedule/models - the function roles()).

The quick fix is - remove Jennie as a staff lead from one of the two scheduled sessions.

The better fix is - we fix the code for the roles() function to really be distinct.  ... working on it now.

**Comment by jonkiparsky** [comment]
@bethlakshmi - Code looks good, but I'd really like to see a test before merging.
