### ISSUE TITLE
Merchant fees not going through

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#633]
I was contacted by a vendor (Lush Beads) who couldn't submit her application.  When she did, she was told her fee wasn't paid.  I compared the email she used on BPT with her account on the site and -- sure enough -- they were different.  I updated her profile to reflect an accurate payment address.  Then I synchronized ticket transactions.  I then hijacked her account and tried to submit the application, only to get the error that her application fee had not been paid.

**Comment by bethlakshmi** [comment]
The BPT side API token was unintentionally deleted.  We replaced it and transactions started syncing again and problem was solved.
Had been broken since 12/8/2015
