### ISSUE TITLE
Volunteer Allocation page: Convert to tabular display

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#655]
Scrap current display Instead, show a table of volunteers who are either Interested (selected this type of opportunity) or Available (Selected this time slot) or both. Table columns: 
[Display Name, Interested, Available, Conflict, Review, Allocate]

Display name: comes from user profile
Interested: User indicated interest in this flavor of volunteer opp
Available: User indicated availability for this time slot
Conflict: User is booked for some other event in this time slot
Review: -> Review Volunteer Bid
Allocate: -> Create Allocation page

Table should be sortable on Interested, Available, Conflict. By default, sort by Available, then Interested, then Conflict. (so the clusters are, in descending order, I+A, I, A, with any conflicts at the bottom of the table, regardless of interest or availability)

**Comment by burlexpo** [comment]
@jonkiparsky Any movement on this? I didn't realize it hadn't been labeled when it was created 3 weeks ago.  Should have been High Priority.  Might actually still be useful for this year (*definitely* useful going forward), but only if we can get it up on the live site by Tuesday or Wednesday.

**Comment by bethlakshmi** [comment]
look at /gbe/templates/gbe/bid_review_list.tmpl

fpr a JS example.  JS libraries are already in base.tmpl

**Comment by bethlakshmi** [comment]
Notes:  Filter order is Conflict (N), then Interested (Y), then Available (Y)
And we do not show volunteers who are NOT available in the table.

**Comment by burlexpo** [comment]
I created a volunteer tailor-made to show up during the Rhinestone Revue (someone who is both interested and available for volunteering during the event). 

I went to the Rhinestone Revue page (http://burlesque-expo.com/scheduler/edit/GenericEvent/2591) and created a volunteer opportunity:

http://burlesque-expo.com/scheduler/edit/Show/2514

- **Title**: Tech Crew
- **Volunteer Type**: Tech Crew
- **#**: 3
- **Duration**: 01:30:00
- **Day**: Fri, Feb 10
- **Time**: 08:00 PM
- **Location**: Theater
- 

When I click on the **Action** **_Staff button_**, I'm shown a 3 lists of volunteers: All Volunteer; Interested Volunteers; Available Volunteers. 

This ticket was supposed to show me

Volunteers who are both Available **and** Interested    _then_
Volunteers who are Available    _then_
Volunteers who are interested   _then_
All volunteers

The three existing columns do seem to be winnowing people down, but I don't see the first category (Volunteers who are both Available and Interested) anywhere.
