### ISSUE TITLE
search on act/reviewlist only picks up performer name (not act name)

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#661]
on http://gbe2016test.gbeadmin.webfactional.com/act/reviewlist, type "La Vie" into the search filter box. Notice that the act titled "La Vie en Rose" does not come up. 
Not sure if this is intentional, but it's not very helpful.

**Comment by bethlakshmi** [comment]
Actually it does pick up that act - navigate to page 3 of your search results.  Ruby Solitaire's act "La Vie On Rose" is on the 3rd page, because of where the perfomer sits in the alphabet.

**Comment by jonkiparsky** [comment]
Hm. True. I see what got me - the search includes the Action column, so it finds "Review" in every row. 
Okay - that's wrong, but probably not wrong enough to worry about.

**Comment by burlexpo** [comment]
It's got nothing to do with the action column.  You used the search function incorrectly.  

You entered a search string without quotes so the search returned every incidence of "La", "Vie", "en" or "Rose" (for example, it matched the "la" in the middle of the word "splash" in the review of the first act).  

If you type '"La Vie en Rose"' into the search box, it returns exactly one match.

**Comment by jonkiparsky** [comment]
> It's got nothing to do with the action column.

This is incorrect. The inclusion of the action column is why the relatively unusual string "vie" didn't reduce the search. And this is incorrect behavior for a search box - it should not include this column, precisely because it produces incorrect behavior. But again, not worth worrying about, which is why I closed this issue.
