### ISSUE TITLE
Standards: testing user-uploaded files

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#669]
It is not clear how we should test parts of the code which involve files uploaded by the user (ie, audio files). Specific use case: to deal with the code added to address AC-308, we need to have audio files in the uploads/audio directory. What is the right way to create those for tests? 

Definition of done: create a reasonable example of a test which shows a clean way to produce an Act with an associated audio file. This audio file might be a pre-existing dummy object in the test harness somewhere, but should not start out in the uploads/audio directory, and should end up there. Bonus points for a solution of the form

```
act = ActFactory(audio= [something])
```

**Comment by bethlakshmi** [comment]
Did this with the FilerImage files - see the tests for vendor create/edit and persona create/edit
