### ISSUE TITLE
Testing operations touching the file system

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#670]
We have no existing patterns for testing operations which change the state of the file system (as opposed to changing the state of the database). For example, GBE-308 commits code which generates and moves files under the MEDIA_ROOT tree. 
We need a good standard for writing tests of this sort of functionality.

**Comment by bethlakshmi** [comment]
I basically ended up doing this - I found a decent way to mock file upload in tests, and to redirect the test to the chosen test file for upload.  I used this in several places, I think I even included the audio file manipulation when we had some bugs there last year.

It's not formalized, but there's enough in place that is consistent than can be copied from.
