### ISSUE TITLE
Reports: Volunteer shifts have also gotten attached to special events

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#677]
This is a gap in the original report:

http://localhost:8282/reports/staff_area

Last year we used "staff areas" as holders for collections of volunteer work managed by a staff member.
We also had "shows" that had collections of volunteer shifts.

Now - we also have a fairly noteworthy case for a special event - The Athenaium - which has ongoing volunteer shifts.  I suspect it's a special event, because @burlexpo  wants it to show up in the Special Events listings (with Tea party, pool party, etc) - so it makes sense... but we don't show special event in this report... and so the person running that area (Jenny) can't see who her volunteers are - the way other staff members can.

**Comment by bethlakshmi** [comment]
http://localhost:8282/reports/setup/room?conf_slug=GBE2015&submit=Select+conference

The switch part looks good... until I dig into the data, and find out that when the GBE 2015 switch is on, we are missing anything for Feb. 22.  Many rooms on this list were scheduled for both days, (Sat and Sun), and we display schedules for both:

http://gbelive.webfactional.com/reports/setup/room

shows the data I'm working with, and I know we have the 22nd in there.  I have trouble believing my data locally is different...

**Comment by burlexpo** [comment]
This is also true of Drop-in classes which are there own category, but which shoul show up on the Special Events calendar.  They should **not** show up on the Conference calendar (not that they currently do), because we have enough people who confuse the Drop-in classes with The Conference.

**Comment by bethlakshmi** [comment]
Fixed this
