### ISSUE TITLE
Automatically create show-related Volunteer shifts when scheduling a show.

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#679]
While some volunteer positions are fluid from year to year, certain show-related positions are always going ot be the same.  It would be great if when a show was scheduled, those volunteer positions were automatically created.  The scheduled time could be the same as the show (maybe starting :30 minutes earlier than the show), and the name of each position should be of the format "Show name - Position", i.e., Rhinestone Revue - Follow Spot

**Position/Staff Area/Min./Max.**
Lighting Board/Tech Crew/1/1
Follow-spot/Tech Crew/1/1
Sound Eng./Tech Crew/1/1
Playback/Tech Crew/1/1
Stage Mgr/Stage Crew/1/1
Stage Kitten/Stage Crew/2/4
M.C./Performer/1/2
Usher/Security/3/6

Agreement in meeting:
- it happens when a show is scheduled (not on Show creation)
- When a show is edited... there is NO change in these events - each event would have to be manually updated
- It DOES prevent duplicates - if the show already had (for example) a playback tech, then the new playback tech window is NOT added.

**Comment by bethlakshmi** [comment]
@jonkiparsky - Hey there, I've been trying to figure out why some machine's break on the cleanup for this ticket, but it's slow going.  Where are you on the rest of the work for this ticket (the post-cleanup stuff)?

**Comment by bethlakshmi** [comment]
I created a copy function, instead, which I think is as good or better, since you can keep it the same or pick only what you want when you copy.
