### ISSUE TITLE
Act Tech info 500 error

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#681]
http://gbelive.webfactional.com/reports/acttechinfo/view_details/<id for the show>

Is giving me 500 errors.  I'm not sure why, or whether it's new... but this is urgently broken right now...

I have not checked whether the current master code has the same problem yet... live is out of sync with the current master.

**Comment by bethlakshmi** [comment]
ok... calming down a bit... my local master doesn't have this problem and I just updated gbe test, and cannot cause the 500 error.

So, current master cannot replicate and given that we've done a bunch of work in this area, that makes some sense... I will close this if the push to live fixes the problem.

**Comment by eclecticmagpie** [comment]
When will the push to live happen?  Since Scratch told me that my issue #683 wasn't important because this feature provides that functionality (which is wrong, but that's a different question), having both #683 AND #681 together is a showstopper for me.

**Comment by burlexpo** [comment]
Possibly tonight; probably tomorrow.

**Comment by bethlakshmi** [comment]
I pushed the fixes @burlexpo was talking about to live now... we have found 2 problems #691 which came in with the new code and this is still alive and well.  I have a fresh copy of the data on my local and can now see the bug locally... working on it now.

**Comment by bethlakshmi** [comment]
Fix has been sent via pull request on this one.

**Comment by bethlakshmi** [comment]
Closed on live as well.
@jonkiparsky and I are on fire. :P
