### ISSUE TITLE
Add "Sound" as Staff Area

### ISSUE THREAD

**Issue by eclecticmagpie** [bethlakshmi/GBE2#685]
It would make scheduling sound engineers easier if they appeared in a separate staff area.  There are a number of volunteers signed up whom I don't know, and thus I don't know whether they are engineers or not.

I don't expect this for this year, and have prioritized it accordingly.

**Comment by eclecticmagpie** [comment]
Hmm.  Poking around a bit, I see that a number of sound engineers are already scheduled, for both rehearsals and performances.  I thought that that was my job -- if not, great, and I guess I don't need to have Sound as a Staff Area.  

I can't easily tell whether ALL sound engineer slots have been filled or not.  So I don't know whether I need to schedule myself in, or not, or whether I should still be recruiting for more engineers, or if we're all set.

**Comment by burlexpo** [comment]
Replied privately.

**Comment by bethlakshmi** [comment]
Can we close or should this stay open?

**Comment by eclecticmagpie** [comment]
I still think it's a good idea, but it certainly deserves to be discussed
and chewed on a bit, after the expo.  So I'm OK with closing it, and either
reopening it or submitting a new one if we decide that it's a thing that
would improve the process.

Mike Bergman
www.prospecthillforge.com
www.vintagedancers.org/teadance
www.isebastiani.com
reply-to: eclectic@mit.edu

**Comment by bethlakshmi** [comment]
So... a staff area is a staff area.
If you make a Generic Event called "sound" and make it a staff area.. then it's a staff area.  I don't see a code change here.
The place to do what I am talking about is:

on Scheduling -> Generic Event (http://gbelive.webfactional.com/scheduler/list)
Go to the link at the top to create a new event (http://gbelive.webfactional.com/create_event/GenericEvent) 

That gives you the place to make a staff area - just set the "Type" to staff area.

The problem I see is that I have no easy way to let you move volunteer opportunities that are currently in the shows to be in the newly made staff area.  You'd need to delete the current setup, build it again in the area, and then manually reassign the volunteers.

**Comment by bethlakshmi** [comment]
@burlexpo - the sketchy instructions I just wrote are also what you are looking for based on the earlier conversation tonight.

**Comment by burlexpo** [comment]
> The problem I see is that I have no easy way to let you move volunteer opportunities that are currently in the shows to be in the newly made staff area. You'd need to delete the current setup, build it again in the area, and then manually reassign the volunteers.

That's only one of the problems.  The other problem is that we want volunteer shifts to show up on multiple reports.  In this specific case, Mike wants to see all of the 'Sound' related shifts in a single report, but someone else might want to see all of the shifts related to The Main Event (which includes sound people but also lighting, stage hands, etc.) in a single report.  If we create a Sound staff area and the create the volunteer shifts attached to that Staff area, they're no longer attached to a show.

**Comment by eclecticmagpie** [comment]
I think I can get what I want a different way, and it definitely doesn't need to take up your limited time this year.

**Comment by bethlakshmi** [comment]
I think we managed @eclecticmagpie's needs this year with the changes to search on events and staff reports...  if not, I'll need this to get refined in a new ticket on what is missing.
