### ISSUE TITLE
Build/Strike Staffing Report shows last year's (2015) staffing schedule

### ISSUE THREAD

**Issue by eclecticmagpie** [bethlakshmi/GBE2#688]
I'm not sure what *should* be there, but this is confusing.  Perhaps an unpopulated 2016 grid?
I tried adding myself as a volunteer and "assigning" me, to see if that would create an appropriate grid, but it didn't.

**Comment by eclecticmagpie** [comment]
On closer examination, it looks like the 2016 build assignments appear **within** Rhinestone Review, rather than Build/Strike.  We can work with this, I suppose, but it's a weirdness.

**Comment by bethlakshmi** [comment]
#569 
I hope to have this up this weekend - it was fixed last weekend and I generally do a push on saturday morning.
