### ISSUE TITLE
Staffing report for shows mixes 2015 and 2016 reports

### ISSUE THREAD

**Issue by eclecticmagpie** [bethlakshmi/GBE2#689]
Not all of the 2015 reports are clearly labelled 2015 in the title.
Not all the 2016 reports are present -- in particular, Newcomer's Showcase is missing. Either that, or it shouldn't be there at all -- was this replaced with Sunday Showcase?

**Comment by bethlakshmi** [comment]
This is a duplicate.  #569 has been fixed but not pushed.

**Comment by bethlakshmi** [comment]
code is now updated, I'm having a known 500 error issue on my account that I am now looking into.

**Comment by burlexpo** [comment]
Yesm "Newcomer's Showcase" is now "Sunday Showcase".
