### ISSUE TITLE
http://burlesque-expo.com/ internal server error

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#690]
Yes.  I know.  I'm working on it.

**Comment by bethlakshmi** [comment]
I can't explain this.  There was an error in expo/expo/wsgi.py.

I copied the previous wsgi.py back.  
Restarted the server.
It was fixed.
I compared the new master copy and the old copy that worked - no difference.
I copied the new wsgi.py from the current master back on.
No problem.

**Comment by bethlakshmi** [comment]
It's fixed, but I can't explain why.

**Comment by jonkiparsky** [comment]
Spooky. Don't like.
