### ISSUE TITLE
500 error on http://www.burlesque-expo.com/reports/staff_area/139

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#691]
Every staff area report now has a 500 error.
Consistent now on my local master, gbe2016test, and gbelive

This worked 6 days ago when I pulled.

error = FieldError at /reports/staff_area/367

Cannot resolve keyword 'conference' into field. Choices are: contained_events, container_event, eventitem, id, max_volunteer, resources_allocated, schedulable_ptr, starttime

**Comment by jonkiparsky** [comment]
Looks like the code is trying to check the conference on a scheduler.Event
Looking for the line now

**Comment by bethlakshmi** [comment]
I see the lines... they are unnecessary.
The staff event did not need to be filtered by conference, the leadup page was filtered by conference.
The staff event should show any staff event that it's asked to show.

**Comment by jonkiparsky** [comment]
If you make a fix, I'll review and merge

**Comment by bethlakshmi** [comment]
awesome.  Testing now...

**Comment by bethlakshmi** [comment]
@jonkiparsky - thanks Jon - all yours.  pull request is ready.

**Comment by bethlakshmi** [comment]
Now pushed by extremely fast team work to live as hot but clean fix.
