### ISSUE TITLE
Number of acts displayed on Show Schedule Summary and Number of acts shown in Act Ordering tool not the same

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#694]
This makes me nervous.... but I've reassured myself that I'm not actually missing any accepted acts.

If I look at The Sunday Showcase on http://burlesque-expo.com/scheduler/list I see there are 20 acts (see image).
![screenshot 2016-01-30 12 52 16](https://cloud.githubusercontent.com/assets/5369404/12697412/7599fe20-c750-11e5-849d-36dfd223078b.png)

But when I go to put the acts in order (click on _edit_ than click on _schedule acts_ to get to http://burlesque-expo.com/scheduler/acts/The%20Sunday%20Showcase) I can see there are only 17 acts on the list. (see image)
![screenshot 2016-01-30 12 56 38](https://cloud.githubusercontent.com/assets/5369404/12697423/c9b59c44-c750-11e5-87e0-d3a763b4f0e9.png)

When I look at http://burlesque-expo.com/scheduler/details/365/ I see 17 acts; when I look at http://burlesque-expo.com/act/reviewlist and search for "The Sunday Showcase" and sort by "State" I get **17** accepted acts, so I don't think I'm missing anyone.  This may be looking at last year's info?

**Comment by jonkiparsky** [comment]
@burlexpo Looking at this now.

**Comment by jonkiparsky** [comment]
Looks like the "20 Acts" is counting all acts allocated to the show. My hunch is that this includes three acts which are not in "accepted" state, but I'm having trouble signing on to the live server to verify this.

**Comment by burlexpo** [comment]
OK -- I can live with this.  It's labeled Medium priority and the deadline is "Post-Expo".  It's not pressing but I wanted to get it logged.  What *is* pressing (and probably related) is #672

**Comment by bethlakshmi** [comment]
These were both refactored into Show Dashboard, which is just one thing and hopefully clearer.
