### ISSUE TITLE
Volunteers must have profiles with Badge Names

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#699]
Create some sort of check that there is a name associated with a volunteer bid.  If there isn't one, put in their badge name.  If they don't have a badge name, put in their first name.  If they don't have a first name (i.e., the don't have a profile) keep redirecting them to the profile page until they get it.

**Comment by jonkiparsky** [comment]
There are a few things to get straight here. 
First of all, a user's first name comes from their User object, not from their profile. There is one user in the system without a first_name, and that is the "limbo" user that is used in the ticketing system. (I don't remember the details of this, it was some sort of sketchy Marcus code, but anyway there's a magic user in the system that is used by the ticketing module) All other users have first_names.

Second, all Volunteer bids are associated with profiles. You can't have a volunteer bid without a profile, it's a database constraint. 

Third, all volunteer bids currently have profiles with display_names. (just confirmed this about two minutes ago)

So what exactly is the problem you're trying to solve here? Give me the symptoms.

**Comment by burlexpo** [comment]
> So what exactly is the problem you're trying to solve here? Give me the symptoms.

The symptoms are volunteers who do not have names displayed when they come through.  Yes, all of the volunteer bids currently have profiles with display_names.  That's because I've fixed the ones that have come through without names by hand as they've come through.

There is a way to circumvent the DB constraint of "you can't have a volunteer bid without a profile" quite accidentally and enthusiastically.  It's easier to show you in person -- and since I've got a work-around for this (and there's almost certainly going to be more pressing stuff for you to work on), I'm going to drop this down to 'after the Expo'.

**Comment by bethlakshmi** [comment]
All of the users showing @burlexpo's systems are NOT coming through ticketing (the source of the limbo user, who is exactly 1 user and profile in the system to accommodate purchasers in BPT who never logged into the expo site).  

In all of these cases, the user had a legitimate username, firstname, lastname and password (all the stuff in the User object)

HOWEVER - they also had a near empty Profile object.  No badge name, and other fields that we require on the update profile page are empty.  This can happen through are regular login by the following steps:
1 - register a new account - http://www.burlesque-expo.com/accounts/register
2 - get redirected to the profile page (/update_profile)
3 - choose not to finish it, go to the I want to... Volunteer! link and proceed through the volunteer bid process.

You will end up with a user object, (first name + last name), and a Profile Object with no display name, no phone (also required), and therefore, no name in many other parts of the system.

I did exactly this on test to produce the user "noprofileman"

**Comment by bethlakshmi** [comment]
We reviewed the problem the hack is:
1 - create a user account (first, last, email, username, password)
2 - delete everything on the profile page
3 - save (which stores the profile)
4 - volunteer

And there you are.

We do now have "badge_name" and that's what is used to make your badge - if no display name, it gives first name.

Fix that we actually want:
- on the volunteer page, test for BOTH profile validity (that they at least have a display name and phone number),
- not valid profile or no profile --> redirect to the profile page
- AND give a nice status message in a yellow box saying that this is needed BEFORE volunteering

And our redirect back to volunteer bidding will make this into a nice wizard.

NICE TO HAVE:  add phone validity test script (national only is good enough, internaltional is better)

Do this for all of the bid options - they all have a bidder, make them all check that the bidder has not just a profile but a decent one with contact info we can use.

**Comment by bethlakshmi** [comment]
Also fix the redirect - the volunteer profile missing case should point to update_profile
The update profile should redirect back to the bid.

**Comment by bethlakshmi** [comment]
OK... the fix involves quite a bit of redirecting, so here's the map for my sanity...

When the user hits "volunteer/bid"...

1 - if the user is not logged in --> redirect to "accounts/register?next=/volunteer/bid"
   - account is made, login happens --> redirect to "/update_profile?next=/volunteer/bid"
   - profile is made complete (w. display name and phone)  --> redirect to "volunteer/bid"
   - volunteer bid is successful - go to home page with success message

2 - user has account but no profile --> redirect to "/update_profile?next=/volunteer/bid"
   - profile is made complete (w. display name and phone)  --> redirect to "volunteer/bid"
   - volunteer bid is successful - go to home page with success message

3 - user has profile, but with no display name or phone number -- same flow as #2 

4 - user has a profile, with display name and phone - they go straight to "volunteer/bid"

I added test cases to this effect.
