### ISSUE TITLE
Bios are not filtered by conference

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#703]
We have 3 perfectly good bio pages:

from gbe/urls.py
```
    url(r'^bios/staff/?$',
        views.bios_staff, name='bios_staff'),
    url(r'^bios/teachers/?$',
        views.bios_teachers, name='bios_teacher'),
    url(r'^/bios/volunteers/?$',
        views.bios_volunteer, name='bios_volunteer'),
```

But they don't filter by conference.

Filtering is needed on 2 directions:

1 - filter only the given role for people who are that role in THIS conference
2 - filter for the given conference in the list of things the given person is contributing - for example - Betty taught Bra Bootcamp in 2015 and Bra Workshop in 2016, only Bra Workshop should show up on the 2016 conference page.

SCOPE DOWN - this should only apply to teachers, not to staff and volunteers.  Those URLs were never ever implemented.  We should create a new ticket for next year if we want them.

**Comment by bethlakshmi** [comment]
I'm glad to take when I'm free if this is still high.

I have no particular love of this, though, so if it's beaten to the take by someone else, that's OK too.

**Comment by bethlakshmi** [comment]
Pull request is pending @burlexpo  and @jonkiparsky .

Given the urgency, I'm also texting Jon.

**Comment by burlexpo** [comment]
You're a big damn hero.
