### ISSUE TITLE
Volunteer contact table still doubtful

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#710]
https://github.com/bethlakshmi/GBE2/pull/704

Fixed teachers, performers, and vendors.
But volunteers is doubtful.

As a workaround, I recommend the staff lists (I realize they have problems too...)

But I know that fixing the volunteer thing right now is beyond me.

For sure, right now:
http://localhost:8282/scheduler/contact_by_role/Volunteers

Will give you a list of people with a mix of what they volunteered for last year and this year.
But also - it MAY omit people who were drafted w/out filling out the volunteer bid form, since that's based around who OFFERED, and not who was drafted out of band.

Can't fix before expo.

**Comment by eclecticmagpie** [comment]
thats a bad url

Mike Bergman
www.prospecthillforge.com
www.vintagedancers.org/teadance
www.isebastiani.com
reply-to: eclectic@mit.edu

**Comment by jonkiparsky** [comment]
@bethlakshmi  Why the hell didn't I know you were working on this?

**Comment by burlexpo** [comment]
@eclecticmagpie 

>  that's a bad URL

Nope.  It's a local URL.  Replace everything in front of /scheduler with http://www.Burlesque-Expo.com and it should work.

**Comment by eclecticmagpie** [comment]
On Wed, Feb 3, 2016 at 10:48 AM, Scratch <notifications@github.com> wrote:

> @eclecticmagpie <https://github.com/eclecticmagpie>
>
> that's a bad URL
>
> Nope. It's a local URL. Replace everything in front of /scheduler with
> http://www.Burlesque-Expo.com and it should work.
>
Nope.
http://www.burlesque-expo.com/scheduler/contact_by_role/Volunteers
(literally what you wrote) produces a 500 error.

http://www.burlesque-expo.com:8282/scheduler/contact_by_role/Volunteers
(what I think you meant) produces a "cannot contact server" error.

I suspect that the original URL was local to Beth's machine, and only works
there, not just because it's a local URL, but because whatever changes she
made haven't been pushed live yet.  But that's just guessing.

I poked at this a bit, and produced an Excel spreadsheet that has one line
per volunteer, and MOST of the column info in the right places.  I think it
can be adjusted with some hand-editing without too much pain.  I've
attached it, along with the .CSV file.

**Comment by burlexpo** [comment]
Right you are, Mike.  I get the same 500 error.

**Comment by bethlakshmi** [comment]
@jonkiparsky - I made comments on the pull request 2 days ago.
In the meant time, I got phone calls from Scratch asking me to pull it as is.
Since I saw a way to make 1 broken thing work (Teachers) I fixed it and pulled your pull request.

I wrote this ticket to document the work that I had already made comments on in the pull request.

I don't know how to be less surprising here.

**Comment by bethlakshmi** [comment]
Yes, I get server error 500 on the live site too.
It created results on my local.
It creates results in:
http://gbe2016test.gbeadmin.webfactional.com/scheduler/contact_by_role/Volunteers

And it 500 errors on live:
http://www.burlesque-expo.com/scheduler/contact_by_role/Volunteers

The data is different and causing a problem.

I have tested it with data pulled Jan 30th.  Something between then and now is sufficiently different to cause a case of this 500 error.

My bigger concern is, however, that even when we fix the 500 error, the basic way the data is currently pulled pulls from the gbe.Volunteer object first (that's the comment in the pull request).  The Volunteer object reflects people who *offered* to volunteer via the bids.

The code in scheduling does NOT (and should NOT) require a volunteer bid to be part of the user's account in order for us to draft the person as a volunteer doing a role for a volunteer opportunity.  So I'm worried that as is, the code is inaccurate. 

I provided that comment here:

https://github.com/bethlakshmi/GBE2/pull/704

**Comment by bethlakshmi** [comment]
notes on planned approach:
- create a VolunteerBid when a user is allocated to a volunteer opportunity, 
- choose a set of default values for the Volunteer Bid & mark it as system generated in a comment field somewhere (like background field).
- bid would be for the same conference as the event
- then make sure the contact volunteer by email link looks at volunteer bid only and populates the data from there.

We need a migration for converting current volunteers who don't have bids.

**Comment by bethlakshmi** [comment]
As a side note from staring at the data here, we ALSO need to make sure when this is done that the data output in the CSV is purely for the current conference.

**Comment by bethlakshmi** [comment]
And that it is complete, meaning that;
- every volunteer w a bid for this conference is shown
- there is a row for every booking (in the current conference only) into a volunteer opportunity
- and that the role the volunteer is booked into is accurate

**Comment by BenignCremator** [comment]
Right... Do not test with GBE Admin account, it does not have a complete profile, which generates errors.... Do we want to either make a complete profile for gbeadmin, or alter volunteer review to 'fix' the problem? A redirect to completing a profile before filing out the volunteer form is also an idea.

**Comment by bethlakshmi** [comment]
Hmm... I like the idea of error-proofing the case of 'a user with no profile can be scheduled properly'

I also like 'we screen out users with no profiles from scheduling' - because the profile includes contact information that we can't replicated automatically --- like phone numbers.  worth a place holder ticket and a discussion.

on gbeadmin - I didn't even remember this user existed!
