### ISSUE TITLE
menus do not dismiss correctly

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#718]
See screenshot. We should only have one menu tree active at a time (not two)
<img width="988" alt="screen shot 2016-02-14 at 3 02 28 pm" src="https://cloud.githubusercontent.com/assets/5283553/13036087/1d5d23bc-d32c-11e5-81ac-609404be0b49.png">

**Comment by burlexpo** [comment]
We can close this, right?
