### ISSUE TITLE
Pick a consistent date/time format and institute it.

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#729]
We have at least 2:

http://localhost:8282/scheduler/details/424

Example:  "Feb. 6, 2016, 2 p.m. - 3 p.m."

And 

http://localhost:8282/scheduler/view_list/
Example:  "Sat, Feb 06, 2 p.m. - 3 p.m., "

But also

http://localhost:8282/volunteer/reviewlist
Example: "Fri, Feb 05, 05:00 PM to 10:00 PM"

And

http://localhost:8282/volunteer/assign/569
Example: "Thu, 6 PM - 11 PM" --> although this one was done to save space horizontally.

My vote would be:

Sat, Feb 6, 2:00 PM - 3:00 PM.
- weekday - 3 letter with capitalization
- month - 3 letter with capitalization
- day - no padding zeros
- hour - no padding zeros
- minute - I actually don't care if the minutes are zero if they are there... but we do have stuff at the 30 minute mark.
- AM/PM - all caps, no periods 

But before starting on this ticket, let's find some agreement.  I believe there's a way to set it in the settings... if not, there's certainly a way to make a commonly used function.

**Comment by bethlakshmi** [comment]
I'm torn on whether this is a bug.  I think that inconsistent dates are a visual breakage, but we never set a spec for this.

**Comment by burlexpo** [comment]
I can't see how having a consistent date/time format could be a bad thing...

**Comment by jonkiparsky** [comment]
Formatting dates is trivial. There is a provision for a default date time
format in settings, if you want to use it. There is a set time format
function in scheduler, but it is kind of broken and should be rewritten.

Not sure I see the urgency of this item relative to getting up to the
upgrade and resolving currently outstanding bugs

sent from my handy. typos are just part of the fun.

**Comment by BenignCremator** [comment]
*SIGH*  Date/Time formatting should be context and user pref dependent and not in the code per se.  We really should just specify what the granularity, for lack of a better term, is in the code is, and have the user set how they want to read it.  This is one of the things that Django is supposed to make easy, but we never sat down and figured out the Django-easy way, and now we have hard code in the app....

**Comment by bethlakshmi** [comment]
Note to self...

To do list...

- set settings.py format for this
- force formatting on the fly to use settings.py
- use django settings where possible (research that…)

- set time format - is also weird.
   - kill it, and refactor into this plan

- update wiki for later review

**Comment by BenignCremator** [comment]
Have created date/time formats (plural) in settings.py, and updated some of the *.py and *.tmpl files to use them.  More importantly, I have figured out how to use them in the templates, which was non-obvious.  Add a page in the wiki about them, and how to use them.  Have not figured out how to use them on a couple of the pages, since I can not find where the dates are referenced.  Wondering if it is within Javascript.

**Comment by bethlakshmi** [comment]
For http://localhost:8282/volunteer/reviewlist

The path is
 urls.py --> review_volunteer_list_view (asView)
   ---> review_bid_list_view (parent)
     ---> get -> get_context_dict (goes to volunteer list) -> rows 
      - which is built by get_rows - 
   ---> bid.bid_review_summary

Which then hits remains, and in this case the class Volunteer.

Which brings us to volunteer.py, lines 66-100

The dates are built for availability_string and unavailability_string - which are the list of VolunteerWindow objects (remains.py) and it's just their unicode output (lines 88-90)

So the actual time manipulation is in remains.py --> Volunteer Window --> lines 88-90

**Comment by BenignCremator** [comment]
.....  I finally found what you are referencing.  It was in gbe/models/remains.py, not gbe/views/ or gbe/forms.  I would expect formatting to occur in the views.  Changing this to finish ticket, should open ticket to move this into views.

**Comment by BenignCremator** [comment]
Ok, have time in default formats and pulling format from settings.py file, so we can change this.  Committed code, some errors in coverage tests, first glance is either tests checking for specified text, or tests using formats while being able to import them.  Digging deeper....

**Comment by BenignCremator** [comment]
This has become an 11 point ticket.  First off, some of the test were testing the date/time formats with literals.  Mostly changes those to test against a format pattern.  Others were testing formatted date/times against formatted data/times from other parts of the app, so to get them to work, needed to go through and change most of the formatting for date/time across the apps.  Which led to needing to fix their tests as well.  Down to 22 tests failing, all having nothing to do with the scope of the original request.  *WHEE*

**Comment by BenignCremator** [comment]
And now I have found a couple of tests that get DATE_FORMAT from the default Django filters, and ignore what is in settings.py.  Adding an import into these tests did not fix the problem, since it seems to be happening at a lower level then our test code.  Tricky.  Need to ponder this.

**Comment by BenignCremator** [comment]
Problem with tests was that in many places, we were pushing formatted time text down for storage or BI logic, not pushing it up for display.  Restored the literal formats for data being pushed down, and failed tests went away.  Long term, we may want to change the models.py et al to NOT store formatted time text in the DB but either UNIX time long_ints or durations ints, do logic on those, and only format for display, however that goes WAY beyond the scope of this ticket.
