### ISSUE TITLE
10 - Pictures on site?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#73]
Is it possible to have some panes on the site -- not on every page -- that display an image randomly selected from a directory of images?

i.e., on the profile update page (for example) would it be possible to set a pane below the "Please let me know About" pane (on screen right) that displayed an image at random, if we made sure that all the images were the same fixed size?

This is a "nice to have" and not on the critical path.

**Comment by burlexpo** [comment]
This may get resolved with the CMS system.

**Comment by burlexpo** [comment]
@bethlakshmi I think this can be closed.  Do you agree?

**Comment by bethlakshmi** [comment]
I agree if you do.
We don't have pictures *everywhere*, but I think we hit the spirit of the request.
