### ISSUE TITLE
Coverage for scheduler.views - schedule_acts

### ISSUE THREAD

**Issue by BenignCremator** [bethlakshmi/GBE2#734]
Coverage is currently at 9%.  Target is 90%.

**Comment by jonkiparsky** [comment]
Ah, come on - shoot for 100%...

**Comment by BenignCremator** [comment]
On 03/03/2016 09:10 PM, Jon Kiparsky wrote:
> Ah, come on - shoot for 100%...

The first 90% if any job take the first 90% of the time.  The remaining 
10% takes the remaining 90% of the time.

Seriously, though, I would if I though that 10% was going to be worth 
not putting other coverage work in elsewhere.  At that point in time, 
the gaps in the code will most likely be bigger fish to fry.

Hunter

**Comment by BenignCremator** [comment]
First commit, covers base case of event_list.  Required 'Scheduling Mavens' perms, which tells me that that this event_list was not the event_list that I was looking for (I had assumed that this was the event_list for all users looking at events, not the one Scheduling Mavens used to populate the calender).  Still, done is better then not done, so I will take it....

**Comment by bethlakshmi** [comment]
@BenignCremator  - where are you on this?  I have maybe 1-2 days of scheduler test stuff I can do before this becomes a blocker to 100% coverage on scheduler.views.  If you are willing, I'm game to start on this on Monday.

**Comment by bethlakshmi** [comment]
Closed, the view now has 1 uncovered line of code, and it's a difficult to mock case.
