### ISSUE TITLE
Bid class - causing an error in save draft exposes ALL personae.

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#749]
This is NOT a regression, but it is a bug.

It is at least as old as March 3, 2016 (broken on live which dates to that date)

Steps to reproduce:
1 - go to - (or another version of the code)

http://gbe2016test.gbeadmin.webfactional.com/class/create/

2 - Press "Save Draft" (fill in no information)

3 - an error appears (title is required)

PROBLEM - Pull down the Teacher: drop down - you'll see that ALL personae are there (all individuals, troupes are not there).  The selection should stay consistent with the initial load during the creation and only the user's relevant personae should be there (for example, if you are "betty", then you get "Betty Blaize" and nothing else).

**Comment by jonkiparsky** [comment]
Fantastic! What thing to find. Okay, I'll take a look.

**Comment by bethlakshmi** [comment]
Whee!  Merged.
