### ISSUE TITLE
act/create does not work

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#750]
On current master;

http://gbe2016test.gbeadmin.webfactional.com/act/create

throws the error:

global name 'Performer' is not defined

This is a break since the update on March 3.  It does not fail on live.

Marking as high because it utterly blocks new act creation, so I won't push master to live with this

**Comment by jonkiparsky** [comment]
My bad, fixing. (see - test coverage is important!)

**Comment by bethlakshmi** [comment]
merged
