### ISSUE TITLE
Clone Class  Bids results empty data

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#764]
From what I can see, this is NOT a _recent_ regression. 
However, it's a really big bug.

1 - go to historical view of personal page
http://localhost:8282/gbe?historical=1

2 - pick a class, select clone

3 - the class shows up in the current view with no name.
If you look further you'll see that almost no data has been cloned.

This is true as well on live, prior to any recent update.

Not sure how far back this regression goes, I'm fairly certain this worked at some point...

Marking as high because it means a feature really doesn't work at all.

**Comment by jonkiparsky** [comment]
This one is profoundly weird.
