### ISSUE TITLE
Coverage for scheduler.views.view_list

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#776]

**Comment by jonkiparsky** [comment]
Gee, more dead code.

**Comment by jonkiparsky** [comment]
Should probably also clean up the confusion between view_list and event_list in the urlconf

**Comment by bethlakshmi** [comment]
Makes sense to me.  I fear it (hope we don't have many/any "reverse" calls) but yeah, that's very confusing.
