### ISSUE TITLE
Changes to http://burlesque-expo.com/volunteer/bid/ #1 (Replace shifts with hours)

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#821]
On http://burlesque-expo.com/volunteer/bid/

Replace the first questions ("How many shifts would you like to work?") with the question "How many hours would you like to work?".  Response can still be in a drop-down menu.

**Comment by bethlakshmi** [comment]
This can be just changing the label.  For clarity we may want to change the DB column name.
