### ISSUE TITLE
Create Event Based messaging system for bids

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#823]
**Since this is going to apply to class and act bids, it needs to be up and running by 7/31/16** When a user successfully submits or edits a volunteer bid, that user should get a pop-up which corresponds to the action they have taken.

Tech details below.

**Comment by bethlakshmi** [comment]
I used 

`from django.contrib import messages`

When implementing a popup in assign_volunteer.  The code is actually in gbe/forms.py
The library also had to be set in our settings.py file to include it.

**Comment by bethlakshmi** [comment]
Messaging system would be in the DB, editable via Admin, with a structure like this:
- view - name of the *.py view in gbe/views
- text - html that shows up
- summary - something scratch can read
- code - ALL_CAPS  code that lets the code fetch what it needs.

code and view are Read only in Admin
the others are editable.

view + code are unique together.
