### ISSUE TITLE
Add 'Less Preferred Times' field to Class Submission form.

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#827]
On http://burlesque-expo.com/class/create/

Create a required question of checkboxes called "I would Prefer to Avoid" and place it just below "Preferred Teaching Times".

The checkbox options are

- Friday Afternoon
- Saturday Morning
- Saturday Afternoon
- Sunday morning
- Sunday afternoon

The checkbox options are the same as the ones for "Preferred Teaching Times"; if we change those it's likely these will change as well.

Add a pop-up help text which reads "We will do our best to accommodate everyone's requests when scheduling classes, but please realize that is not always possible.  The more flexible you can be, the more likely we are to be able to schedule your class.  Thanks for your understanding!"

**Comment by jonkiparsky** [comment]
This should appear everywhere that Preferred Times appears

**Comment by gawaineo** [comment]
Is this link correct? http://burlesque-expo.com/class/create/ 
I can't find the Preferred Teaching Times options.

**Comment by jonkiparsky** [comment]
That's one spot, certainly. The way I would find the others would be to find where that literal is defined:
```
[jpk@Jons-MBP-2/~/code/GBE2: Sun Jul 10 16:10]:527 $ git grep "Friday Afternoon"
expo/gbe_forms_text.py:class_schedule_options = [('0', 'Friday Afternoon'),
```

and then look to see what we're doing with `class_schedule_options`:
```
[jpk@Jons-MBP-2/~/code/GBE2: Sun Jul 10 16:10]:528 $ git grep class_schedule_options
expo/gbe/forms.py:        choices=class_schedule_options,
expo/gbe/forms.py:        choices=class_schedule_options,
expo/gbe_forms_text.py:class_schedule_options = [('0', 'Friday Afternoon'),
```

And then I'd proceed from there. (yeah, it's a bit of a scavenger hunt...)

**Comment by gawaineo** [comment]
Should "I would Prefer to Avoid" be a required question? It's currently marked as required in my updates.

**Comment by burlexpo** [comment]
No, it shouldn't be.  We need to know what times they prefer, but they 
may not have times they want to avoid.

**Comment by gawaineo** [comment]
ok gotcha, fixed it.
