### ISSUE TITLE
Persona images are expandable

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#841]
Related to #305 

When user clicks on thumbnail image, show expanded image in pop-up window.  Image is persistent until dismissed or user leaves this page.

**Comment by jonkiparsky** [comment]
Modal should be persistent until dismissed. (provide a dismiss button)

**Comment by bethlakshmi** [comment]
On the http://localhost:8282/gbe page
has a popover (window on top of the existing page, with a closeable X)

**Comment by jonkiparsky** [comment]
Required: do this on the profile page

**Comment by jonkiparsky** [comment]
Ideally, this should be reusable code.

**Comment by BenignCremator** [comment]
Functional testing kinda works.  Either image is not sized to fit the popup, or the popup is not sized to fit the image.  Should be one of the other (I would lean towards sizing the popup to the image, but that is me).  Also, some of these images are HUGE.  We may want to resize images to an appropriate 'full page' size, so the one that take up four or more screens, well, don't.  Waiting to confer with others on this before I approve.

**Comment by gawaineo** [comment]
- Changes look good and the photos are consistent and centered.
- pep8 looks good as well
- test results from py.test are great
![samurai_shot](https://cloud.githubusercontent.com/assets/13838812/18893151/a506c34e-84da-11e6-85af-38bb556dd94c.png)
![lionel](https://cloud.githubusercontent.com/assets/13838812/18893183/c036b340-84da-11e6-9b4d-352054d43a55.png)

**Note:** In the screenshot below I notice only the top picture shows where you see Samurai and Samurai2. I believe @BenignCremator pointed this out last time (so maybe there is a separate ticket).


![2nd_photo_missing](https://cloud.githubusercontent.com/assets/13838812/18893132/8d6a910c-84da-11e6-90f0-f9f62a3a1fb6.png)

I approve as well, changes look great.

**Comment by gawaineo** [comment]
closing, changes were committed and Pull request was reviewed and approved.
