### ISSUE TITLE
Cache all existing images in such a way as to not blow up the server

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#842]
EOM

**Comment by BenignCremator** [comment]
Added batch processing capability to the code, general code refactor, added a 'thumbnail' size to the resize options, and ability to specify options on the command line, including location to move images to.  Tested on personal server.  Installed onto web462/GBE test, and fixed bugs to get it to run there.  Committed code to a new branch, issuing a PR.

**Comment by BenignCremator** [comment]
PR has been reviewed and accepted into Master.  Checked deployed code on GBElive/web489.  Has processed 409 files correctly, logs look good.  Closing.
