### ISSUE TITLE
Move "Performer Items"

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#843]
This work is to be done on http://localhost:8282/gbe

 Move **Performer Items** from the rightmost column to the bottom of the center column (below tickets).

**Comment by gawaineo** [comment]
Hi,

On this page: http://www.burlesque-expo.com/gbe , I don't see anywhere that says tickets. But I was able to find where the tickets template is on that page.

Should I be seeing something related to tickets in the middle of the page?

G

**Comment by burlexpo** [comment]
> Should I be seeing something related to tickets in the middle of the page?
>
Only if the account has purchased tickets (which includes application 
fees and vendor booth fees).  If the account hasn't purchased tickets, 
the section doesn't display.

**Comment by gawaineo** [comment]
Is there a way I can fake ticketing so that the Performer Item section pops up?

**Comment by burlexpo** [comment]
Login to your account and select *I Want To... > ...Buy A Ticket*  You get taken to our ticketing page.  Click the link to purchase a "Whole Shebang".  You get taken to the BrownPaper TIckets site. Enter *2017VIP* into the "Password or Discount Code" field and click "Show Available Tickets".  The option to 'purchase' a ticket for no dollars shows up.  Add one free ticket to your shopping cart and check out, making sure to  use the same address to check out as you use on the Burlesque-Expo site.

**Comment by gawaineo** [comment]
Oh ok, I tried to do that yesterday but it didn't show me any ticket options (on my locally running GBE app). Below is a picture.
![selection_005](https://cloud.githubusercontent.com/assets/13838812/17423518/330e33ec-5a89-11e6-88e7-c82833774436.png)

**Comment by jonkiparsky** [comment]
@gawaineo Did you mean to open a PR for this branch?

**Comment by gawaineo** [comment]
Yea I did.
On Aug 7, 2016 01:33, Jon Kiparsky <notifications@github.com> wrote:@gawaineo Did you mean to open a PR for this branch?

**Comment by jonkiparsky** [comment]
Okay, 'cause I'm not seeing one.

**Comment by gawaineo** [comment]
Created: https://github.com/bethlakshmi/GBE2/pull/851

**Comment by gawaineo** [comment]
https://github.com/bethlakshmi/GBE2/pull/851
