### ISSUE TITLE
Change Label on Volunteer Reviewlist

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#855]
On The volunteer review page (http://gbe2016test.gbeadmin.webfactional.com/volunteer/reviewlist) the fourth column still reads "# of **shifts**".  It should be changed to read "# of **hours**" to reflect recent changes to volunteer bid form.

**Comment by bethlakshmi** [comment]
Cool.  For reference, I think this is stored in gbe/models/remains.py as a static list of values.

**Comment by BenignCremator** [comment]
Reviewed that is find that the assign volunteer view (/volunteer/assign/[id#]) also states '# Shifts' instead of '# of Hours'.  Rolling that change in as well.

**Comment by gawaineo** [comment]
@jonkiparsky  @BenignCremator is this complete and needs to be closed?

**Comment by BenignCremator** [comment]
Yes, can be closed.  Closing.
