### ISSUE TITLE
BUG: All video options displayed when none selected

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#856]
When submitting an act, a performer can select one of 
- This is video of the act I'm submitting
- This is video of me, but not the act I'm submitting
- I don't have any video of myself

Ordinarily in reviewing an act, only one of those options is displayed.  In looking at [Red Velvet's submission ](http://burlesque-expo.com/act/review/715) where (my guess is) she didn't select any of those options, we sell _all_ of those options displayed. 

![red velvet review](https://cloud.githubusercontent.com/assets/5369404/17641153/30e5fae6-60e2-11e6-8e87-bc94af7e5d45.jpg)

**Comment by bethlakshmi** [comment]
now up on test.

**Comment by burlexpo** [comment]
Tested.  Works.  Closing.
