### ISSUE TITLE
Automated Deploy Process that allows for Fast Roll Back to previous state

### ISSUE THREAD

**Issue by BenignCremator** [bethlakshmi/GBE2#857]
Write an automated deploy script that provides for safe forward deploy and safe backward deploys to known state.  Expected requirements of Ver 1.0:
-  Take server down and/or provides down for maint page
-  Pulls code from repository
-  Migrates DB
-  Allows smoke testing before accepting deploy
-  Gives us a binary accept deploy or rollback option.
-  Rollback takes us back one step

Thoughts on implementation:
-  A down service page that state that we are performing maintenance
  *\*  Current downconf pages produce an Internal Server Error
-  Backs up database at start of process
-  Has three or four directories that houses the codebase
  *\*  A new directory that new code is pulled into
  **\*  Migrations occur here before code is run via wsgi
  *\*  A current directory that is the current running code
  *\*  A previous directory that holds that last running version of the code
-  One step command that accepts the release name we are going to deploy
-  One step command that rolls back the release to the previous directory of the code
  *\*  Uses parallel databases for each code directory avoid lost data on rollback after delay
  *\*  New DB migrations will need to be compatible with old Code

**Comment by bethlakshmi** [comment]
Divio does this differently enough that this can be deprecated
