### ISSUE TITLE
WON'T DO: Add URLs to Images in Slider

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#864]
This tickets is considered closed when a site editor (i.e., me) can easily create a slideshow of images where we can easily specify the URL the user is taken to when any given image is clicked.

Ideally, this would simply be built on top of either the existing "Gallery" plug-in or the various image attributes that are editable in the CMS file manager.

**Comment by bethlakshmi** [comment]
I'm not sure I understand this one... when you say "any given image" can you give me some examples - we have images all over the place and they are pretty different from page to page in how they operate... so "all" images is impossible.  My baseline would be:
- are the images created via the django-cms system?
- are they vendor images?
- are they user persona images?

**Comment by burlexpo** [comment]
What I want to be able to do is put a slideshow on a page with multiple images in it.  I want to easily be able to specify that if *Image 1* is link with URL of ABC, so clicking the image takes the user to ABC; *Image 2* is a link with URL of DEF, so clicking the image takes the user to DEF; etc.

**Comment by bethlakshmi** [comment]
Hmm... so as I see it, the work of this (technically) is:
- either find or build a Django CMS slideshow that does the URL activity described here   
   - if "build" is the answer, we could extend a slide show CMS plugin that is available today (there are 2 or 3, I could dig up my notes)
   - ... or... build one using a slideshow GUI element (I think there is one in bootstrap)

- integrate it in our Django-CMS system, *probably* removing the existing slideshow plug in if there is feature parity.

Assumption - we have a limited number of slideshows now, so we don't need to worry about data migration from old slideshow plug in to new slideshow plugin.

Assumption - we don't need it (in this ticket) to connect to non-django-cms code (for example, the event details for a show, or the fashion faire - two very image heavy pages)
