### ISSUE TITLE
Vendor coordinator does not get bid state change section

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#865]
on the page:

http://localhost:8282/vendor/review/643

a user with the permission "Vendor Coordinator" should see a box in the lower right hand corner of the screen that shows the "Bid Change" = a form with the bid state (accept, reject, etc) and a submit button. Same GUI as:

http://localhost:8282/class/review/643
http://localhost:8282/costume/review/643

But it no longer shows up.

**Comment by bethlakshmi** [comment]
@jonkiparsky - I don't want to mess around in an area you are heavlly working in.  But if you want me to, I'll take it.  I suspect unless @burlexpo it is not immediately urgent, but will be very urgent when we need to accept vendors.

**Comment by jonkiparsky** [comment]
Will take this one

**Comment by bethlakshmi** [comment]
Thank you.

**Comment by burlexpo** [comment]
I originally created this as #854, which is closed now.  Here are my notes for what they're worth:

I believe that I have both 'Vendor Reviewer' and 'Vendor Coordinator' status. It looks that way when I check http://burlesque-expo.com/admin/auth/user/

My reviewer status seems to function. When I go to http://burlesque-expo.com/vendor/reviewlist I see @bethlakshmi's test vendor ("Betty test"). When I click the 'review' link, I'm taken to the review page where I see the Reviewer tool (lower left-hand corner), but not the coordinator tool (which should be in the lower right corner).

**Comment by BenignCremator** [comment]
Just pulled this down and set ip up.  Functional test looks good.  Progressing onto code review.
