### ISSUE TITLE
Act create failing on live

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#866]
```

  File "/home/gbelive/webapps/gbelive/lib/python2.7/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/gbelive/webapps/gbelive/lib/python2.7/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/home/gbelive/webapps/gbelive/expo/expo/gbe_logging.py", line 25, in __call__
    return funct(*args, **kwargs)

  File "/home/gbelive/webapps/gbelive/expo/gbe/views/bid_act_view.py", line 124, in BidActView
    'BidActView')

  File "/home/gbelive/webapps/gbelive/expo/gbe/views/act_display_functions.py", line 25, in display_invalid_act
    performer__contact=profile)

  File "/home/gbelive/webapps/gbelive/lib/python2.7/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)

  File "/home/gbelive/webapps/gbelive/lib/python2.7/django/db/models/query.py", line 313, in get
    (self.model._meta.object_name, num))

MultipleObjectsReturned: get() returned more than one Act -- it returned 2!


<WSGIRequest
path:/act/create/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'theact-why_you': [u'Been on my Meow Tour since May of this year.  Haven\'t been to this side of the U.S. since I lived in Fl.  I also love to travel meet to people, producers and see how others "burlesque".  I always learn when I travel and love meeting new people.'], u'theact-video_choice': [u'2'], u'theact-track_duration': [u'04:00'], u'theact-act_duration': [u'04:00'], u'theact-other_performance': [u'0', u'1', u'2'], u'theact-track_artist': [u'Pharrel Williams'], u'theact-description': [u'Fun upbeat disco comedy act. Disco diva who is HAPPY and then switches into roller skates from the rest of the performance.'], u'theact-shows_preferences': [u'0', u'1', u'2', u'3'], u'theact-title': [u'Roller Girl'], u'theact-track_title': [u'Happy'], u'submit': [u'Submit For Approval'], u'theact-video_link': [u'https://www.youtube.com/watch?v=jxo5_AWQ4rY&feature=youtu.be'], u'csrfmiddlewaretoken': [u'bPiLUTHO1q4mu5TzotTIEXg7QdM61Dqu'], u'theact-performer': [u'1273']}>
```

**Comment by jonkiparsky** [comment]
Act edit is also failing, looks like the same bug

**Comment by burlexpo** [comment]
It's just that one user.  I was sending out email about this.

**Comment by jonkiparsky** [comment]
Okay, still a bug. Will have a fix tonight

**Comment by burlexpo** [comment]
Here's the email I was writing:

I have a user with a spectacularly screwed up account.  It's not a system-wide bug (because it's  just one user), so I'm not sure how to log it.  Here's the issue:

User 'Chairmyn Meow' created two draft acts during the first week in August.  She never submitted them.  On August 8 (at the end of the free application period), I went and deleted all the unused free application 'tickets' from our system and had Brownpaper Tickets do the same on their end.

She contacted me yesterday and said: "I also went and tried submitting my saved acts now and I received an internal server error 505. Twice when I tried to submit."

I went and created a test act and was able to save it as a draft without a problem.  I was able to submit that act (once paid) without a problem.

Then she wrote to me and said:

> Ok, so I logged out and when I tried to log back in it mentioned my account didn't exist but when I tried to make another account it mentioned that email was in sue already.
> I did while I was logged in create another act and try to submit and I received the same server error.
> 
> Ok, so I made a new login used my personal email, didn't take my name since it's "already in use" I wrote Chairmyn Meow Now.  It took my act. I filled everything out quick and short hand. Too many times filling out forms.  So I guess my account was corrupt 😞"

**Comment by jonkiparsky** [comment]
Ah, okay. Interesting. Thanks for that. I'll review the state of the code around this and see if there's anything I need to do (ie, catch this state and handle it better)

**Comment by jonkiparsky** [comment]
@burlexpo @bethlakshmi So the problem is if there are more than one existing acts with name conflicts, the get() call here fails, because get() always fails unless it finds exactly one matching item. 
There is a PR out with a simple fix for this: if there are multiple matching acts, it takes the first one. This is not ideal, since it doesn't really show the user what the problem is, but at least it lets them see what's going on and change the name of the act they're submitting, which is I think what we want them to do. If they decide to change the name of the existing act that we show them, then their submit fails again, they see what looks like the same edit screen again, they get frustrated, and maybe customer service is required, or maybe they just fix it again and get on with their life. 

If this behavior is acceptable, let's go ahead and merge the PR. If something more fancy is required we need to discuss exactly what should happen in this case and how much attention we want to give to this situation.
