### ISSUE TITLE
Create PurchasedTicketContext

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#878]
Context should provide the necessary objects, connected correctly, for tests which require a purchased ticket. 
Ideally, this should be used to simplify a couple of existing tests.

**Comment by jonkiparsky** [comment]
@bethlakshmi Can you provide a reference for a test or two that are doing this logic already?

**Comment by bethlakshmi** [comment]
My best emulation for this is:

GBE2/expo/tests/ticketing/test_process_bpt_order_list.py
- which mocks a ticket being purchased and the GBE ticketing system finding it.

GBE2/expo/tests/ticketing/test_transactions.py
- which does simulate a transaction

GBE2/expo/tests/gbe/test_reports.py
- does a simple little transaction and purchaser to test the badge reports (create_transaction)

Sorry... somehow I didn't realize this one was in our sprint!

**Comment by gawaineo** [comment]
Ok thanks, will look into it.

**Comment by BenignCremator** [comment]
Bethlakshmi and I approved, I merged and closed PR, deleted branch.  Waiting on deploy to test to close ticket.
