### ISSUE TITLE
Fee and max enrollment can not be null

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#882]
They can be blank but not null.
When you delete the values from either of these fields while bidding, you will get an error because the model won't let you submit a null value.  

Recommendation = update the model and let them be null.  We don't actually want to require them, and so empty should be OK.

**Comment by bethlakshmi** [comment]
Because this is blocking a test in #833 (can't create a class because I didn't give max_enrollment), I may fix this with #833 so the test can proceed as it should.

**Comment by jonkiparsky** [comment]
Is this really a blocker? Can't the test simply provide a max_enrollment? 
I ask because migrations at this point are not going to make life easy if we want to pursue the path to 1.7 (GBE-877)
