### ISSUE TITLE
Research coordinating ticket prices/descriptions

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#896]
We want to have ticket descriptions and prices automatically synched.  When synched, information from BPT takes precedence over information on Burlesque-Expo.com

Related to #238

**Comment by bethlakshmi** [comment]
Putting this down because I think I can the other unassigned & open ticket done more quickly.

**Comment by bethlakshmi** [comment]
Picking this up, but I hit a snag.

The description is easy enough to find, and it's easy enough to always update ticket info when the description changes.

The challenge is coordinating the prices...

The BPT API does NOT give me a clear indication on what price to publish.  What it gives me:

http://www.brownpapertickets.com/apidocs/2.0/pricelist.html

is the field "live":

- "yes" = currently available for purchase
- "no" = currently NOT available for purchase

BUT - that includes things that can be purchased with coupons.  So if you use our developer id, and poll this api:

http://www.brownpapertickets.com/api2/pricelist?id=**PUT_DEVELOPER_ID_HERE**&event_id=2504574&date_id=1408005

Then you actually get 3 prices that are "live":
- $175 - the main purchase price right now
- $40 - a deal that can only be bought with a coupon by very special people
- $0 - a deal that can only be bought with a coupon by VERY very special people

We only want to put the first on our site.

So... I can't *totally* trust the value of "live".

I have two options:

1 - we argue with BPT and get them to add some sort of coupon indicator to the API. That would tell us if the price is fully public, or something we only offer to coupon holders.

2 - I add a "coupon_required" field to our side of the data.  If you set "coupon_required" - the code will never ever publish that price.  If you *don't*, then when the price goes live, we change the public price.

Also - to make this really useful, we need a timed sync with BPT to get the ticket prices on a regular basis, so we can automatically change the price when needed.  In most cases, the conditions are that we sold X number of cheaper tickets, and that trigger is unpredictable.
