### ISSUE TITLE
DB Scrubber script to smooth some of the rough edges of using DB Dumps for Dev and Test work

### ISSUE THREAD

**Issue by BenignCremator** [bethlakshmi/GBE2#906]
While talking with Bethlakshmi, a desire for a script that would scrub the DB dumps of some of the things that make dev and test work less then optimum.   First pass for things to improve:
*  Substitute real world URLs to localhost, so clicking on a link in a browser does not take you to burlesque-expo.com or webfactional when you are doing local dev or test work.
*  Substitute every password for a standard dev/test password that has nothing to do with reality, so we do not have to reset them to log in as a different user.

Nice to have:
*  Anonymize personal information, so a lost DB files does not expose emails, personal name and details, etc.

**Comment by BenignCremator** [comment]
First pass of a DB Scrubber script.  Seems to work, but need other eyes to check it.

**Comment by bethlakshmi** [comment]
Not necessary with Divio as we get database dumps as part of their tooling.
