### ISSUE TITLE
Trying to save tech info/schedule rehearsal throws error.

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#920]
User May Hemmer reports that she can't schedule a rehearsal slot.  She can get to the tech info page for her act and select a slot, but when she clicks "Save" she gets a 500 error.  I hijacked her account and verified the problem.

**Comment by bethlakshmi** [comment]
This is the same bug as #593 - which we just pulled to master.

I pulled the master branch onto gbelive to fix that just now (12:15PM Thursday, Dec. 8)
