### ISSUE TITLE
Email Template per Show

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#949]
Create a show key for the email templates such that each show acceptance notifaction can give details specific to the four different shows.  Also, pass the template a Show Name and an Act Tech Info link.

**Comment by bethlakshmi** [comment]
Some details:

- the template key would be the show's title ("The Burlesque Bordello") which means they would stick around from year to year.

**Comment by bethlakshmi** [comment]
https://github.com/bethlakshmi/GBE2/pull/937
