### ISSUE TITLE
Add a Captcha to ../accounts/register

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#956]
Upon reviewing the existing users, I noticed a bunch that were clearly created by robots.  I don't think they're harmful, but they do clutter up the DB and could potentially be harmful.  Can we install something like https://github.com/kbytesys/django-recaptcha2 to validate the forms submitted through ../accounts/register?

The first couple of Captcha packages I looked at on https://djangopackages.org/grids/g/captcha/ seem to want at least v1.7 of Django.  Also, I'm a big fan of the "I'm Not a Robot" verification (https://nakedsecurity.sophos.com/2014/12/05/i-am-not-a-robot-google-swaps-text-captchas-for-quivery-mouse-clicks/) vs the "please type in this distorted text" verification.

**Comment by gawaineo** [comment]
I resource of resources I found on stackoverflow: http://stackoverflow.com/questions/2275806/easy-to-use-django-captcha-or-registration-app-with-captcha

**Comment by bethlakshmi** [comment]
https://github.com/mbi/django-simple-captcha/tree/v0.4.6

**Comment by bethlakshmi** [comment]
How about this one?

https://github.com/praekelt/django-recaptcha

Looks like it uses the checkbox style captcha, and looks easy enough to integrate.  

I also suggest that I put it on any no-login-required form - including class idea proposals.
