### ISSUE TITLE
Change default number of volunteer hours

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#959]
The "Number of Hours" field on ../volunteer/bid/ is required but has a default value of 1 so if someone ignores or overlooks this field, they sign up for 1 hour of volunteering; not so useful.

1) Set the initial value of the dropdown menu to "-----" so that someone is forced to select a value.

2) Set the minimum number of hours they can select to 2 (i.e, list value is 2, 3, 4, 5, etc. up to 12).

**Comment by burlexpo** [comment]
Hey @gawaineo do you think you can tackle this in the next couple of days? I know it's not the way we've been doing things, but we're now more in the crunch phase than anything else, and I *think* this is really editing and not re-coding.

**Comment by gawaineo** [comment]
@burlexpo @BenignCremator @bethlakshmi 

Here's the PR: https://github.com/bethlakshmi/GBE2/pull/963
