### ISSUE TITLE
Add JavaScript functionality to ../profile/manage

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#970]
Add the ability to hide columns and sort by columns to ../profile/manage like we have on ../act/reviewlist

**Comment by bethlakshmi** [comment]
A thought - what if we also combine the Emails?  we have the user's identified email, and then a secondary email they may have used to purchase stuff with (controlled purely by admins for security reasons).  What if we put both emails in one column with a marker?

> Contact:  contact@email.com
> Purchase: purchase@email.com

It might fix the ugliness nicely.  And it would be searchable with the Javascript library we use elsewhere.

**Comment by burlexpo** [comment]
Sure. That's Good Thing.
