### ISSUE TITLE
Be able to delete users through ../profile/manage

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#971]
Related to #970 

Add a new "Action" to the "Action" column: **Delete**

This should do the same thing as

- going into http://burlesque-expo.com/admin/auth/user/
- selecting a user 
- selecting "Delete Selected Users" from the dropdown menu
- clicking the "Go" button

BONUS: If it can throw a warning pop-up message of "Are you sure you want to delete this user?" with cancel/confirm buttons, that'd be great, but it's a nice-to-have, not a requirement.

**Comment by bethlakshmi** [comment]
I'd like to assume the following constraints:
- Only if you are the Volunteer Coordinator
- This really blows away everything - just like /admin/auth/user... it will kill:
    - the user (username/password, etc) & profile info
    - the personas of the user
    - the acts and other bids made by the user (so if this user proposed several Acts and a Class, all are gone).
    - and any interaction from any PREVIOUS conference...  (if they performed last year, they are gone, too...)
    - and anything they were booked into.

That's what "delete user" on the user's page - the user is the root of an enormous tree of stuff.

That seems a bit terrifying from the point of view of that particular screen - but you're the boss.

**Comment by bethlakshmi** [comment]
counter proposal from team:
- button on Act Review List that takes you to /profile/manage
- action on profile/manage to delete that user

**Comment by burlexpo** [comment]
No,  I don't want it on the Act Review List.  We have a bunch of robots that have created accounts.  I want to be able to blow them away and the easy way to spot them is on ../admin/auth/user/.  

Please do it the way it is described in the ticket.

**Comment by bethlakshmi** [comment]
Hmm... I was looking at the ticket #1001 and thinking that we could serve two needs w. one function.

Problem: I wanted to give a warning on this work that wasn't just - "are you sure?" but that gave actual details of what would be deleted, so the user could be warned when this isn't just a superfluous user.  

**Proposal:**
- when an special privilege user does the delete function called here...
- if the user is only a user with a profile (the typical pattern of a robot) - we delete the data entirely.  Let's get the crap data out of the system entirely.
- if the user is tied into Bids, or Events, or Purchases - we go the "inactive" route - we disable the user account.  
    - in the case of in active - the user is marked not "Active" (visible on /admin/auth/user/<id>/)
    - the user email remains intact
    - the profile remains intact
    - any connection that reflects the user (bids, events, tickets) remains intact and as public as it ever was.

Regardless of the outcome, we send a green alert message to the top of the screen saying which one we did.  Either:
- This user had no involvement with the Expo, all data has been deleted.
- This user was previously involved with the Expo.  The account has been disabled.  Involvement was:  (provide summary of events, bids, tickets as pleases me... let me know if you want something specific).

That sets me up pretty well to reuse a lot of this code on the "self delete" later.

**Comment by burlexpo** [comment]
That all sounds good to me.
