### ISSUE TITLE
Submitting a bid sends email

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#975]
When a Volunteer Bid comes in, it sends a notification to all the Volunteer Reviewers.

When a class bid comes in, an automated notification should be sent to class reviewers.
When an act bid comes in, an automated notification should be sent to act reviewers.
When a vendor bid comes in, an automated notification should be sent to vendor reviewers.

**Comment by bethlakshmi** [comment]
closed with #888 and #889 - making the code more unified, I included this.
