### ISSUE TITLE
Include name in automated emails

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#976]
Currently, when a class status is changed, an automatic email is generated which reads "Dear [Name], The status of your class has been changed to Accepted. You can always check the status of your submissions or your schedule by visiting your personal pane on Great Burlesque Expo" 

I'd like it to say "Dear [Name], The status of your class, **"[Name of Class]"**,  has been changed to Accepted. You can always check the status of your submissions or your schedule by visiting your personal pane on Great Burlesque Expo".  The bold is just there for clarity; it shouldn't be there in the email.

**Comment by bethlakshmi** [comment]
That can work today - {{ bid }} will give you the title most of the time (any time you mess with the templates, this bears some testing).  But also {{ bid.b_title }} should do it.  And there's some other data options based on "bid".  I'll take the action at some point to write up a little user guide in the "description" field of the Email Templates in the Post Office section so you have a reference for editing.

**Comment by bethlakshmi** [comment]
Updated on live site.  Put comments on every current template:
http://www.burlesque-expo.com/admin/post_office/emailtemplate/?o=1

so that the fields avaiable are clear.
