### ISSUE TITLE
Export Volunteers doesn't do what I need it to do

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#987]
I don't think this is technically a bug.  I think the functionality is working as intended, we're just missing a step in translation.

When I go to http://burlesque-expo.com/admin/gbe/volunteer/?accepted__exact=3&conference__id__exact=2&submitted__exact=1

and use the _Export Selected Volunteers_ function, the resulting export doesn't include anything like names or contact information -- which is what I was hoping to get.

**Comment by bethlakshmi** [comment]
Addressed as #1135
